from torch import Tensor
from .module import Module

__all__ = ["ChannelShuffle"]

class ChannelShuffle(Module):
    __constants__ = ...
    groups: int
    def __init__(self, groups: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def extra_repr(self) -> str: ...
