from collections import OrderedDict
from collections import abc as container_abcs
from collections.abc import Callable, Iterable, Iterator, Mapping
from typing import TYPE_CHECKING, Any, Self, TypeVar, overload
from warnings import deprecated

from torch._jit_internal import _copy_to_script_wrapper

from .module import Module

if TYPE_CHECKING: ...
__all__ = ["Container", "ModuleDict", "ModuleList", "ParameterDict", "ParameterList", "Sequential"]
T = TypeVar("T", bound=Module)

@deprecated(
    "`nn.Container` is deprecated. All of it's functionality is now implemented in `nn.Module`. Subclass that instead.",
    category=FutureWarning,
)
class Container(Module):
    def __init__(self, **kwargs: Any) -> None: ...

class Sequential[**P = ..., R = Any](Module[P, R]):
    _modules: dict[str, Module[P, R]]
    @overload
    def __init__(self, *args: Module[P, R]) -> None: ...
    @overload
    def __init__(self, arg: OrderedDict[str, Module[P, R]]) -> None: ...
    def __init__(self, *args) -> None: ...
    def __getitem__(self, idx: slice | int) -> Sequential[P, R] | Module[P, R]: ...
    def __setitem__(self, idx: int, module: Module[P, R]) -> None: ...
    def __delitem__(self, idx: slice | int) -> None: ...
    def __len__(self) -> int: ...
    def __add__(self, other) -> Sequential[P, R]: ...
    def pop(self, key: int | slice) -> Module[P, R]: ...
    def __iadd__(self, other) -> Self: ...
    def __mul__(self, other: int) -> Sequential[P, R]: ...
    def __rmul__(self, other: int) -> Sequential[P, R]: ...
    def __imul__(self, other: int) -> Self: ...
    def __dir__(self) -> list[str]: ...
    def __iter__(self) -> Iterator[Module[P, R]]: ...
    def append(self, module: Module[P, R]) -> Self: ...
    def insert(self, index: int, module: Module[P, R]) -> Self: ...
    def extend(self, sequential: Iterable[Module[P, R]]) -> Self: ...

class ModuleList[**P, R](Module[P, R]):
    _modules: dict[str, Module[P, R]]
    def __init__(self, modules: Iterable[Module[P, R]] | None = ...) -> None: ...
    @overload
    def __getitem__(self, idx: slice) -> ModuleList[P, R]: ...
    @overload
    def __getitem__(self, idx: int) -> Module[P, R]: ...
    def __getitem__(self, idx: int | slice) -> Module[P, R] | ModuleList[P, R]: ...
    def __setitem__(self, idx: int, module: Module[P, R]) -> None: ...
    def __delitem__(self, idx: int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Module[P, R]]: ...
    def __iadd__(self, modules: Iterable[Module[P, R]]) -> Self: ...
    def __add__(self, other: Iterable[Module[P, R]]) -> ModuleList[P, R]: ...
    def __dir__(self) -> list[str]: ...
    def insert(self, index: int, module: Module[P, R]) -> None: ...
    def append(self, module: Module[P, R]) -> Self: ...
    def pop(self, key: int | slice) -> Module[P, R]: ...
    def extend(self, modules: Iterable[Module[P, R]]) -> Self: ...

class ModuleDict[**P, R](Module[P, R]):
    _modules: dict[str, Module[P, R]]
    def __init__(self, modules: Mapping[str, Module[P, R]] | None = ...) -> None: ...
    def __getitem__(self, key: str) -> Module[P, R]: ...
    def __setitem__(self, key: str, module: Module[P, R]) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Module[P, R]: ...
    def keys(self) -> container_abcs.KeysView[str]: ...
    def items(self) -> container_abcs.ItemsView[str, Module[P, R]]: ...
    def values(self) -> container_abcs.ValuesView[Module[P, R]]: ...
    def update(self, modules: Mapping[str, Module[P, R]]) -> None: ...

class ParameterList(Module):
    def __init__(self, values: Iterable[Any] | None = ...) -> None: ...
    @overload
    def __getitem__(self, idx: int) -> Any: ...
    @overload
    def __getitem__(self: T, idx: slice) -> T: ...
    def __getitem__(self, idx) -> Self | Any: ...
    def __setitem__(self, idx: int, param: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __iadd__(self, parameters: Iterable[Any]) -> Self: ...
    def __dir__(self) -> list[str]: ...
    def append(self, value: Any) -> Self: ...
    def extend(self, values: Iterable[Any]) -> Self: ...
    def extra_repr(self) -> str: ...
    def __call__(self, *args, **kwargs): ...

class ParameterDict(Module):
    def __init__(self, parameters: Any = ...) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __reversed__(self) -> Iterator[str]: ...
    def copy(self) -> ParameterDict: ...
    def __contains__(self, key: str) -> bool: ...
    def setdefault(self, key: str, default: Any | None = ...) -> Any: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Any: ...
    def popitem(self) -> tuple[str, Any]: ...
    def get(self, key: str, default: Any | None = ...) -> Any: ...
    def fromkeys(self, keys: Iterable[str], default: Any | None = ...) -> ParameterDict: ...
    def keys(self) -> container_abcs.KeysView[str]: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def values(self) -> Iterable[Any]: ...
    def update(self, parameters: Mapping[str, Any] | ParameterDict) -> None: ...
    def extra_repr(self) -> str: ...
    def __call__(self, input): ...
    def __or__(self, other: ParameterDict) -> ParameterDict: ...
    def __ror__(self, other: ParameterDict) -> ParameterDict: ...
    def __ior__(self, other: ParameterDict) -> Self: ...
