from typing import Any, Protocol

__all__ = ["LazyModuleMixin"]

class _LazyProtocol(Protocol):
    def register_forward_pre_hook(self, hook, *, prepend=..., with_kwargs=...) -> None: ...

class LazyModuleMixin:
    cls_to_become: type[Any] | None = ...
    def __init__(self: _LazyProtocol, *args, **kwargs) -> None: ...
    def initialize_parameters(self: _LazyProtocol, *args, **kwargs): ...
    def has_uninitialized_params(self: _LazyProtocol) -> bool: ...
