from typing import Any

__all__ = ["consume_prefix_in_state_dict_if_present"]
_single = ...
_pair = ...
_triple = ...
_quadruple = ...

def consume_prefix_in_state_dict_if_present(state_dict: dict[str, Any], prefix: str) -> None: ...
