import torch
from torch import Tensor, nn

from ...modeling_outputs import (
    BackboneOutput,
    BaseModelOutputWithNoAttention,
    BaseModelOutputWithPoolingAndNoAttention,
    ImageClassifierOutputWithNoAttention,
)
from ...modeling_utils import PreTrainedModel
from ...utils.backbone_utils import BackboneMixin
from .configuration_resnet import ResNetConfig

"""PyTorch ResNet model."""
logger = ...

class ResNetConvLayer(nn.Module):
    def __init__(
        self, in_channels: int, out_channels: int, kernel_size: int = ..., stride: int = ..., activation: str = ...
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class ResNetEmbeddings(nn.Module):
    def __init__(self, config: ResNetConfig) -> None: ...
    def forward(self, pixel_values: Tensor) -> Tensor: ...

class ResNetShortCut(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, stride: int = ...) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class ResNetBasicLayer(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, stride: int = ..., activation: str = ...) -> None: ...
    def forward(self, hidden_state): ...

class ResNetBottleNeckLayer(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        stride: int = ...,
        activation: str = ...,
        reduction: int = ...,
        downsample_in_bottleneck: bool = ...,
    ) -> None: ...
    def forward(self, hidden_state): ...

class ResNetStage(nn.Module):
    def __init__(
        self, config: ResNetConfig, in_channels: int, out_channels: int, stride: int = ..., depth: int = ...
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class ResNetEncoder(nn.Module):
    def __init__(self, config: ResNetConfig) -> None: ...
    def forward(
        self, hidden_state: Tensor, output_hidden_states: bool = ..., return_dict: bool = ...
    ) -> BaseModelOutputWithNoAttention: ...

class ResNetPreTrainedModel(PreTrainedModel):
    config: ResNetConfig
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...

class ResNetModel(ResNetPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> BaseModelOutputWithPoolingAndNoAttention: ...

class ResNetForImageClassification(ResNetPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> ImageClassifierOutputWithNoAttention: ...

class ResNetBackbone(ResNetPreTrainedModel, BackboneMixin):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> BackboneOutput: ...

__all__ = ["ResNetBackbone", "ResNetForImageClassification", "ResNetModel", "ResNetPreTrainedModel"]
