import torch
from torchvision.transforms import functional as F

from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    BatchFeature,
    DefaultFastImageProcessorKwargs,
    SizeDict,
)
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import is_torchvision_available

if is_torchvision_available(): ...
logger = ...
MAX_IMAGE_SIZE = ...

def get_resize_output_image_size(image, resolution_max_side: int) -> tuple[int, int]: ...
def get_max_height_width(images_list: list[list[torch.Tensor]]) -> tuple[int, int]: ...
def make_pixel_mask(image: torch.Tensor, output_size: tuple[int, int]) -> torch.Tensor: ...

class Idefics3FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_pad: bool | None
    do_image_splitting: bool | None
    max_image_size: dict[str, int] | None
    return_row_col_info: bool | None

class Idefics3ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    max_image_size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_image_splitting = ...
    do_pad = ...
    return_row_col_info = ...
    valid_kwargs = Idefics3FastImageProcessorKwargs
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...
    def split_images(
        self, images: torch.Tensor, max_image_size: dict[str, int], interpolation: F.InterpolationMode = ...
    ):  # -> tuple[Tensor, list[int], list[int]]:

        ...
    def resize_for_vision_encoder(
        self, image: torch.Tensor, vision_encoder_max_size: int, interpolation: F.InterpolationMode = ...
    ):  # -> Tensor:

        ...
    def pad(
        self, image: torch.Tensor, padded_size: tuple[int, int], fill: int = ..., return_pixel_mask: bool = ...
    ):  # -> tuple[Any | Tensor, Tensor | None]:
        ...
    def preprocess(self, images: ImageInput, **kwargs: Unpack[Idefics3FastImageProcessorKwargs]) -> BatchFeature: ...
    def to_dict(self):  # -> dict[str, Any]:
        ...
    def get_number_of_image_patches(
        self, height: int, width: int, images_kwargs=...
    ):  # -> tuple[Any | Literal[1], Any | Literal[1], Any | Literal[1]]:

        ...

__all__ = ["Idefics3ImageProcessorFast"]
