import dataclasses
from pathlib import Path

default_demo_code = ...
static_only_demo_code = ...
layout_demo_code = ...
fallback_code = ...
PATTERN_RE = ...
PATTERN = ...

@dataclasses.dataclass
class ComponentFiles:
    template: str
    demo_code: str = ...
    python_file_name: str = ...
    js_dir: str = ...
    def __post_init__(self):  # -> None:
        ...

OVERRIDES = ...

def delete_contents(directory: str | Path) -> None: ...
