"""
This type stub file was generated by pyright.
"""

from ..runtime.jit import jit
from . import core, math

@core._tensor_member_fn
@jit
def cdiv(x, div):
    """
    Computes the ceiling division of :code:`x` by :code:`div`

    :param x: the input number
    :type x: Block
    :param div: the divisor
    :type div: Block
    """

@core._tensor_member_fn
@jit
@math._add_math_1arg_docstr("sigmoid")
def sigmoid(x): ...
@core._tensor_member_fn
@jit
@math._add_math_1arg_docstr("softmax")
def softmax(x, dim=..., keep_dims=..., ieee_rounding=...): ...
@core._tensor_member_fn
@jit
def ravel(x, can_reorder=...):
    """
    Returns a contiguous flattened view of :code:`x`.

    :param x: the input tensor
    :type x: Block
    """

@jit
def swizzle2d(i, j, size_i, size_j, size_g):  # -> tuple[Any, Any]:
    """
    Transforms the indices of a row-major `size_i * size_j` matrix into
    the indices of a column-major matrix for each group of `size_g` rows.

    For example, for :code:`size_i = size_j = 4` and :code:`size_g = 2`, it will
    transform ::

        [[0 , 1 , 2 , 3 ],
         [4 , 5 , 6 , 7 ],
         [8 , 9 , 10, 11],
         [12, 13, 14, 15]]

    into ::

        [[0, 2,  4 , 6 ],
         [1, 3,  5 , 7 ],
         [8, 10, 12, 14],
         [9, 11, 13, 15]]
    """

@jit
def zeros(shape, dtype):
    """
    Returns a tensor filled with the scalar value 0 for the given :code:`shape` and :code:`dtype`.

    :param shape: Shape of the new array, e.g., (8, 16) or (8, )
    :type shape: tuple of ints
    :param dtype: Data-type of the new array, e.g., :code:`tl.float16`
    :type dtype: DType
    """

@jit
def zeros_like(input):
    """
    Returns a tensor of zeros with the same shape and type as a given tensor.

    :param input: input tensor
    :type input: Tensor
    """

@core._tensor_member_fn
@jit
@core._add_reduction_docstr(
    "maximum", return_indices_arg="return_indices", tie_break_arg="return_indices_tie_break_left"
)
def max(
    input, axis=..., return_indices=..., return_indices_tie_break_left=..., keep_dims=...
):  # -> builtins.tuple[Any, Any] | triton.language.core.tuple:
    ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr("maximum index", tie_break_arg="tie_break_left")
def argmax(input, axis, tie_break_left=..., keep_dims=...): ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr(
    "minimum", return_indices_arg="return_indices", tie_break_arg="return_indices_tie_break_left"
)
def min(
    input, axis=..., return_indices=..., return_indices_tie_break_left=..., keep_dims=...
):  # -> builtins.tuple[Any, Any] | triton.language.core.tuple:
    ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr("minimum index", tie_break_arg="tie_break_left")
def argmin(input, axis, tie_break_left=..., keep_dims=...): ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr("sum", dtype_arg="dtype")
def sum(input, axis=..., keep_dims=..., dtype: core.constexpr = ...):  # -> tuple:
    ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr("xor sum")
def xor_sum(input, axis=..., keep_dims=...):  # -> tuple:
    ...
@core._tensor_member_fn
@jit
@core._add_reduction_docstr("reduce_or")
def reduce_or(input, axis, keep_dims=...):  # -> tuple:
    ...
@core._tensor_member_fn
@jit
@core._add_scan_docstr("cumsum", dtype_arg="dtype")
def cumsum(input, axis=..., reverse=..., dtype: core.constexpr = ...): ...
@core._tensor_member_fn
@jit
@core._add_scan_docstr("cumprod")
def cumprod(input, axis=..., reverse=...): ...
@jit
def sort_impl(x, k: core.constexpr = ..., dim: core.constexpr = ..., descending: core.constexpr = ...):
    """
    Sorts a tensor along a specified dimension.

    :param x: The input tensor to be sorted.
    :type x: Tensor
    :param dim: The dimension along which to sort the tensor. If None, the tensor is sorted along the last dimension. Currently, only sorting along the last dimension is supported.
    :type dim: int, optional
    :param k: the number of top elements to select. If none, assume k = x.shape[dim]
    :type k: int, optional
    :param descending: If set to True, the tensor is sorted in descending order. If set to False, the tensor is sorted in ascending order.
    :type descending: bool, optional
    """

@jit
def sort(x, dim: core.constexpr = ..., descending: core.constexpr = ...): ...
@jit
def topk(x, k: core.constexpr, dim: core.constexpr = ...): ...
@jit
def bitonic_merge(x, dim: core.constexpr = ..., descending: core.constexpr = ...): ...
@core._tensor_member_fn
@jit
def flip(x, dim=...):
    """
    Flips a tensor `x` along the dimension `dim`.

    :param x: the first input tensor
    :type x: Block
    :param dim: the dimension to flip along
    :type dim: int
    """

@jit
def interleave(a, b):
    """
    Interleaves the values of two tensors along their last dimension. The two tensors must have the same shape.
    Equivalent to `tl.join(a, b).reshape(a.shape[:-1] + [2 * a.shape[-1]])`

    :param a: The first input tensor.
    :type a: Tensor
    :param b: The second input tensor.
    :type b: Tensor
    """
