import types

@staticmethod
def deserialize(bytes) -> None: ...
@staticmethod
def serialize(tensor_dict, metadata=None) -> None: ...
@staticmethod
def serialize_file(tensor_dict, filename, metadata=None) -> None: ...

class safe_open:
    def __init__(self, filename, framework, device=...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None,
        _exc_value: BaseException | None,
        _traceback: types.TracebackType | None,
    ) -> None: ...
    def get_slice(self, name) -> None: ...
    def get_tensor(self, name) -> None: ...
    def keys(self) -> None: ...
    def metadata(self) -> None: ...

class SafetensorError(Exception): ...
