import ast

import torch

class AttributeTypeIsSupportedChecker(ast.NodeVisitor):
    def check(self, nn_module: torch.nn.Module) -> None: ...
    def visit_Assign(self, node): ...
    def visit_AnnAssign(self, node): ...
    def visit_Call(self, node): ...
