import contextlib

@contextlib.contextmanager
def optimized_execution(should_optimize): ...
@contextlib.contextmanager
def fuser(name): ...

last_executed_optimized_graph = ...

def set_fusion_strategy(strategy: list[tuple[str, int]]): ...
