def save(m, f, _extra_files=...):  # -> None:

    ...
def load(f, map_location=..., _extra_files=..., _restore_shapes=...): ...
def validate_map_location(map_location=...):  # -> device | None:
    ...
def jit_module_from_flatbuffer(f): ...
def save_jit_module_to_flatbuffer(m, f, _extra_files=...):  # -> None:

    ...
def get_flatbuffer_module_info(path_or_file): ...
