def save(m, f, _extra_files=...): ...
def load(f, map_location=..., _extra_files=..., _restore_shapes=...): ...
def validate_map_location(map_location=...): ...
def jit_module_from_flatbuffer(f): ...
def save_jit_module_to_flatbuffer(m, f, _extra_files=...): ...
def get_flatbuffer_module_info(path_or_file): ...
