import weakref
from typing import Any

class EnabledProxy:
    def __init__(self) -> None: ...
    def parse_env(self, name, default, true_message, false_message): ...
    def __bool__(self) -> bool: ...

_enabled = ...

def disable(): ...
def enable(): ...

_python_cu = ...
_script_classes: dict[type[Any], type[Any]] = ...
_name_to_pyclass: dict[str, type[Any]] = ...
_jit_caching_layer: weakref.WeakKeyDictionary = ...
_jit_function_overload_caching: weakref.WeakKeyDictionary = ...
