"""
JIT-related state.

This module stores various pieces of Python-global state relating to the JIT.

This is not intended to be imported directly; please the exposed
functionalities in `torch.jit`.
"""

import weakref
from typing import Any

class EnabledProxy:
    """
    Stores whether the JIT is enabled or not.

    This is just a wrapper for a bool, so that we get reference semantics
    """
    def __init__(self) -> None: ...
    def parse_env(self, name, default, true_message, false_message): ...
    def __bool__(self) -> bool: ...

_enabled = ...

def disable(): ...
def enable(): ...

_python_cu = ...
_script_classes: dict[type[Any], type[Any]] = ...
_name_to_pyclass: dict[str, type[Any]] = ...
_jit_caching_layer: weakref.WeakKeyDictionary = ...
_jit_function_overload_caching: weakref.WeakKeyDictionary = ...
