from collections.abc import Callable

import torch
import torch.fx as fx

aten = ...

def get_aten_target(node: fx.Node) -> Callable: ...

rand_ops = ...

def fx_graph_cse(fx_g: torch.fx.graph.Graph):  # -> Graph:
    ...
def raise_getitems(gm: fx.GraphModule) -> fx.GraphModule: ...
def strip_overloads(gm):  # -> None:

    ...
def get_placeholders(graph): ...
def get_outputs(graph): ...
