import contextlib
from abc import ABC, abstractmethod
from typing import Any

from torch._C._functorch import CInterpreter

class FuncTorchInterpreter(ABC):
    def __init__(self, cptr: Any) -> None: ...
    @abstractmethod
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def level(self): ...
    def key(self): ...
    def get_state(self): ...
    def check_state(self, state): ...
    def __getstate__(self): ...

@contextlib.contextmanager
def temporarily_pop_interpreter_stack(): ...
@contextlib.contextmanager
def temporarily_clear_interpreter_stack(): ...
@contextlib.contextmanager
def temporarily_restore_interpreter_stack(stack): ...

class VmapInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def process(self, op, args, kwargs): ...
    def batch_size(self): ...
    def randomness(self): ...
    def get_state(self): ...

@contextlib.contextmanager
def nested(*contexts): ...

class GradInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def lift(self, args, kwargs): ...
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def prev_grad_mode(self): ...
    def get_state(self): ...

class JvpInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def lift(self, args, kwargs): ...
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def prev_fwd_grad_mode(self): ...
    def get_state(self): ...

class FunctionalizeInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def process(self, op, args, kwargs): ...
    def functionalize_add_back_views(self): ...
    def get_state(self): ...

def coerce_cinterpreter(cinterpreter: CInterpreter) -> FuncTorchInterpreter: ...
def retrieve_current_functorch_interpreter() -> FuncTorchInterpreter: ...
def retrieve_all_functorch_interpreters() -> list[FuncTorchInterpreter]: ...
def compare_functorch_state(states: list[tuple[Any, ...]]) -> bool: ...
def dispatch_functorch(op, args, kwargs): ...
