import contextlib

type in_dims_t = int | tuple
type out_dims_t = int | tuple[int, ...]

def doesnt_support_saved_tensors_hooks(f): ...
def vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs): ...
def get_chunk_sizes(total_elems, chunk_size): ...
@contextlib.contextmanager
def vmap_increment_nesting(batch_size, randomness): ...
def restore_vmap(func, in_dims, batch_size, randomness): ...
def wrap_batched(args, bdims, level): ...
def unwrap_batched(args, level): ...
