from ....tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for GPTSANJapanese."""
logger = ...
VOCAB_FILES_NAMES = ...

def load_vocab_and_emoji(
    vocab_file, emoji_file
):  # -> tuple[OrderedDict[Any, Any], OrderedDict[Any, Any], OrderedDict[Any, Any], Any]:

    ...

class GPTSanJapaneseTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self,
        vocab_file,
        emoji_file,
        unk_token=...,
        pad_token=...,
        bos_token=...,
        eos_token=...,
        sep_token=...,
        do_clean_text=...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def convert_tokens_to_string(self, tokens):  # -> LiteralString:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def prepare_for_tokenization(
        self, text, prefix_text=..., add_sep_token=..., **kwargs
    ):  # -> tuple[Any, dict[str, Any]]:
        ...

class SubWordJapaneseTokenizer:
    def __init__(self, vocab, ids_to_tokens, emoji) -> None: ...
    def __len__(self) -> int:  # -> int:
        ...
    def clean_text(self, content):  # -> str:
        ...
    def tokenize(self, text, clean=...):  # -> list[Any]:
        ...
    def convert_id_to_token(self, index): ...

__all__ = ["GPTSanJapaneseTokenizer"]
