from ..cutlass_utils import try_import_cutlass
from cutlass_library.gemm_operation import *
from cutlass_library.library import *

if try_import_cutlass():
    _LOGGER = ...
    class EmitGemmUniversal3xInstanceWithEVT:
        def __init__(self, operation_suffix=..., evt_name=...) -> None: ...
        def instance_template(self):  # -> LiteralString:
            ...
        def emit_block_scale_epilogue_functor(self, operation): ...
        @staticmethod
        def pointerize_if_grouped(operation, layout): ...
        @staticmethod
        def problem_shape(operation):  # -> LiteralString | Literal['cute::Shape<int,int,int,int>']:
            ...
        def emit(self, operation): ...
