from cutlass_library.gemm_operation import *
from cutlass_library.library import *

from ..cutlass_utils import try_import_cutlass

if try_import_cutlass():
    _LOGGER = ...
    class EmitGemmUniversal3xInstanceWithEVT:
        def __init__(self, operation_suffix=..., evt_name=...) -> None: ...
        def instance_template(self): ...
        def emit_block_scale_epilogue_functor(self, operation): ...
        @staticmethod
        def pointerize_if_grouped(operation, layout): ...
        @staticmethod
        def problem_shape(operation): ...
        def emit(self, operation): ...
