from ...processing_utils import ProcessorMixin

"""
Audio/Text processor class for CLAP
"""

class ClapProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def __call__(self, text=..., audios=..., return_tensors=..., **kwargs):  # -> BatchEncoding:

        ...
    def batch_decode(self, *args, **kwargs): ...
    def decode(self, *args, **kwargs): ...
    @property
    def model_input_names(self):  # -> list[Any]:
        ...

__all__ = ["ClapProcessor"]
