from typing import Any

import numpy as np

from ..utils import is_torch_available
from .base import Pipeline

if is_torch_available(): ...
logger = ...

def ffmpeg_read(bpayload: bytes, sampling_rate: int) -> np.ndarray: ...

class AudioClassificationPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, inputs: np.ndarray | bytes | str | dict, **kwargs: Any) -> list[dict[str, Any]]: ...
    def preprocess(self, inputs):  # -> Any:
        ...
    def postprocess(self, model_outputs, top_k=..., function_to_apply=...):  # -> list[dict[str, Any | str]]:
        ...
