from typing import Any

from .base import GenericTensor, Pipeline

class FeatureExtractionPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def preprocess(self, inputs, **tokenize_kwargs) -> dict[str, GenericTensor]: ...
    def postprocess(self, model_outputs, return_tensors=...):  # -> None:
        ...
    def __call__(self, *args: str | list[str], **kwargs: Any) -> Any | list[Any]: ...
