from typing import Any, overload

from PIL import Image

from ..utils import is_torch_available, is_vision_available
from .base import Pipeline

if is_vision_available(): ...
if is_torch_available(): ...
logger = ...

class ImageToImagePipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def __call__(self, images: str | Image.Image, **kwargs: Any) -> Image.Image: ...
    @overload
    def __call__(self, images: list[str] | list[Image.Image], **kwargs: Any) -> list[Image.Image]: ...
    def __call__(
        self, images: str | list[str] | Image.Image | list[Image.Image], **kwargs: Any
    ) -> Image.Image | list[Image.Image]: ...
    def preprocess(
        self, image, timeout=...
    ):  # -> transformers.feature_extraction_utils.BatchFeature | Any | transformers.image_processing_base.BatchFeature:
        ...
    def postprocess(self, model_outputs):  # -> list[Any]:
        ...
