from typing import Any, overload

from PIL import Image

from ..utils import ExplicitEnum, is_tf_available, is_torch_available, is_vision_available
from .base import Pipeline

if is_vision_available(): ...
if is_tf_available(): ...
if is_torch_available(): ...
logger = ...

def sigmoid(_outputs):  # -> Any:
    ...
def softmax(_outputs):  # -> Any:
    ...

class ClassificationFunction(ExplicitEnum):
    SIGMOID = ...
    SOFTMAX = ...
    NONE = ...

class ImageClassificationPipeline(Pipeline):
    function_to_apply: ClassificationFunction = ...
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def __call__(self, inputs: str | Image.Image, **kwargs: Any) -> list[dict[str, Any]]: ...
    @overload
    def __call__(self, inputs: list[str] | list[Image.Image], **kwargs: Any) -> list[list[dict[str, Any]]]: ...
    def __call__(
        self, inputs: str | list[str] | Image.Image | list[Image.Image], **kwargs: Any
    ) -> list[dict[str, Any]] | list[list[dict[str, Any]]]: ...
    def preprocess(
        self, image, timeout=...
    ):  # -> transformers.feature_extraction_utils.BatchFeature | Any | transformers.image_processing_base.BatchFeature:
        ...
    def postprocess(self, model_outputs, function_to_apply=..., top_k=...):  # -> list[dict[str, Any | str]]:
        ...
