from typing import TYPE_CHECKING, Any, overload

from PIL import Image

from ..utils import add_end_docstrings, is_torch_available, is_vision_available
from .base import Pipeline, build_pipeline_init_args

if is_vision_available(): ...
if is_torch_available(): ...
if TYPE_CHECKING: ...
logger = ...

class ObjectDetectionPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def __call__(self, image: str | Image.Image, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    @overload
    def __call__(
        self, image: list[str] | list[Image.Image], *args: Any, **kwargs: Any
    ) -> list[list[dict[str, Any]]]: ...
    def __call__(self, *args, **kwargs) -> list[dict[str, Any]] | list[list[dict[str, Any]]]: ...
    def preprocess(
        self, image, timeout=...
    ):  # -> BatchEncoding | Any | transformers.feature_extraction_utils.BatchFeature | transformers.image_processing_base.BatchFeature:
        ...
    def postprocess(
        self, model_outputs, threshold=...
    ):  # -> list[dict[str, Any | str | dict[str, int]]] | list[dict[str, Any]]:
        ...
