from typing import Any, overload

from ..utils import is_torch_available
from .base import Pipeline

if is_torch_available(): ...
DEFAULT_VOCODER_ID = ...

class TextToAudioPipeline(Pipeline):
    _load_processor = ...
    _pipeline_calls_generate = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    _default_generation_config = ...
    def __init__(self, *args, vocoder=..., sampling_rate=..., no_processor=..., **kwargs) -> None: ...
    def preprocess(self, text, **kwargs):  # -> BatchEncoding | Any:
        ...
    @overload
    def __call__(self, text_inputs: str, **forward_params: Any) -> dict[str, Any]: ...
    @overload
    def __call__(self, text_inputs: list[str], **forward_params: Any) -> list[dict[str, Any]]: ...
    def __call__(self, text_inputs: str | list[str], **forward_params) -> dict[str, Any] | list[dict[str, Any]]: ...
    def postprocess(self, audio):  # -> dict[Any, Any]:
        ...
