from typing import Any

from ..utils import ExplicitEnum, add_end_docstrings, is_tf_available, is_torch_available
from .base import GenericTensor, Pipeline, build_pipeline_init_args

if is_tf_available(): ...
if is_torch_available(): ...

def sigmoid(_outputs):  # -> Any:
    ...
def softmax(_outputs):  # -> Any:
    ...

class ClassificationFunction(ExplicitEnum):
    SIGMOID = ...
    SOFTMAX = ...
    NONE = ...

class TextClassificationPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    return_all_scores = ...
    function_to_apply = ...
    def __init__(self, **kwargs) -> None: ...
    def __call__(
        self, inputs: str | list[str] | dict[str, str] | list[dict[str, str]], **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    def preprocess(self, inputs, **tokenizer_kwargs) -> dict[str, GenericTensor]: ...
    def postprocess(
        self, model_outputs, function_to_apply=..., top_k=..., _legacy=...
    ):  # -> dict[str, Any | str] | list[dict[str, Any | str]]:
        ...
