from typing import Any, overload

from ..utils import add_end_docstrings, is_av_available, is_torch_available
from .base import Pipeline, build_pipeline_init_args

if is_av_available(): ...
if is_torch_available(): ...
logger = ...

class VideoClassificationPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def __call__(self, inputs: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    @overload
    def __call__(self, inputs: list[str], **kwargs: Any) -> list[list[dict[str, Any]]]: ...
    def __call__(
        self, inputs: str | list[str] | None = ..., **kwargs
    ):  # -> list[Any] | PipelineIterator | Generator[Any, Any, None] | Tensor | Any | None:

        ...
    def preprocess(
        self, video, num_frames=..., frame_sampling_rate=...
    ):  # -> transformers.feature_extraction_utils.BatchFeature | Any | transformers.image_processing_base.BatchFeature:
        ...
    def postprocess(self, model_outputs, top_k=..., function_to_apply=...):  # -> list[dict[str, Any | str]]:
        ...

def read_video_pyav(container, indices):  # -> NDArray[Any]:
    ...
