from typing import TYPE_CHECKING, Any

from ...tokenization_utils import PreTrainedTokenizer
from ...tokenization_utils_base import TextInput
from ...utils.import_utils import requires

if TYPE_CHECKING: ...
logger = ...
VOCAB_FILES_NAMES = ...
SPIECE_UNDERLINE = ...

@requires(backends=("sentencepiece",))
class GemmaTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self,
        vocab_file,
        unk_token=...,
        bos_token=...,
        eos_token=...,
        pad_token=...,
        sp_model_kwargs: dict[str, Any] | None = ...,
        add_bos_token=...,
        add_eos_token=...,
        clean_up_tokenization_spaces=...,
        use_default_system_prompt=...,
        spaces_between_special_tokens=...,
        **kwargs,
    ) -> None: ...
    def __getstate__(self):  # -> dict[str, Any]:
        ...
    def __setstate__(self, d):  # -> None:
        ...
    @property
    def vocab_size(self): ...
    def get_vocab(self):  # -> dict[str, int]:

        ...
    def tokenize(self, text: TextInput, **kwargs) -> list[str]: ...
    def convert_tokens_to_string(self, tokens): ...
    def save_vocabulary(self, save_directory, filename_prefix: str | None = ...) -> tuple[str]: ...
    def build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=...):  # -> list[str | list[str] | Any | None]:
        ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...

__all__ = ["GemmaTokenizer"]
