from typing import Literal

from .base import BaseInferenceType, dataclass_with_extra

type AutomaticSpeechRecognitionEarlyStoppingEnum = Literal["never"]

@dataclass_with_extra
class AutomaticSpeechRecognitionGenerationParameters(BaseInferenceType):
    do_sample: bool | None = ...
    early_stopping: bool | AutomaticSpeechRecognitionEarlyStoppingEnum | None = ...
    epsilon_cutoff: float | None = ...
    eta_cutoff: float | None = ...
    max_length: int | None = ...
    max_new_tokens: int | None = ...
    min_length: int | None = ...
    min_new_tokens: int | None = ...
    num_beam_groups: int | None = ...
    num_beams: int | None = ...
    penalty_alpha: float | None = ...
    temperature: float | None = ...
    top_k: int | None = ...
    top_p: float | None = ...
    typical_p: float | None = ...
    use_cache: bool | None = ...

@dataclass_with_extra
class AutomaticSpeechRecognitionParameters(BaseInferenceType):
    generation_parameters: AutomaticSpeechRecognitionGenerationParameters | None = ...
    return_timestamps: bool | None = ...

@dataclass_with_extra
class AutomaticSpeechRecognitionInput(BaseInferenceType):
    inputs: str
    parameters: AutomaticSpeechRecognitionParameters | None = ...

@dataclass_with_extra
class AutomaticSpeechRecognitionOutputChunk(BaseInferenceType):
    text: str
    timestamp: list[float]

@dataclass_with_extra
class AutomaticSpeechRecognitionOutput(BaseInferenceType):
    text: str
    chunks: list[AutomaticSpeechRecognitionOutputChunk] | None = ...
