from typing import Any, Literal

from .base import BaseInferenceType, dataclass_with_extra

type TextToSpeechEarlyStoppingEnum = Literal["never"]

@dataclass_with_extra
class TextToSpeechGenerationParameters(BaseInferenceType):
    do_sample: bool | None = ...
    early_stopping: bool | TextToSpeechEarlyStoppingEnum | None = ...
    epsilon_cutoff: float | None = ...
    eta_cutoff: float | None = ...
    max_length: int | None = ...
    max_new_tokens: int | None = ...
    min_length: int | None = ...
    min_new_tokens: int | None = ...
    num_beam_groups: int | None = ...
    num_beams: int | None = ...
    penalty_alpha: float | None = ...
    temperature: float | None = ...
    top_k: int | None = ...
    top_p: float | None = ...
    typical_p: float | None = ...
    use_cache: bool | None = ...

@dataclass_with_extra
class TextToSpeechParameters(BaseInferenceType):
    generation_parameters: TextToSpeechGenerationParameters | None = ...

@dataclass_with_extra
class TextToSpeechInput(BaseInferenceType):
    inputs: str
    parameters: TextToSpeechParameters | None = ...

@dataclass_with_extra
class TextToSpeechOutput(BaseInferenceType):
    audio: Any
    sampling_rate: float | None = ...
