from typing import Any

from .base import BaseInferenceType, dataclass_with_extra

@dataclass_with_extra
class TextToImageParameters(BaseInferenceType):
    guidance_scale: float | None = ...
    height: int | None = ...
    negative_prompt: str | None = ...
    num_inference_steps: int | None = ...
    scheduler: str | None = ...
    seed: int | None = ...
    width: int | None = ...

@dataclass_with_extra
class TextToImageInput(BaseInferenceType):
    inputs: str
    parameters: TextToImageParameters | None = ...

@dataclass_with_extra
class TextToImageOutput(BaseInferenceType):
    image: Any
