from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import is_torch_available, is_torchvision_available
from ...video_utils import VideoInput

"""Fast Image processor class for Qwen2-VL."""
if is_torch_available(): ...
if is_torchvision_available(): ...
logger = ...

class Qwen2VLFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    min_pixels: int | None
    max_pixels: int | None
    patch_size: int | None
    temporal_patch_size: int | None
    merge_size: int | None

class Qwen2VLImageProcessorFast(BaseImageProcessorFast):
    do_resize = ...
    resample = ...
    size = ...
    do_rescale = ...
    do_normalize = ...
    image_mean = ...
    image_std = ...
    do_convert_rgb = ...
    patch_size = ...
    temporal_patch_size = ...
    merge_size = ...
    min_pixels = ...
    max_pixels = ...
    valid_kwargs = Qwen2VLFastImageProcessorKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[Qwen2VLFastImageProcessorKwargs]) -> None: ...
    def preprocess(
        self, images: ImageInput, videos: VideoInput | None = ..., **kwargs: Unpack[Qwen2VLFastImageProcessorKwargs]
    ) -> BatchFeature: ...
    def get_number_of_image_patches(self, height: int, width: int, images_kwargs=...): ...

__all__ = ["Qwen2VLImageProcessorFast"]
