import types
from typing import Any

class _ClassNamespace(types.ModuleType):
    def __init__(self, name: str) -> None: ...
    def __getattr__(self, attr: str) -> Any: ...

class _Classes(types.ModuleType):
    __file__ = ...
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> _ClassNamespace: ...
    @property
    def loaded_libraries(self) -> Any: ...
    def load_library(self, path: str) -> None: ...

classes = ...
