from typing import Optional
from torch import Tensor

"""Various linear algebra utility methods for internal use."""

def is_sparse(A): ...
def get_floating_dtype(A):  # -> dtype:

    ...
def matmul(A: Optional[Tensor], B: Tensor) -> Tensor: ...
def bform(X: Tensor, A: Optional[Tensor], Y: Tensor) -> Tensor: ...
def qform(A: Optional[Tensor], S: Tensor):  # -> Tensor:

    ...
def basis(A):  # -> ...:

    ...
def symeig(A: Tensor, largest: Optional[bool] = ...) -> tuple[Tensor, Tensor]: ...
def matrix_rank(input, tol=..., symmetric=..., *, out=...) -> Tensor: ...
def solve(input: Tensor, A: Tensor, *, out=...) -> tuple[Tensor, Tensor]: ...
def lstsq(input: Tensor, A: Tensor, *, out=...) -> tuple[Tensor, Tensor]: ...
def eig(self: Tensor, eigenvectors: bool = ..., *, e=..., v=...) -> tuple[Tensor, Tensor]: ...
