import os
from typing import Any
from torch.serialization import MAP_LOCATION

class _Faketqdm:
    def __init__(self, total=..., disable=..., unit=..., *args, **kwargs) -> None: ...
    def update(self, n) -> None: ...
    def set_description(self, *args, **kwargs) -> None: ...
    def write(self, s) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

__all__ = ["download_url_to_file", "get_dir", "help", "list", "load", "load_state_dict_from_url", "set_dir"]
HASH_REGEX = ...
_TRUSTED_REPO_OWNERS = ...
ENV_GITHUB_TOKEN = ...
ENV_TORCH_HOME = ...
ENV_XDG_CACHE_HOME = ...
DEFAULT_CACHE_DIR = ...
VAR_DEPENDENCY = ...
MODULE_HUBCONF = ...
READ_DATA_CHUNK = ...
_hub_dir: str | None = ...

def get_dir() -> str: ...
def set_dir(d: str | os.PathLike) -> None: ...
def list(github, force_reload=..., skip_validation=..., trust_repo=..., verbose=...) -> list[str]: ...
def help(github, model, force_reload=..., skip_validation=..., trust_repo=...) -> str | None: ...
def load(
    repo_or_dir, model, *args, source=..., trust_repo=..., force_reload=..., verbose=..., skip_validation=..., **kwargs
) -> object: ...
def download_url_to_file(url: str, dst: str, hash_prefix: str | None = ..., progress: bool = ...) -> None: ...
def load_state_dict_from_url(
    url: str,
    model_dir: str | None = ...,
    map_location: MAP_LOCATION = ...,
    progress: bool = ...,
    check_hash: bool = ...,
    file_name: str | None = ...,
    weights_only: bool = ...,
) -> dict[str, Any]: ...
