import torch

class DistAutogradContext: ...

def backward(context_id: int, roots: list[torch.Tensor], retain_graph: bool = ...) -> None: ...
def get_gradients(context_id: int) -> dict[torch.Tensor, torch.Tensor]: ...
