from dataclasses import dataclass
from typing import Any

import torch
from torch import nn

from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, ModelOutput
from ...modeling_utils import PreTrainedModel
from .configuration_vits import VitsConfig

"""PyTorch VITS model."""
logger = ...

@dataclass
class VitsModelOutput(ModelOutput):
    waveform: torch.FloatTensor | None = ...
    sequence_lengths: torch.FloatTensor | None = ...
    spectrogram: tuple[torch.FloatTensor] | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
class VitsTextEncoderOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    prior_means: torch.FloatTensor | None = ...
    prior_log_variances: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

@torch.jit.script
def fused_add_tanh_sigmoid_multiply(input_a, input_b, num_channels):  # -> Tensor:
    ...

class VitsWaveNet(torch.nn.Module):
    def __init__(self, config: VitsConfig, num_layers: int) -> None: ...
    def forward(self, inputs, padding_mask, global_conditioning=...): ...
    def remove_weight_norm(self):  # -> None:
        ...

class VitsPosteriorEncoder(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(self, inputs, padding_mask, global_conditioning=...):  # -> tuple[Any, Tensor, Tensor]:
        ...

class HifiGanResidualBlock(nn.Module):
    def __init__(self, channels, kernel_size=..., dilation=..., leaky_relu_slope=...) -> None: ...
    def get_padding(self, kernel_size, dilation=...): ...
    def apply_weight_norm(self):  # -> None:
        ...
    def remove_weight_norm(self):  # -> None:
        ...
    def forward(self, hidden_states): ...

class VitsHifiGan(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def apply_weight_norm(self):  # -> None:
        ...
    def remove_weight_norm(self):  # -> None:
        ...
    def forward(
        self, spectrogram: torch.FloatTensor, global_conditioning: torch.FloatTensor | None = ...
    ) -> torch.FloatTensor: ...

class VitsResidualCouplingLayer(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self, inputs, padding_mask, global_conditioning=..., reverse=...
    ):  # -> tuple[Tensor, Tensor] | tuple[Tensor, None]:
        ...

class VitsResidualCouplingBlock(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(self, inputs, padding_mask, global_conditioning=..., reverse=...):  # -> Tensor | Any:
        ...

class VitsDilatedDepthSeparableConv(nn.Module):
    def __init__(self, config: VitsConfig, dropout_rate=...) -> None: ...
    def forward(self, inputs, padding_mask, global_conditioning=...): ...

class VitsConvFlow(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self, inputs, padding_mask, global_conditioning=..., reverse=...
    ):  # -> tuple[Any, Tensor] | tuple[Any, None]:
        ...

class VitsElementwiseAffine(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self, inputs, padding_mask, global_conditioning=..., reverse=...
    ):  # -> tuple[Any, Tensor] | tuple[Any, None]:
        ...

class VitsStochasticDurationPredictor(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self, inputs, padding_mask, global_conditioning=..., durations=..., reverse=..., noise_scale=...
    ):  # -> Any | Tensor:
        ...

class VitsDurationPredictor(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, inputs, padding_mask, global_conditioning=...): ...

class VitsAttention(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        key_value_states: torch.Tensor | None = ...,
        attention_mask: torch.Tensor | None = ...,
        layer_head_mask: torch.Tensor | None = ...,
        output_attentions: bool = ...,
    ) -> tuple[torch.Tensor, torch.Tensor | None]: ...

class VitsFeedForward(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states, padding_mask): ...

class VitsEncoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        padding_mask: torch.FloatTensor,
        attention_mask: torch.Tensor | None = ...,
        output_attentions: bool = ...,
    ):  # -> tuple[Tensor, Any] | tuple[Tensor]:
        ...

class VitsEncoder(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.FloatTensor,
        padding_mask: torch.FloatTensor,
        attention_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutput: ...

class VitsTextEncoder(nn.Module):
    def __init__(self, config: VitsConfig) -> None: ...
    def forward(
        self,
        input_ids: torch.Tensor,
        padding_mask: torch.FloatTensor,
        attention_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.Tensor] | VitsTextEncoderOutput: ...

class VitsPreTrainedModel(PreTrainedModel):
    config: VitsConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...

class VitsModel(VitsPreTrainedModel):
    def __init__(self, config: VitsConfig) -> None: ...
    def get_encoder(self):  # -> VitsTextEncoder:
        ...
    def forward(
        self,
        input_ids: torch.Tensor | None = ...,
        attention_mask: torch.Tensor | None = ...,
        speaker_id: int | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
        labels: torch.FloatTensor | None = ...,
    ) -> tuple[Any] | VitsModelOutput: ...

__all__ = ["VitsModel", "VitsPreTrainedModel"]
