from threading import Thread

_IN_TOPLEVEL_PROCESS = ...

def in_toplevel_process() -> bool: ...

_watchdog_thread: Thread | None = ...
_original_parent: int | None = ...

def has_parent_changed() -> bool: ...
