import torch
from torch import nn

from ...modeling_outputs import (
    BackboneOutput,
    BaseModelOutputWithNoAttention,
    BaseModelOutputWithPoolingAndNoAttention,
    ImageClassifierOutputWithNoAttention,
)
from ...modeling_utils import PreTrainedModel
from ...utils.backbone_utils import BackboneMixin
from .configuration_convnext import ConvNextConfig

"""PyTorch ConvNext model."""
logger = ...

def drop_path(input: torch.Tensor, drop_prob: float = ..., training: bool = ...) -> torch.Tensor: ...

class ConvNextDropPath(nn.Module):
    def __init__(self, drop_prob: float | None = ...) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class ConvNextLayerNorm(nn.Module):
    def __init__(self, normalized_shape, eps=..., data_format=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class ConvNextEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextLayer(nn.Module):
    def __init__(self, config, dim, drop_path=...) -> None: ...
    def forward(self, hidden_states: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextStage(nn.Module):
    def __init__(
        self, config, in_channels, out_channels, kernel_size=..., stride=..., depth=..., drop_path_rates=...
    ) -> None: ...
    def forward(self, hidden_states: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextEncoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        hidden_states: torch.FloatTensor,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutputWithNoAttention: ...

class ConvNextPreTrainedModel(PreTrainedModel):
    config: ConvNextConfig
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...

class ConvNextModel(ConvNextPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutputWithPoolingAndNoAttention: ...

class ConvNextForImageClassification(ConvNextPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | ImageClassifierOutputWithNoAttention: ...

class ConvNextBackbone(ConvNextPreTrainedModel, BackboneMixin):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: torch.Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> BackboneOutput: ...

__all__ = ["ConvNextBackbone", "ConvNextForImageClassification", "ConvNextModel", "ConvNextPreTrainedModel"]
