from ...image_processing_utils_fast import BaseImageProcessorFast

"""Fast Image processor class for ViT."""

class ViTImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...

__all__ = ["ViTImageProcessorFast"]
