from dataclasses import dataclass
from typing import Optional

import torch
from torch import Tensor, nn
from torch.autograd import Function
from torch.autograd.function import once_differentiable

from ....file_utils import (
    ModelOutput,
    add_start_docstrings,
    add_start_docstrings_to_model_forward,
    is_scipy_available,
    is_vision_available,
    replace_return_docstrings,
)
from ....modeling_layers import GradientCheckpointingLayer
from ....modeling_utils import PreTrainedModel
from ....utils import is_accelerate_available, is_torchvision_available
from .configuration_deta import DetaConfig

"""PyTorch DETA model."""
logger = ...
MultiScaleDeformableAttention = ...

def load_cuda_kernels():  # -> None:
    ...

class MultiScaleDeformableAttentionFunction(Function):
    @staticmethod
    def forward(
        context,
        value,
        value_spatial_shapes,
        value_level_start_index,
        sampling_locations,
        attention_weights,
        im2col_step,
    ): ...
    @staticmethod
    @once_differentiable
    def backward(context, grad_output):  # -> tuple[Any, None, None, Any, Any, None]:
        ...

if is_accelerate_available(): ...
if is_vision_available(): ...
if is_torchvision_available(): ...
if is_scipy_available(): ...
logger = ...
_CONFIG_FOR_DOC = ...
_CHECKPOINT_FOR_DOC = ...

@dataclass
class DetaDecoderOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
class DetaModelOutput(ModelOutput):
    init_reference_points: torch.FloatTensor | None = ...
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    decoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    decoder_attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...
    encoder_last_hidden_state: torch.FloatTensor | None = ...
    encoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    encoder_attentions: tuple[torch.FloatTensor] | None = ...
    enc_outputs_class: torch.FloatTensor | None = ...
    enc_outputs_coord_logits: torch.FloatTensor | None = ...
    output_proposals: torch.FloatTensor | None = ...

@dataclass
class DetaObjectDetectionOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    loss_dict: dict | None = ...
    logits: torch.FloatTensor | None = ...
    pred_boxes: torch.FloatTensor | None = ...
    auxiliary_outputs: list[dict] | None = ...
    init_reference_points: torch.FloatTensor | None = ...
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    decoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    decoder_attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...
    encoder_last_hidden_state: torch.FloatTensor | None = ...
    encoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    encoder_attentions: tuple[torch.FloatTensor] | None = ...
    enc_outputs_class: Optional = ...
    enc_outputs_coord_logits: Optional = ...
    output_proposals: torch.FloatTensor | None = ...

def inverse_sigmoid(x, eps=...):  # -> Tensor:
    ...

class DetaFrozenBatchNorm2d(nn.Module):
    def __init__(self, n) -> None: ...
    def forward(self, x): ...

def replace_batch_norm(model):  # -> None:

    ...

class DetaBackboneWithPositionalEncodings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.Tensor, pixel_mask: torch.Tensor):  # -> tuple[list[Any], list[Any]]:

        ...

class DetaSinePositionEmbedding(nn.Module):
    def __init__(self, embedding_dim=..., temperature=..., normalize=..., scale=...) -> None: ...
    def forward(self, pixel_values, pixel_mask):  # -> Tensor:
        ...

class DetaLearnedPositionEmbedding(nn.Module):
    def __init__(self, embedding_dim=...) -> None: ...
    def forward(self, pixel_values, pixel_mask=...):  # -> Tensor:
        ...

def build_position_encoding(config):  # -> DetaSinePositionEmbedding | DetaLearnedPositionEmbedding:
    ...
def multi_scale_deformable_attention(
    value: Tensor, value_spatial_shapes: Tensor, sampling_locations: Tensor, attention_weights: Tensor
) -> Tensor: ...

class DetaMultiscaleDeformableAttention(nn.Module):
    def __init__(self, config: DetaConfig, num_heads: int, n_points: int) -> None: ...
    def with_pos_embed(self, tensor: torch.Tensor, position_embeddings: Tensor | None):  # -> Tensor:
        ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = ...,
        encoder_hidden_states=...,
        encoder_attention_mask=...,
        position_embeddings: torch.Tensor | None = ...,
        reference_points=...,
        spatial_shapes=...,
        level_start_index=...,
        output_attentions: bool = ...,
    ):  # -> tuple[Any, Tensor]:
        ...

class DetaMultiheadAttention(nn.Module):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = ..., bias: bool = ...) -> None: ...
    def with_pos_embed(self, tensor: torch.Tensor, position_embeddings: Tensor | None):  # -> Tensor:
        ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = ...,
        position_embeddings: torch.Tensor | None = ...,
        output_attentions: bool = ...,
    ) -> tuple[torch.Tensor, torch.Tensor | None, tuple[torch.Tensor] | None]: ...

class DetaEncoderLayer(nn.Module):
    def __init__(self, config: DetaConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        position_embeddings: torch.Tensor | None = ...,
        reference_points=...,
        spatial_shapes=...,
        level_start_index=...,
        output_attentions: bool = ...,
    ):  # -> tuple[Tensor, Any] | tuple[Tensor]:

        ...

class DetaDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: DetaConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: torch.Tensor | None = ...,
        reference_points=...,
        spatial_shapes=...,
        level_start_index=...,
        encoder_hidden_states: torch.Tensor | None = ...,
        encoder_attention_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
    ):  # -> tuple[Tensor, Any, Any] | tuple[Tensor]:

        ...

class DetaPreTrainedModel(PreTrainedModel):
    config: DetaConfig
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...
    supports_gradient_checkpointing = ...

DETA_START_DOCSTRING = ...
DETA_INPUTS_DOCSTRING = ...

class DetaEncoder(DetaPreTrainedModel):
    def __init__(self, config: DetaConfig) -> None: ...
    @staticmethod
    def get_reference_points(spatial_shapes, valid_ratios, device): ...
    def forward(
        self,
        inputs_embeds=...,
        attention_mask=...,
        position_embeddings=...,
        spatial_shapes=...,
        level_start_index=...,
        valid_ratios=...,
        output_attentions=...,
        output_hidden_states=...,
        return_dict=...,
    ):  # -> tuple[Tensor | Any | tuple[Tensor | Any, ...] | tuple[()] | tuple[Any, ...], ...] | BaseModelOutput:

        ...

class DetaDecoder(DetaPreTrainedModel):
    def __init__(self, config: DetaConfig) -> None: ...
    def forward(
        self,
        inputs_embeds=...,
        encoder_hidden_states=...,
        encoder_attention_mask=...,
        position_embeddings=...,
        reference_points=...,
        spatial_shapes=...,
        level_start_index=...,
        valid_ratios=...,
        output_attentions=...,
        output_hidden_states=...,
        return_dict=...,
    ):  # -> tuple[Any | Tensor | tuple[Any, ...] | tuple[()], ...] | DetaDecoderOutput:

        ...

@add_start_docstrings(
    ...,
    DETA_START_DOCSTRING,
)
class DetaModel(DetaPreTrainedModel):
    def __init__(self, config: DetaConfig) -> None: ...
    def get_encoder(self):  # -> DetaEncoder:
        ...
    def get_decoder(self):  # -> DetaDecoder:
        ...
    def freeze_backbone(self):  # -> None:
        ...
    def unfreeze_backbone(self):  # -> None:
        ...
    def get_valid_ratio(self, mask, dtype=...):  # -> Tensor:

        ...
    def get_proposal_pos_embed(self, proposals):  # -> Tensor:

        ...
    def gen_encoder_output_proposals(self, enc_output, padding_mask, spatial_shapes):  # -> tuple[Any, Tensor, Tensor]:

        ...
    @add_start_docstrings_to_model_forward(DETA_INPUTS_DOCSTRING)
    @replace_return_docstrings(output_type=DetaModelOutput, config_class=_CONFIG_FOR_DOC)
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        pixel_mask: torch.LongTensor | None = ...,
        decoder_attention_mask: torch.FloatTensor | None = ...,
        encoder_outputs: torch.FloatTensor | None = ...,
        inputs_embeds: torch.FloatTensor | None = ...,
        decoder_inputs_embeds: torch.FloatTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.FloatTensor] | DetaModelOutput: ...

@add_start_docstrings(
    ...,
    DETA_START_DOCSTRING,
)
class DetaForObjectDetection(DetaPreTrainedModel):
    _tied_weights_keys = ...
    _no_split_modules = ...
    def __init__(self, config: DetaConfig) -> None: ...
    @add_start_docstrings_to_model_forward(DETA_INPUTS_DOCSTRING)
    @replace_return_docstrings(output_type=DetaObjectDetectionOutput, config_class=_CONFIG_FOR_DOC)
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        pixel_mask: torch.LongTensor | None = ...,
        decoder_attention_mask: torch.FloatTensor | None = ...,
        encoder_outputs: torch.FloatTensor | None = ...,
        inputs_embeds: torch.FloatTensor | None = ...,
        decoder_inputs_embeds: torch.FloatTensor | None = ...,
        labels: list[dict] | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.FloatTensor] | DetaObjectDetectionOutput: ...

def dice_loss(inputs, targets, num_boxes): ...
def sigmoid_focal_loss(inputs, targets, num_boxes, alpha: float = ..., gamma: float = ...): ...

class DetaLoss(nn.Module):
    def __init__(
        self, matcher, num_classes, focal_alpha, losses, num_queries, assign_first_stage=..., assign_second_stage=...
    ) -> None: ...
    def loss_labels(self, outputs, targets, indices, num_boxes):  # -> dict[str, Any]:

        ...
    @torch.no_grad()
    def loss_cardinality(self, outputs, targets, indices, num_boxes):  # -> dict[str, Tensor]:

        ...
    def loss_boxes(self, outputs, targets, indices, num_boxes):  # -> dict[Any, Any]:

        ...
    def get_loss(
        self, loss, outputs, targets, indices, num_boxes
    ):  # -> dict[str, Tensor] | dict[str, Any] | dict[Any, Any]:
        ...
    def forward(self, outputs, targets):  # -> dict[Any, Any]:

        ...

class DetaMLPPredictionHead(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers) -> None: ...
    def forward(self, x):  # -> Tensor | Any:
        ...

class DetaHungarianMatcher(nn.Module):
    def __init__(self, class_cost: float = ..., bbox_cost: float = ..., giou_cost: float = ...) -> None: ...
    @torch.no_grad()
    def forward(self, outputs, targets):  # -> list[tuple[Tensor, Tensor]]:

        ...

def box_area(boxes: Tensor) -> Tensor: ...
def box_iou(boxes1, boxes2):  # -> tuple[Any, Any]:
    ...
def generalized_box_iou(boxes1, boxes2): ...
def nonzero_tuple(x): ...

class DetaMatcher:
    def __init__(self, thresholds: list[float], labels: list[int], allow_low_quality_matches: bool = ...) -> None: ...
    def __call__(self, match_quality_matrix):  # -> tuple[Any, Any]:

        ...
    def set_low_quality_matches_(self, match_labels, match_quality_matrix):  # -> None:

        ...

def subsample_labels(
    labels: torch.Tensor, num_samples: int, positive_fraction: float, bg_label: int
):  # -> tuple[Tensor, Tensor]:

    ...
def sample_topk_per_gt(pr_inds, gt_inds, iou, k):  # -> tuple[Any, Any] | tuple[Tensor, Tensor]:
    ...

class DetaStage2Assigner(nn.Module):
    def __init__(self, num_queries, max_k=...) -> None: ...
    def forward(self, outputs, targets, return_cost_matrix=...):  # -> tuple[list[Any], list[Any]] | list[Any]:
        ...
    def postprocess_indices(self, pr_inds, gt_inds, iou):  # -> tuple[Any, Any] | tuple[Tensor, Tensor]:
        ...

class DetaStage1Assigner(nn.Module):
    def __init__(self, t_low=..., t_high=..., max_k=...) -> None: ...
    def forward(self, outputs, targets):  # -> list[Any]:
        ...
    def postprocess_indices(self, pr_inds, gt_inds, iou):  # -> tuple[Any, Any] | tuple[Tensor, Tensor]:
        ...

__all__ = ["DetaForObjectDetection", "DetaModel", "DetaPreTrainedModel"]
