from collections.abc import Callable
from typing import TypeVar

from torch.fx import Graph
from torch.fx._compatibility import compatibility
from torch.fx.graph_module import GraphModule

T = TypeVar("T")
__all__ = ["GraphTransformObserver"]

@compatibility(is_backward_compatible=False)
class GraphTransformObserver:
    __pass_count = ...
    def __init__(
        self,
        gm: GraphModule,
        passname: str,
        subsystem: str | None = ...,
        log_url: str | None = ...,
    ) -> None: ...
    @classmethod
    def get_current_pass_count(cls) -> int: ...
    def apply_gm_pass(self, pass_fn: Callable[[GraphModule], T]) -> T | None: ...
    def apply_graph_pass(self, pass_fn: Callable[[Graph], T]) -> T | None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, type, value, tb) -> None: ...
    def get_node_creation_hook(self) -> Callable[..., None]: ...
    def get_node_erase_hook(self) -> Callable[..., None]: ...
    def get_node_replace_hook(self) -> Callable[..., None]: ...
    def get_deepcopy_hook(self) -> Callable[..., None]: ...
