from contextlib import contextmanager

from ....processing_utils import ProcessorMixin

"""
Speech processor class for M-CTC-T
"""

class MCTCTProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def batch_decode(self, *args, **kwargs): ...
    def pad(self, *args, **kwargs): ...
    def decode(self, *args, **kwargs): ...
    @contextmanager
    def as_target_processor(self):  # -> Generator[None, Any, None]:

        ...

__all__ = ["MCTCTProcessor"]
