import torch
from torch.types import Storage

__all__: list[str] = ...
if not hasattr(torch._C, "_gds_register_buffer"): ...

def gds_register_buffer(s: Storage) -> None: ...
def gds_deregister_buffer(s: Storage) -> None: ...

class GdsFile:
    def __init__(self, filename: str, flags: int) -> None: ...
    def __del__(self) -> None: ...
    def register_handle(self) -> None: ...
    def deregister_handle(self) -> None: ...
    def load_storage(self, storage: Storage, offset: int = ...) -> None: ...
    def save_storage(self, storage: Storage, offset: int = ...) -> None: ...
