from torch import Tensor

__all__: list[str] = ...

class _CodeParser:
    def __init__(self, code_string: str) -> None: ...

class _JittedFunction:
    def __init__(self, code_string: str, return_by_ref: bool, num_outputs: int, **kwargs) -> None: ...
    def __call__(self, *tensors: Tensor, **kwargs) -> Tensor: ...
