__all__ = [
    "enable",
    "get_filename",
    "get_max_tuning_duration",
    "get_max_tuning_iterations",
    "get_results",
    "get_rotating_buffer_size",
    "get_validators",
    "is_enabled",
    "mgpu_tune_gemm_in_file",
    "read_file",
    "record_untuned_enable",
    "record_untuned_is_enabled",
    "set_filename",
    "set_max_tuning_duration",
    "set_max_tuning_iterations",
    "set_rotating_buffer_size",
    "tune_gemm_in_file",
    "tuning_enable",
    "tuning_is_enabled",
    "write_file",
    "write_file_on_exit",
]

def enable(val: bool = ...) -> None: ...
def is_enabled() -> bool: ...
def tuning_enable(val: bool = ...) -> None: ...
def tuning_is_enabled() -> bool: ...
def record_untuned_enable(val: bool = ...) -> None: ...
def record_untuned_is_enabled() -> bool: ...
def set_max_tuning_duration(duration: int) -> None: ...
def get_max_tuning_duration() -> int: ...
def set_max_tuning_iterations(iterations: int) -> None: ...
def get_max_tuning_iterations() -> int: ...
def set_filename(filename: str, insert_device_ordinal: bool = ...) -> None: ...
def get_filename() -> str: ...
def get_results() -> tuple[str, str, str, float]: ...
def get_validators() -> tuple[str, str]: ...
def write_file_on_exit(val: bool) -> None: ...
def write_file(filename: str | None = ...) -> bool: ...
def read_file(filename: str | None = ...) -> bool: ...
def set_rotating_buffer_size(buffer_size: int) -> None: ...
def get_rotating_buffer_size() -> int: ...
def tune_gemm_in_file(filename: str) -> None: ...
def mgpu_tune_gemm_in_file(filename_pattern: str, num_gpus: int) -> None: ...
