import contextlib
import torch
from collections.abc import Callable
from warnings import deprecated
from torch._library.utils import RegistrationHandle

class FakeImplHolder:
    def __init__(self, qualname: str) -> None: ...
    @property
    def kernel(self):  # -> Kernel | None:
        ...
    @kernel.setter
    def kernel(self, value): ...
    def register(self, func: Callable, source: str, lib, *, allow_override=...) -> RegistrationHandle: ...

def construct_meta_kernel(qualname: str, fake_impl_holder: FakeImplHolder) -> Callable: ...
def get_none():  # -> None:
    ...

global_ctx_getter: Callable = ...

@contextlib.contextmanager
def set_ctx_getter(ctx_getter):  # -> Generator[None, Any, None]:
    ...

class FakeImplCtx:
    def __init__(self, _fake_mode, _op) -> None: ...
    @deprecated("`create_unbacked_symint` is deprecated, please use `new_dynamic_size` instead", category=FutureWarning)
    def create_unbacked_symint(self, *, min=..., max=...) -> torch.SymInt: ...
    def new_dynamic_size(self, *, min=..., max=...) -> torch.SymInt: ...

def allocate_size(shape_env, min_val=..., max_val=...): ...
