from collections.abc import Callable
from typing import Optional

from .utils import RegistrationHandle

__all__ = ["SimpleLibraryRegistry", "SimpleOperatorEntry", "singleton"]

class SimpleLibraryRegistry:
    def __init__(self) -> None: ...
    def find(self, qualname: str) -> SimpleOperatorEntry: ...

singleton: SimpleLibraryRegistry = ...

class SimpleOperatorEntry:
    def __init__(self, qualname: str) -> None: ...
    @property
    def abstract_impl(self):  # -> FakeImplHolder:
        ...

class GenericTorchDispatchRuleHolder:
    def __init__(self, qualname) -> None: ...
    def register(self, torch_dispatch_class: type, func: Callable) -> RegistrationHandle: ...
    def find(self, torch_dispatch_class):  # -> None:
        ...

def find_torch_dispatch_rule(op, torch_dispatch_class: type) -> Callable | None: ...
