from abc import ABC, abstractmethod
from typing import Optional

class Constraint(ABC):
    def __init__(self) -> None: ...
    def test(self):  # -> None:

        ...
    @abstractmethod
    def advance(self): ...
    @abstractmethod
    def does_advance(self, token_id: int): ...
    @abstractmethod
    def update(self, token_id: int): ...
    @abstractmethod
    def reset(self): ...
    @abstractmethod
    def remaining(self): ...
    @abstractmethod
    def copy(self, stateful=...): ...

class PhrasalConstraint(Constraint):
    def __init__(self, token_ids: list[int]) -> None: ...
    def advance(self):  # -> int | None:
        ...
    def does_advance(self, token_id: int):  # -> bool:
        ...
    def update(self, token_id: int):  # -> tuple[bool, bool, bool]:
        ...
    def reset(self):  # -> None:
        ...
    def remaining(self):  # -> int:
        ...
    def copy(self, stateful=...):  # -> PhrasalConstraint:
        ...

class DisjunctiveTrie:
    def __init__(self, nested_token_ids: list[list[int]], no_subsets=...) -> None: ...
    def next_tokens(self, current_seq):  # -> list[Any]:

        ...
    def reached_leaf(self, current_seq):  # -> bool:
        ...
    def count_leaves(self, root):  # -> int:
        ...
    def has_subsets(self, trie, nested_token_ids):  # -> bool:

        ...

class DisjunctiveConstraint(Constraint):
    def __init__(self, nested_token_ids: list[list[int]]) -> None: ...
    def advance(self):  # -> list[Any] | None:
        ...
    def does_advance(self, token_id: int):  # -> bool:
        ...
    def update(self, token_id: int):  # -> tuple[bool, bool, bool]:
        ...
    def reset(self):  # -> None:
        ...
    def remaining(self):  # -> int:
        ...
    def copy(self, stateful=...):  # -> DisjunctiveConstraint:
        ...

class ConstraintListState:
    def __init__(self, constraints: list[Constraint]) -> None: ...
    def init_state(self):  # -> None:
        ...
    def get_bank(self): ...
    def advance(self):  # -> list[Any] | None:

        ...
    def reset(self, token_ids: Optional[list[int]]):  # -> None:

        ...
    def add(
        self, token_id: int
    ):  # -> tuple[Literal[True], Literal[False]] | tuple[Any | Literal[False], Any | Literal[False]]:
        ...
    def copy(self, stateful=...):  # -> ConstraintListState:
        ...
