import numpy as np
import torch
from dataclasses import dataclass
from typing import Any, Optional, Union
from torch import nn
from ..modeling_utils import PreTrainedModel
from ..utils import ModelOutput, is_torch_available
from .configuration_utils import PretrainedConfig, WatermarkingConfig
from .logits_process import SynthIDTextWatermarkLogitsProcessor

if is_torch_available(): ...
logger = ...

@dataclass
class WatermarkDetectorOutput:
    num_tokens_scored: Optional[np.array] = ...
    num_green_tokens: Optional[np.array] = ...
    green_fraction: Optional[np.array] = ...
    z_score: Optional[np.array] = ...
    p_value: Optional[np.array] = ...
    prediction: Optional[np.array] = ...
    confidence: Optional[np.array] = ...

class WatermarkDetector:
    def __init__(
        self,
        model_config: PretrainedConfig,
        device: str,
        watermarking_config: Union[WatermarkingConfig, dict],
        ignore_repeated_ngrams: bool = ...,
        max_cache_size: int = ...,
    ) -> None: ...
    def __call__(
        self, input_ids: torch.LongTensor, z_threshold: float = ..., return_dict: bool = ...
    ) -> Union[WatermarkDetectorOutput, np.array]: ...

class BayesianDetectorConfig(PretrainedConfig):
    def __init__(self, watermarking_depth: Optional[int] = ..., base_rate: float = ..., **kwargs) -> None: ...
    def set_detector_information(self, model_name, watermarking_config):  # -> None:
        ...

@dataclass
class BayesianWatermarkDetectorModelOutput(ModelOutput):
    loss: Optional[torch.FloatTensor] = ...
    posterior_probabilities: Optional[torch.FloatTensor] = ...

class BayesianDetectorWatermarkedLikelihood(nn.Module):
    def __init__(self, watermarking_depth: int) -> None: ...
    def forward(self, g_values: torch.Tensor) -> torch.Tensor: ...

class BayesianDetectorModel(PreTrainedModel):
    config: BayesianDetectorConfig
    base_model_prefix = ...
    def __init__(self, config) -> None: ...
    def forward(
        self,
        g_values: torch.Tensor,
        mask: torch.Tensor,
        labels: Optional[torch.Tensor] = ...,
        loss_batch_weight=...,
        return_dict=...,
    ) -> BayesianWatermarkDetectorModelOutput: ...

class SynthIDTextWatermarkDetector:
    def __init__(
        self,
        detector_module: BayesianDetectorModel,
        logits_processor: SynthIDTextWatermarkLogitsProcessor,
        tokenizer: Any,
    ) -> None: ...
    def __call__(self, tokenized_outputs: torch.Tensor):  # -> Any:
        ...
