__all__ = ["BaseScheduler"]

class BaseScheduler:
    def __init__(self, sparsifier, last_epoch=..., verbose=...) -> None: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state_dict) -> None: ...
    def get_last_sl(self) -> list[Any]: ...
    def get_sl(self): ...
    def print_sl(self, is_verbose, group, sl, epoch=...) -> None: ...
    def step(self, epoch=...): ...
