import types

class _XNNPACKEnabled:
    def __get__(self, obj, objtype) -> bool: ...
    def __set__(self, obj, val) -> None: ...

class XNNPACKEngine(types.ModuleType):
    def __init__(self, m, name) -> None: ...
    def __getattr__(self, attr): ...

    enabled = ...
