from collections.abc import Callable
from dataclasses import dataclass

from torch._ops import HigherOrderOperator

def is_graphable(val) -> bool: ...
def is_graphable_type(typ) -> bool: ...
def to_graphable(stuff): ...
def from_graphable(flat_args, spec): ...
def func_to_graphable(func): ...

@dataclass(frozen=True)
class _ConstantFunction:
    func: Callable
    def __call__(self, *args, **kwargs): ...

_op_types = ...

class FlatApply(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, func, in_spec, *flat_args, **_unused): ...

def impl(func, in_spec, *flat_args): ...

flat_apply = ...
