from dataclasses import dataclass
from typing import Callable
from torch._ops import HigherOrderOperator

def is_graphable(val) -> bool: ...
def is_graphable_type(typ) -> bool: ...
def to_graphable(stuff):  # -> tuple[list[Any], TreeSpec]:

    ...
def from_graphable(flat_args, spec):  # -> PyTree:

    ...
def func_to_graphable(func):  # -> tuple[list[Any], TreeSpec]:

    ...

@dataclass(frozen=True)
class _ConstantFunction:
    func: Callable
    def __call__(self, *args, **kwargs): ...

_op_types = ...

class FlatApply(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, func, in_spec, *flat_args, **_unused): ...

def impl(func, in_spec, *flat_args): ...

flat_apply = ...
