from torch._C import DispatchKey
from torch._ops import HigherOrderOperator
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode

class HintsWrapper(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, body_fn, args, kwargs, hints):  # -> Any | None:

        ...

hints_wrapper = ...

@hints_wrapper.py_impl(DispatchKey.CompositeExplicitAutograd)
def hints_wrapper_dense(body_fn, args, kwargs, hints): ...
@hints_wrapper.py_impl(FakeTensorMode)
def hints_wrapper_fake_tensor_mode(mode, body_func, args, kwargs, hints): ...
@hints_wrapper.py_functionalize_impl
def hints_wrapper_functionalize(ctx, body_fn, args, kwargs, hints): ...
def trace_hints_wrapper(proxy_mode, hints_wrapper, body_fn, args, kwargs, hints): ...
@hints_wrapper.py_impl(ProxyTorchDispatchMode)
def inner(proxy_mode, body_fn, args, kwargs, hints):  # -> Any | None:
    ...
