from torch._C import DispatchKey
from torch._functorch.utils import exposed_in
from torch._ops import HigherOrderOperator
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode

@exposed_in("torch")
def strict_mode(callable, operands):  # -> Any | None:
    ...

class StrictMode(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, callable, operands):  # -> Any | None:
        ...

strict_mode_op = ...

@strict_mode_op.py_impl(DispatchKey.CompositeExplicitAutograd)
def strict_mode_op_dense(callable, operands): ...
@strict_mode_op.py_impl(ProxyTorchDispatchMode)
def inner(mode, callable, operands):  # -> Any:
    ...
def trace_strict_mode(mode, strict_mode_op, callable, operands):  # -> Any:
    ...
@strict_mode_op.py_impl(FakeTensorMode)
def strict_mode_fake_tensor_mode(mode, callable, operands): ...
@strict_mode_op.py_functionalize_impl
def strict_mode_func(ctx, callable, inputs): ...
