from dataclasses import dataclass
from typing import Any, NamedTuple, Optional

import torch
from torch.distributed.device_mesh import DeviceMesh
from torch.distributed.tensor.placement_types import Placement

class TensorMeta(NamedTuple):
    shape: torch.Size
    stride: tuple[int, ...]
    dtype: torch.dtype

@dataclass
class DTensorSpec:
    mesh: DeviceMesh
    placements: tuple[Placement, ...]
    tensor_meta: TensorMeta | None = ...
    def __post_init__(self) -> None: ...
    def __setattr__(self, attr: str, value: Any) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    @property
    def shape(self) -> torch.Size: ...
    @property
    def stride(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def num_shards(self) -> int: ...
    @property
    def device_mesh(self) -> DeviceMesh: ...
    @property
    def dim_map(self) -> list[int]: ...
    @property
    def num_shards_map(self) -> list[int]: ...
    @property
    def sums(self) -> list[int]: ...
    @classmethod
    def from_dim_map(
        cls, mesh: DeviceMesh, dim_map: list[int], sums: list[int], tensor_meta: TensorMeta | None = ...
    ) -> DTensorSpec: ...
    def is_replicated(self) -> bool: ...
    def is_sharded(self) -> bool: ...
    def shallow_copy_with_tensor_meta(self, tensor_meta: TensorMeta | None) -> DTensorSpec: ...
