from dataclasses import dataclass

__all__ = ["Partial", "Placement", "Replicate", "Shard"]

class Placement:
    def is_shard(self, dim: int | None = ...) -> bool: ...
    def is_replicate(self) -> bool: ...
    def is_partial(self, reduce_op: str | None = ...) -> bool: ...

@dataclass(frozen=True)
class Shard(Placement):
    dim: int
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

kw_only_dataclass = ...

@dataclass(frozen=True, **kw_only_dataclass)
class _StridedShard(Shard):
    split_factor: int
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class Replicate(Placement):
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class Partial(Placement):
    reduce_op: str = ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

_Partial = Partial
