"""
This type stub file was generated by pyright.
"""

import numpy as np
from collections.abc import Iterable
from typing import Optional, Union
from ...image_processing_utils import BaseImageProcessor
from ...image_utils import ChannelDimension, ImageInput, PILImageResampling
from ...utils import TensorType, is_vision_available

if is_vision_available(): ...
logger = ...

def make_batched_images(images) -> list[list[ImageInput]]: ...
def smart_resize(height: int, width: int, factor: int = ..., min_pixels: int = ..., max_pixels: int = ...): ...

class Emu3ImageProcessor(BaseImageProcessor):
    model_input_names = ...
    def __init__(
        self,
        do_resize: bool = ...,
        resample: PILImageResampling = ...,
        do_rescale: bool = ...,
        rescale_factor: float = ...,
        do_normalize: bool = ...,
        image_mean: Optional[Union[float, list[float]]] = ...,
        image_std: Optional[Union[float, list[float]]] = ...,
        do_convert_rgb: bool = ...,
        do_pad: bool = ...,
        min_pixels: int = ...,
        max_pixels: int = ...,
        spatial_factor: int = ...,
        **kwargs,
    ) -> None: ...
    def preprocess(
        self,
        images: ImageInput,
        do_resize: Optional[bool] = ...,
        size: Optional[dict[str, int]] = ...,
        resample: PILImageResampling = ...,
        do_rescale: Optional[bool] = ...,
        rescale_factor: Optional[float] = ...,
        do_normalize: Optional[bool] = ...,
        image_mean: Optional[Union[float, list[float]]] = ...,
        image_std: Optional[Union[float, list[float]]] = ...,
        do_convert_rgb: Optional[bool] = ...,
        do_pad: bool = ...,
        return_tensors: Optional[Union[str, TensorType]] = ...,
        data_format: Optional[ChannelDimension] = ...,
        input_data_format: Optional[Union[str, ChannelDimension]] = ...,
    ): ...
    def postprocess(
        self,
        images: ImageInput,
        do_rescale: Optional[bool] = ...,
        rescale_factor: Optional[float] = ...,
        do_normalize: Optional[bool] = ...,
        image_mean: Optional[Union[float, list[float]]] = ...,
        image_std: Optional[Union[float, list[float]]] = ...,
        return_tensors: Union[str, TensorType] = ...,
        input_data_format: Optional[Union[str, ChannelDimension]] = ...,
    ): ...
    def unnormalize(
        self,
        image: np.array,
        image_mean: Union[float, Iterable[float]],
        image_std: Union[float, Iterable[float]],
        input_data_format: Optional[Union[str, ChannelDimension]] = ...,
    ) -> np.array: ...

__all__ = ["Emu3ImageProcessor"]
