from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for CANINE."""
logger = ...
UNICODE_VOCAB_SIZE = ...
PAD = ...
CLS = ...
SEP = ...
BOS = ...
MASK = ...
RESERVED = ...
SPECIAL_CODEPOINTS: dict[int, str] = ...
SPECIAL_CODEPOINTS_BY_NAME: dict[str, int] = ...

class CanineTokenizer(PreTrainedTokenizer):
    def __init__(
        self,
        bos_token=...,
        eos_token=...,
        sep_token=...,
        cls_token=...,
        pad_token=...,
        mask_token=...,
        add_prefix_space=...,
        model_max_length=...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self) -> int: ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def convert_tokens_to_string(self, tokens):  # -> str:
        ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...):  # -> tuple[()]:
        ...

__all__ = ["CanineTokenizer"]
