from typing import Any, TypeAlias
from torch.types import Device

_device_t: TypeAlias = Device | str | int | None

def empty_cache() -> None: ...
def reset_peak_memory_stats(device: _device_t = ...) -> None: ...
def reset_accumulated_memory_stats(device: _device_t = ...) -> None: ...
def memory_stats_as_nested_dict(device: _device_t = ...) -> dict[str, Any]: ...
def memory_stats(device: _device_t = ...) -> dict[str, Any]: ...
def memory_allocated(device: _device_t = ...) -> int: ...
def max_memory_allocated(device: _device_t = ...) -> int: ...
def memory_reserved(device: _device_t = ...) -> int: ...
def max_memory_reserved(device: _device_t = ...) -> int: ...
def mem_get_info(device: _device_t = ...) -> tuple[int, int]: ...

__all__ = [
    "empty_cache",
    "max_memory_allocated",
    "max_memory_reserved",
    "mem_get_info",
    "memory_allocated",
    "memory_reserved",
    "memory_stats",
    "memory_stats_as_nested_dict",
    "reset_accumulated_memory_stats",
    "reset_peak_memory_stats",
]
