import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import is_torchvision_v2_available

if is_torchvision_v2_available(): ...

class LlavaOnevisionFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    image_grid_pinpoints: list[list[int]] | None
    do_pad: bool | None

class LlavaOnevisionImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_pad = ...
    image_grid_pinpoints = ...
    valid_kwargs = LlavaOnevisionFastImageProcessorKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[LlavaOnevisionFastImageProcessorKwargs]) -> None: ...
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[LlavaOnevisionFastImageProcessorKwargs]
    ) -> BatchFeature: ...
    def pad_to_square(
        self, images: torch.Tensor, background_color: int | tuple[int, int, int] = ...
    ) -> torch.Tensor: ...

__all__ = ["LlavaOnevisionImageProcessorFast"]
