from typing import Any

import torch.nn
from torch.nn import Module

from .utils import ExactWeakKeyDictionary

"""Mutation tracking and dynamic module detection system for Dynamo.

This module provides mechanisms to track and respond to mutations in PyTorch modules
and detect dynamically created or modified modules.

Key components:
- MutationTracker: Tracks mutations to objects and invalidates associated cached code
- GenerationTracker: Tracks module creation timing to identify dynamic instances
- Patching system for nn.Module to detect mutations and dynamic creation

The system ensures that Dynamo's optimizations remain valid by detecting and responding
to runtime changes in module state and structure.
"""
unpatched_nn_module_init = ...

class MutationTracker:
    db: ExactWeakKeyDictionary = ...
    def __init__(self) -> None: ...
    def on_mutation(self, name: str) -> None: ...
    def track(self, guarded_code: Any) -> None: ...

def watch(obj: Any, guarded_code: Any) -> None: ...
def ensure_patched(cls: Any) -> None: ...

class GenerationTracker:
    generation: int = ...
    dynamic_classes: ExactWeakKeyDictionary = ...
    generation_values: ExactWeakKeyDictionary = ...
    @classmethod
    def tag(cls, obj: Any) -> None: ...
    @staticmethod
    def mark_class_dynamic(cls: type[torch.nn.Module]) -> None: ...
    @classmethod
    def get_generation_value(cls, obj: Any) -> int: ...
    @classmethod
    def check(cls, obj: Any) -> bool: ...
    @classmethod
    def clear(cls) -> None: ...

def is_dynamic_nn_module(obj: Any, is_export: bool) -> bool: ...
def install_generation_tagging_init() -> None: ...
