import torch

__all__ = ["model_is_exported"]
_EXPORTED_TRAINING_ATTR = ...

class _WrapperModule(torch.nn.Module):
    def __init__(self, fn) -> None: ...
    def forward(self, *args, **kwargs): ...

def model_is_exported(m: torch.nn.Module) -> bool: ...
