import logging
import os
import sys

import torchaudio.lib._torchaudio
from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op

from .utils import _check_cuda_version, _init_dll_path, _init_sox, _LazyImporter, _load_lib

_LG = ...
__all__ = ["_IS_RIR_AVAILABLE", "_IS_TORCHAUDIO_EXT_AVAILABLE", "_check_cuda_version", "lazy_import_sox_ext"]
if os.name == "nt" and (3, 8) <= sys.version_info < (3, 9): ...
_IS_TORCHAUDIO_EXT_AVAILABLE = ...
_IS_RIR_AVAILABLE = ...
_IS_ALIGN_AVAILABLE = ...
if _IS_TORCHAUDIO_EXT_AVAILABLE:
    _IS_RIR_AVAILABLE = ...
    _IS_ALIGN_AVAILABLE = ...
_SOX_EXT = ...

def lazy_import_sox_ext():  # -> _LazyImporter:
    ...

fail_if_no_rir = ...
fail_if_no_align = ...
