from collections.abc import Callable
from typing import Any

from .observer import _PartialWrapper
from .qconfig import QConfigAny

__all__ = [
    "QConfigMapping",
    "get_default_qat_qconfig_mapping",
    "get_default_qconfig_mapping",
]
_GLOBAL_DICT_KEY = ...
_OBJECT_TYPE_DICT_KEY = ...
_MODULE_NAME_REGEX_DICT_KEY = ...
_MODULE_NAME_DICT_KEY = ...
_MODULE_NAME_OBJECT_TYPE_ORDER_DICT_KEY = ...
_FIXED_QPARAMS_OP_TO_OBSERVER: dict[Callable | str, _PartialWrapper] = ...

def get_default_qconfig_mapping(backend=..., version=...) -> QConfigMapping: ...
def get_default_qat_qconfig_mapping(backend=..., version=...) -> QConfigMapping: ...

_QCONFIG_STYLE_ORDER: list[str] = ...

class QConfigMapping:
    def __init__(self) -> None: ...
    def set_global(self, global_qconfig: QConfigAny) -> QConfigMapping: ...
    def set_object_type(self, object_type: Callable | str, qconfig: QConfigAny) -> QConfigMapping: ...
    def set_module_name_regex(self, module_name_regex: str, qconfig: QConfigAny) -> QConfigMapping: ...
    def set_module_name(self, module_name: str, qconfig: QConfigAny) -> QConfigMapping: ...
    def set_module_name_object_type_order(
        self,
        module_name: str,
        object_type: Callable,
        index: int,
        qconfig: QConfigAny,
    ) -> QConfigMapping: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, qconfig_dict: dict[str, Any]) -> QConfigMapping: ...
