from collections import namedtuple
from warnings import deprecated
from torch.ao.quantization.fake_quantize import FakeQuantizeBase
from .observer import ObserverBase, _PartialWrapper
from typing import TypeAlias

__all__ = [
    "QConfig",
    "QConfigAny",
    "QConfigDynamic",
    "default_activation_only_qconfig",
    "default_debug_qconfig",
    "default_dynamic_qat_qconfig",
    "default_dynamic_qconfig",
    "default_embedding_qat_qconfig",
    "default_embedding_qat_qconfig_4bit",
    "default_per_channel_qconfig",
    "default_per_channel_symmetric_qnnpack_qat_qconfig",
    "default_per_channel_symmetric_qnnpack_qconfig",
    "default_qat_qconfig",
    "default_qat_qconfig_v2",
    "default_qconfig",
    "default_quint8_weight_qconfig",
    "default_reuse_input_qconfig",
    "default_symmetric_qnnpack_qat_qconfig",
    "default_symmetric_qnnpack_qconfig",
    "default_weight_only_qconfig",
    "float16_dynamic_qconfig",
    "float16_static_qconfig",
    "float_qparams_weight_only_qconfig",
    "float_qparams_weight_only_qconfig_4bit",
    "get_default_qat_qconfig",
    "get_default_qat_qconfig_dict",
    "get_default_qconfig",
    "get_default_qconfig_dict",
    "per_channel_dynamic_qconfig",
    "qconfig_equals",
]

class QConfig(namedtuple("QConfig", ["activation", "weight"])):
    __slots__ = ...
    def __new__(cls, activation, weight) -> Self: ...

@deprecated(
    "`QConfigDynamic` is going to be deprecated in PyTorch 1.12, please use `QConfig` instead", category=FutureWarning
)
class QConfigDynamic(namedtuple("QConfigDynamic", ["activation", "weight"])):
    __slots__ = ...
    def __new__(cls, activation=..., weight=...) -> Self: ...

default_qconfig = ...
default_debug_qconfig = ...
default_per_channel_qconfig = ...
default_dynamic_qconfig = ...
float16_dynamic_qconfig = ...
float16_static_qconfig = ...
per_channel_dynamic_qconfig = ...
float_qparams_weight_only_qconfig = ...
float_qparams_weight_only_qconfig_4bit = ...
default_qat_qconfig = ...
default_dynamic_qat_qconfig = ...
default_weight_only_qconfig = ...
default_activation_only_qconfig = ...
default_qat_qconfig_v2 = ...
default_reuse_input_qconfig = ...

def get_default_qconfig(backend=..., version=...) -> QConfig: ...

default_symmetric_qnnpack_qconfig = ...
default_per_channel_symmetric_qnnpack_qconfig = ...
default_embedding_qat_qconfig = ...
default_embedding_qat_qconfig_4bit = ...
default_quint8_weight_qconfig = ...

def get_default_qat_qconfig(backend=..., version=...) -> QConfig: ...

default_symmetric_qnnpack_qat_qconfig = ...
default_per_channel_symmetric_qnnpack_qat_qconfig = ...
_default_fp32_placeholder_qconfig = ...
_default_quint8_placeholder_qconfig = ...

@deprecated(
    "`torch.ao.quantization.get_default_qconfig_dict` is deprecated and will be removed in a future version. Please use `torch.ao.quantization.get_default_qconfig_mapping` instead.",
    category=FutureWarning,
)
def get_default_qconfig_dict(backend=..., version=...) -> dict[str, Any]: ...
@deprecated(
    "`torch.ao.quantization.get_default_qat_qconfig_dict` is deprecated and will be removed in a future version. Please use `torch.ao.quantization.get_default_qat_qconfig_mapping` instead.",
    category=FutureWarning,
)
def get_default_qat_qconfig_dict(backend=..., version=...) -> dict[str, Any]: ...

QConfigAny: TypeAlias = QConfig | None
_ObserverOrFakeQuantizeConstructor: TypeAlias = type[ObserverBase | FakeQuantizeBase] | _PartialWrapper

def qconfig_equals(q1: QConfigAny, q2: QConfigAny) -> bool: ...
