__all__ = [
    "convert_dynamic_jit",
    "convert_jit",
    "fuse_conv_bn_jit",
    "prepare_dynamic_jit",
    "prepare_jit",
    "quantize_dynamic_jit",
    "quantize_jit",
    "script_qconfig",
    "script_qconfig_dict",
]

def script_qconfig(qconfig) -> QConfig: ...
def script_qconfig_dict(qconfig_dict) -> dict[Any, QConfig | None]: ...
def fuse_conv_bn_jit(model, inplace=...): ...
def prepare_jit(model, qconfig_dict, inplace=...): ...
def prepare_dynamic_jit(model, qconfig_dict, inplace=...): ...
def convert_jit(model, inplace=..., debug=..., preserved_attrs=...): ...
def convert_dynamic_jit(model, inplace=..., debug=..., preserved_attrs=...): ...
def quantize_jit(model, qconfig_dict, run_fn, run_args, inplace=..., debug=...): ...
def quantize_dynamic_jit(model, qconfig_dict, inplace=..., debug=...): ...
