import functools

aten = ...
prims = ...

def mark_mixed_dtype(computation_node):  # -> None:
    ...
def mark_mixed_dtype_allowed_computation_ops(gm):  # -> None:

    ...
def recover_original_precision_folded_computation_ops(gm):  # -> None:

    ...

_binary_ops = ...

@functools.cache
def binary_folding_init():  # -> None:
    ...
