import logging
from collections.abc import Callable

import torch

logger: logging.Logger = ...

def is_graph_input(node: torch.fx.Node) -> bool: ...
def is_fsdp_all_gather_wait(wait: torch.fx.Node) -> bool: ...
def is_graph_output(node: torch.fx.Node) -> bool: ...
def is_fsdp_reduce_scatter_wait(wait: torch.fx.Node) -> bool: ...
def bucket_fsdp_all_gather(
    gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float] | None = ..., mode: str | None = ...
) -> None: ...
def bucket_fsdp_reduce_scatter(
    gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float] | None = ..., mode: str | None = ...
) -> None: ...
