log = ...
aten = ...
_scaled_dot_product_attention = ...

def partialize_and_update_signature(func, **kwargs):
    """Equivalent to functools.partial but also updates the signature on returned function"""
