import os
from typing import Literal

from torch import Tensor

@staticmethod
def deserialize(bytes): ...
@staticmethod
def serialize(tensor_dict, metadata=...): ...
@staticmethod
def serialize_file(tensor_dict, filename, metadata=...): ...

class safe_open:
    def __init__(
        self, filename: str | os.PathLike[str], framework: Literal["pt", "tf", "flax", "numpy"], device: str
    ) -> None: ...
    def __enter__(self): ...
    def __exit__(self, _exc_type, _exc_value, _traceback): ...
    def get_slice(self, name: str): ...
    def get_tensor(self, name: str) -> Tensor: ...
    def keys(self): ...
    def metadata(self): ...
    def offset_keys(self): ...

class SafetensorError(Exception): ...
