import os

from jax import Array

def save(tensors: dict[str, Array], metadata: dict[str, str] | None = ...) -> bytes: ...
def save_file(
    tensors: dict[str, Array], filename: str | os.PathLike, metadata: dict[str, str] | None = ...
) -> None: ...
def load(data: bytes) -> dict[str, Array]: ...
def load_file(filename: str | os.PathLike) -> dict[str, Array]: ...
