from dataclasses import dataclass

import torch
from torch import Tensor, nn

from ...modeling_utils import PreTrainedModel
from ...pytorch_utils import compile_compatible_method_lru_cache
from ...utils import ModelOutput
from .configuration_rt_detr_v2 import RTDetrV2Config

def multi_scale_deformable_attention_v2(
    value: Tensor,
    value_spatial_shapes: Tensor,
    sampling_locations: Tensor,
    attention_weights: Tensor,
    num_points_list: list[int],
    method=...,
) -> Tensor: ...

class RTDetrV2MultiscaleDeformableAttention(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = ...,
        encoder_hidden_states=...,
        encoder_attention_mask=...,
        position_embeddings: torch.Tensor | None = ...,
        reference_points=...,
        spatial_shapes=...,
        spatial_shapes_list=...,
        level_start_index=...,
        output_attentions: bool = ...,
    ):  # -> tuple[Any, Tensor]:
        ...

class RTDetrV2MultiheadAttention(nn.Module):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = ..., bias: bool = ...) -> None: ...
    def with_pos_embed(self, tensor: torch.Tensor, position_embeddings: Tensor | None):  # -> Tensor:
        ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = ...,
        position_embeddings: torch.Tensor | None = ...,
        output_attentions: bool = ...,
    ) -> tuple[torch.Tensor, torch.Tensor | None, tuple[torch.Tensor] | None]: ...

class RTDetrV2DecoderLayer(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: torch.Tensor | None = ...,
        reference_points=...,
        spatial_shapes=...,
        spatial_shapes_list=...,
        level_start_index=...,
        encoder_hidden_states: torch.Tensor | None = ...,
        encoder_attention_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
    ):  # -> tuple[Tensor, Any, Any] | tuple[Tensor]:

        ...

@dataclass
class RTDetrV2DecoderOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_logits: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    intermediate_predicted_corners: torch.FloatTensor | None = ...
    initial_reference_points: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
class RTDetrV2ModelOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_logits: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    intermediate_predicted_corners: torch.FloatTensor | None = ...
    initial_reference_points: torch.FloatTensor | None = ...
    decoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    decoder_attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...
    encoder_last_hidden_state: torch.FloatTensor | None = ...
    encoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    encoder_attentions: tuple[torch.FloatTensor] | None = ...
    init_reference_points: torch.FloatTensor | None = ...
    enc_topk_logits: torch.FloatTensor | None = ...
    enc_topk_bboxes: torch.FloatTensor | None = ...
    enc_outputs_class: torch.FloatTensor | None = ...
    enc_outputs_coord_logits: torch.FloatTensor | None = ...
    denoising_meta_values: dict | None = ...

@dataclass
class RTDetrV2ObjectDetectionOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    loss_dict: dict | None = ...
    logits: torch.FloatTensor | None = ...
    pred_boxes: torch.FloatTensor | None = ...
    auxiliary_outputs: list[dict] | None = ...
    last_hidden_state: torch.FloatTensor | None = ...
    intermediate_hidden_states: torch.FloatTensor | None = ...
    intermediate_logits: torch.FloatTensor | None = ...
    intermediate_reference_points: torch.FloatTensor | None = ...
    intermediate_predicted_corners: torch.FloatTensor | None = ...
    initial_reference_points: torch.FloatTensor | None = ...
    decoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    decoder_attentions: tuple[torch.FloatTensor] | None = ...
    cross_attentions: tuple[torch.FloatTensor] | None = ...
    encoder_last_hidden_state: torch.FloatTensor | None = ...
    encoder_hidden_states: tuple[torch.FloatTensor] | None = ...
    encoder_attentions: tuple[torch.FloatTensor] | None = ...
    init_reference_points: tuple[torch.FloatTensor] | None = ...
    enc_topk_logits: torch.FloatTensor | None = ...
    enc_topk_bboxes: torch.FloatTensor | None = ...
    enc_outputs_class: torch.FloatTensor | None = ...
    enc_outputs_coord_logits: torch.FloatTensor | None = ...
    denoising_meta_values: dict | None = ...

class RTDetrV2FrozenBatchNorm2d(nn.Module):
    def __init__(self, n) -> None: ...
    def forward(self, x): ...

def replace_batch_norm(model):  # -> None:

    ...

class RTDetrV2ConvEncoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.Tensor, pixel_mask: torch.Tensor):  # -> list[Any]:
        ...

class RTDetrV2ConvNormLayer(nn.Module):
    def __init__(self, config, in_channels, out_channels, kernel_size, stride, padding=..., activation=...) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class RTDetrV2EncoderLayer(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        position_embeddings: torch.Tensor | None = ...,
        output_attentions: bool = ...,
        **kwargs,
    ):  # -> tuple[Tensor, Any] | tuple[Tensor]:

        ...

class RTDetrV2RepVggBlock(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(self, x):  # -> Any:
        ...

class RTDetrV2CSPRepLayer(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class RTDetrV2Encoder(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(self, src, src_mask=..., pos_embed=..., output_attentions: bool = ...) -> torch.Tensor: ...

class RTDetrV2HybridEncoder(nn.Module):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    @staticmethod
    def build_2d_sincos_position_embedding(
        width, height, embed_dim=..., temperature=..., device=..., dtype=...
    ):  # -> Tensor:
        ...
    def forward(
        self,
        inputs_embeds=...,
        attention_mask=...,
        position_embeddings=...,
        spatial_shapes=...,
        level_start_index=...,
        valid_ratios=...,
        output_attentions=...,
        output_hidden_states=...,
        return_dict=...,
    ):  # -> tuple[list[Any] | tuple[Any, ...] | Any | tuple[()], ...] | BaseModelOutput:

        ...

def inverse_sigmoid(x, eps=...):  # -> Tensor:
    ...
def get_contrastive_denoising_training_group(
    targets,
    num_classes,
    num_queries,
    class_embed,
    num_denoising_queries=...,
    label_noise_ratio=...,
    box_noise_scale=...,
):  # -> tuple[None, None, None, None] | tuple[Any, Tensor, Tensor, dict[str, tuple[Tensor, ...] | int | list[int | Tensor | Any]]]:

    ...

class RTDetrV2PreTrainedModel(PreTrainedModel):
    config: RTDetrV2Config
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...

class RTDetrV2Decoder(RTDetrV2PreTrainedModel):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(
        self,
        inputs_embeds=...,
        encoder_hidden_states=...,
        encoder_attention_mask=...,
        position_embeddings=...,
        reference_points=...,
        spatial_shapes=...,
        spatial_shapes_list=...,
        level_start_index=...,
        valid_ratios=...,
        output_attentions=...,
        output_hidden_states=...,
        return_dict=...,
    ):  # -> tuple[Any | Tensor | tuple[()] | tuple[Any, ...] | tuple[Any], ...] | RTDetrV2DecoderOutput:

        ...

class RTDetrV2Model(RTDetrV2PreTrainedModel):
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def get_encoder(self):  # -> RTDetrV2HybridEncoder:
        ...
    def get_decoder(self):  # -> RTDetrV2Decoder:
        ...
    def freeze_backbone(self):  # -> None:
        ...
    def unfreeze_backbone(self):  # -> None:
        ...
    @compile_compatible_method_lru_cache(maxsize=32)
    def generate_anchors(self, spatial_shapes=..., grid_size=..., device=..., dtype=...):  # -> tuple[Tensor, Tensor]:
        ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        pixel_mask: torch.LongTensor | None = ...,
        encoder_outputs: torch.FloatTensor | None = ...,
        inputs_embeds: torch.FloatTensor | None = ...,
        decoder_inputs_embeds: torch.FloatTensor | None = ...,
        labels: list[dict] | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.FloatTensor] | RTDetrV2ModelOutput: ...

class RTDetrV2MLPPredictionHead(nn.Module):
    def __init__(self, config, input_dim, d_model, output_dim, num_layers) -> None: ...
    def forward(self, x):  # -> Tensor | Any:
        ...

class RTDetrV2ForObjectDetection(RTDetrV2PreTrainedModel):
    _tied_weights_keys = ...
    _no_split_modules = ...
    def __init__(self, config: RTDetrV2Config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        pixel_mask: torch.LongTensor | None = ...,
        encoder_outputs: torch.FloatTensor | None = ...,
        inputs_embeds: torch.FloatTensor | None = ...,
        decoder_inputs_embeds: torch.FloatTensor | None = ...,
        labels: list[dict] | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
        **kwargs,
    ) -> tuple[torch.FloatTensor] | RTDetrV2ObjectDetectionOutput: ...

__all__ = ["RTDetrV2ForObjectDetection", "RTDetrV2Model", "RTDetrV2PreTrainedModel"]
