from collections import OrderedDict
from typing import Any
from ._utils import _device_t

__all__ = [
    "empty_cache",
    "max_memory_allocated",
    "max_memory_reserved",
    "memory_allocated",
    "memory_reserved",
    "memory_stats",
    "reset_accumulated_memory_stats",
    "reset_peak_memory_stats",
]

def empty_cache() -> None: ...
def memory_stats(device_index: _device_t = ..., /) -> OrderedDict[str, Any]: ...
def memory_allocated(device_index: _device_t = ..., /) -> int: ...
def max_memory_allocated(device_index: _device_t = ..., /) -> int: ...
def memory_reserved(device_index: _device_t = ..., /) -> int: ...
def max_memory_reserved(device_index: _device_t = ..., /) -> int: ...
def reset_accumulated_memory_stats(device_index: _device_t = ..., /) -> None: ...
def reset_peak_memory_stats(device_index: _device_t = ..., /) -> None: ...
