import torch
from torchvision.transforms import functional as F
from torchvision.transforms.v2 import functional as F

from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...image_utils import PILImageResampling, SizeDict
from ...processing_utils import Unpack
from ...utils import is_torchvision_v2_available

if is_torchvision_v2_available(): ...

class DeepseekVLHybridFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    min_size: int
    high_res_size: dict
    high_res_resample: PILImageResampling
    high_res_image_mean: list[float]
    high_res_image_std: list[float]

class DeepseekVLHybridImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    min_size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    valid_kwargs = DeepseekVLHybridFastImageProcessorKwargs
    high_res_image_mean = ...
    high_res_image_std = ...
    high_res_size = ...
    high_res_resample = ...
    def __init__(self, **kwargs: Unpack[DeepseekVLHybridFastImageProcessorKwargs]) -> None: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        min_size: int,
        interpolation: F.InterpolationMode = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...
    def pad_to_square(
        self, images: torch.Tensor, background_color: int | tuple[int, int, int] = ...
    ) -> torch.Tensor: ...

__all__ = ["DeepseekVLHybridImageProcessorFast"]
