from typing import List, Optional

from torchaudio._internal.module_utils import deprecated

from . import utils
from .common import AudioMetaData

__all__ = ["AudioMetaData", "get_audio_backend", "info", "list_audio_backends", "load", "save", "set_audio_backend"]
info = ...
load = ...
save = ...

def list_audio_backends() -> list[str]: ...
@deprecated(...)
def get_audio_backend() -> str | None: ...
@deprecated(...)
def set_audio_backend(backend: str | None):  # -> None:
    ...
