import torch
from torch import Tensor

__all__ = ["FXFloatFunctional", "FloatFunctional", "QFunctional"]

class FloatFunctional(torch.nn.Module):
    def __init__(self) -> None: ...
    def forward(self, x): ...
    def add(self, x: Tensor, y: Tensor) -> Tensor: ...
    def add_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def mul(self, x: Tensor, y: Tensor) -> Tensor: ...
    def mul_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def cat(self, x: list[Tensor], dim: int = ...) -> Tensor: ...
    def add_relu(self, x: Tensor, y: Tensor) -> Tensor: ...
    def matmul(self, x: Tensor, y: Tensor) -> Tensor: ...

class FXFloatFunctional(torch.nn.Module):
    def forward(self, x): ...
    def add(self, x: Tensor, y: Tensor) -> Tensor: ...
    def add_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def mul(self, x: Tensor, y: Tensor) -> Tensor: ...
    def mul_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def cat(self, x: list[Tensor], dim: int = ...) -> Tensor: ...
    def add_relu(self, x: Tensor, y: Tensor) -> Tensor: ...
    def matmul(self, x: Tensor, y: Tensor) -> Tensor: ...

class QFunctional(torch.nn.Module):
    def __init__(self) -> None: ...
    def extra_repr(self) -> str: ...
    def forward(self, x): ...
    def add(self, x: Tensor, y: Tensor) -> Tensor: ...
    def add_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def mul(self, x: Tensor, y: Tensor) -> Tensor: ...
    def mul_scalar(self, x: Tensor, y: float) -> Tensor: ...
    def cat(self, x: list[Tensor], dim: int = ...) -> Tensor: ...
    def add_relu(self, x: Tensor, y: Tensor) -> Tensor: ...
    def matmul(self, x: Tensor, y: Tensor) -> Tensor: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> QFunctional: ...
