import torch
import torch.nn as nn

class AttPool(nn.Module):
    def __init__(self, input_dim: int, att_dim: int) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class Predictor(nn.Module):
    def __init__(self, input_dim: int, att_dim: int) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class SquimSubjective(nn.Module):
    def __init__(self, ssl_model: nn.Module, projector: nn.Module, predictor: nn.Module) -> None: ...
    def forward(self, waveform: torch.Tensor, reference: torch.Tensor) -> Any: ...

def squim_subjective_model(ssl_type: str, feat_dim: int, proj_dim: int, att_dim: int) -> SquimSubjective: ...
def squim_subjective_base() -> SquimSubjective: ...
