import torch
from torch import nn

from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, BaseModelOutputWithPooling, SequenceClassifierOutput
from ...modeling_utils import PreTrainedModel
from .configuration_audio_spectrogram_transformer import ASTConfig

"""PyTorch Audio Spectrogram Transformer (AST) model."""
logger = ...

class ASTEmbeddings(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def get_shape(self, config):  # -> tuple[Any, Any]:
        ...
    def forward(self, input_values: torch.Tensor) -> torch.Tensor: ...

class ASTPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, input_values: torch.Tensor) -> torch.Tensor: ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class ASTSelfAttention(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class ASTSelfOutput(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class ASTAttention(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def prune_heads(self, heads: set[int]) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class ASTIntermediate(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class ASTOutput(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class ASTLayer(GradientCheckpointingLayer):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class ASTEncoder(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        head_mask: torch.Tensor | None = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ) -> tuple | BaseModelOutput: ...

class ASTPreTrainedModel(PreTrainedModel):
    config: ASTConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...

class ASTModel(ASTPreTrainedModel):
    def __init__(self, config: ASTConfig) -> None: ...
    def get_input_embeddings(self) -> ASTPatchEmbeddings: ...
    def forward(
        self,
        input_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutputWithPooling: ...

class ASTMLPHead(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class ASTForAudioClassification(ASTPreTrainedModel):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self,
        input_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        labels: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | SequenceClassifierOutput: ...

__all__ = ["ASTForAudioClassification", "ASTModel", "ASTPreTrainedModel"]
