from collections.abc import Sequence
from pathlib import Path
from typing import Optional, Union

def read_file(fname: Union[Path, str]) -> list[str]: ...
def embed_headers(fname: str, include_dirs: Optional[Union[Sequence[str], Sequence[Path], str]] = ...) -> str: ...

if __name__ == "__main__": ...
