import torch
from torch.overrides import TorchFunctionMode

CURRENT_DEVICE: torch.device | None = ...

class DeviceContext(TorchFunctionMode):
    def __init__(self, device) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def __torch_function__(self, func, types, args=..., kwargs=...): ...

def device_decorator(device, func): ...
def set_device(device):
    """
    Set the default device inside of the wrapped function by decorating it with this function.

    If you would like to use this as a context manager, use device as a
    context manager directly, e.g., ``with torch.device(device)``.
    """
