import contextlib

@contextlib.contextmanager
def report_compile_source_on_error():  # -> Generator[None, Any, None]:
    ...
def shorten_filename(fn, *, base=...): ...
def format_frame(frame, *, base=..., line=...):  # -> str:

    ...
def format_traceback_short(tb):  # -> str:

    ...

class CapturedTraceback:
    __slots__ = ...
    def __init__(self, tb, skip=...) -> None: ...
    def cleanup(self):  # -> None:
        ...
    def summary(self):  # -> StackSummary:
        ...
    def __getstate__(self):  # -> tuple[None, dict[str, int | None]]:
        ...
    @staticmethod
    def extract(*, script=..., cpp=..., skip=...):  # -> CapturedTraceback:

        ...
    def format(self):  # -> list[str]:

        ...
    @staticmethod
    def format_all(tbs):  # -> list[list[str] | None]:

        ...
