import functools
from typing import Any

@functools.cache
def has_triton_package() -> bool: ...
@functools.cache
def get_triton_version(fallback: tuple[int, int] = ...) -> tuple[int, int]: ...
@functools.cache
def has_triton_experimental_host_tma() -> bool: ...
@functools.cache
def has_triton_tensor_descriptor_host_tma() -> bool: ...
@functools.cache
def has_triton_tma() -> bool: ...
@functools.cache
def has_triton_tma_device() -> bool: ...
@functools.lru_cache(None)
def has_triton_stable_tma_api() -> bool: ...
@functools.cache
def has_triton() -> bool: ...
@functools.cache
def triton_backend() -> Any: ...
@functools.cache
def triton_hash_with_backend() -> str: ...
