import enum
from typing import Any

import torch
from torch.types import Device as _Device

__all__ = ["DLDeviceType", "from_dlpack"]

class DLDeviceType(enum.IntEnum):
    kDLCPU = ...
    kDLCUDA = ...
    kDLCUDAHost = ...
    kDLOpenCL = ...
    kDLVulkan = ...
    kDLMetal = ...
    kDLVPI = ...
    kDLROCM = ...
    kDLROCMHost = ...
    kDLExtDev = ...
    kDLCUDAManaged = ...
    kDLOneAPI = ...
    kDLWebGPU = ...
    kDLHexagon = ...
    kDLMAIA = ...

def from_dlpack(ext_tensor: Any, *, device: _Device | None = ..., copy: bool | None = ...) -> torch.Tensor: ...
