class FileBaton:
    def __init__(self, lock_file_path, wait_seconds=..., warn_after_seconds=...) -> None: ...
    def try_acquire(self) -> bool: ...
    def wait(self) -> None: ...
    def release(self) -> None: ...
