import weakref
from collections.abc import MutableMapping
from typing import Self
from weakref import ref

from torch import Tensor

WeakRef = ref
__all__ = ["TensorWeakRef", "WeakIdKeyDictionary", "WeakIdRef", "WeakTensorKeyDictionary"]

class _IterationGuard:
    def __init__(self, weakcontainer) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, e, t, b) -> None: ...

class WeakIdRef(weakref.ref):
    __slots__ = ...
    def __init__(self, key, callback=...) -> None: ...
    def __call__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...

class _WeakHashRef(weakref.ref):
    __slots__ = ...
    def __init__(self, key, callback=...) -> None: ...
    def __call__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...

class WeakIdKeyDictionary(MutableMapping):
    def __init__(self, dict=..., ref_type=...) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...
    def __setitem__(self, key, value) -> None: ...
    def copy(self) -> WeakIdKeyDictionary: ...

    __copy__ = ...
    def __deepcopy__(self, memo) -> Self: ...
    def get(self, key, default=...) -> None: ...
    def __contains__(self, key) -> bool: ...
    def items(self) -> Generator[tuple[Any, Any], Any, None]: ...
    def keys(self) -> Generator[Any, Any, None]: ...

    __iter__ = ...
    def values(self) -> Generator[Any, Any, None]: ...
    def keyrefs(self) -> list[Any]: ...
    def popitem(self) -> tuple[Any, Any]: ...
    def pop(self, key, *args): ...
    def setdefault(self, key, default=...) -> None: ...
    def update(self, dict=..., **kwargs) -> None: ...
    def __ior__(self, other) -> Self: ...
    def __or__(self, other) -> WeakIdKeyDictionary | _NotImplementedType: ...
    def __ror__(self, other) -> Self | _NotImplementedType: ...
    def __eq__(self, other) -> bool: ...

WeakTensorKeyDictionary = WeakIdKeyDictionary

class TensorWeakRef:
    ref: WeakRef[Tensor]
    def __init__(self, tensor: Tensor) -> None: ...
    def __call__(self) -> Tensor | None: ...
