from huggingface_hub import ChatCompletionInputTool

FILENAME_CONFIG = ...
PROMPT_FILENAMES = ...
DEFAULT_AGENT = ...
DEFAULT_SYSTEM_PROMPT = ...
MAX_NUM_TURNS = ...
TASK_COMPLETE_TOOL: ChatCompletionInputTool = ...
ASK_QUESTION_TOOL: ChatCompletionInputTool = ...
EXIT_LOOP_TOOLS: list[ChatCompletionInputTool] = ...
DEFAULT_REPO_ID = ...
