from ..utils import is_accelerate_available, is_eetq_available

if is_eetq_available(): ...
if is_accelerate_available(): ...
logger = ...

def replace_with_eetq_linear(
    model, modules_to_not_convert=..., current_key_name=..., quantization_config=..., pre_quantized=...
): ...
