def eval_env(var, default): ...
def is_module_available(*modules: str) -> bool: ...
def requires_module(*modules: str): ...

UNSUPPORTED = ...

def wrap_deprecated(func, name, direction: str, version: str | None = ..., remove: bool = ...): ...
def deprecated(direction: str, version: str | None = ..., remove: bool = ...): ...

DEPRECATION_MSG = ...
IO_DEPRECATION_MSG = ...
dropping_support = ...

def dropping_class_support(c, msg=...): ...
def dropping_const_support(c, msg=..., name=...): ...

dropping_class_io_support = ...
dropping_io_support = ...

def fail_with_message(message): ...
def no_op(func): ...
