import torch
from _typeshed import Incomplete

class _ParameterMeta(torch._C._TensorMeta):
    def __instancecheck__(self, instance) -> bool: ...

class Parameter(torch.Tensor, metaclass=_ParameterMeta):
    def __len__(self) -> int: ...
    def __new__(cls, data=None, requires_grad: bool = True): ...
    def __deepcopy__(self, memo): ...
    def __reduce_ex__(self, proto): ...
    __torch_function__: Incomplete

class UninitializedTensorMixin:
    data: Incomplete
    __class__: Incomplete
    def materialize(self, shape, device=None, dtype=None) -> None: ...
    @property
    def shape(self) -> None: ...
    def share_memory_(self) -> None: ...
    def __reduce_ex__(self, proto): ...
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None): ...

def is_lazy(param): ...

class UninitializedParameter(UninitializedTensorMixin, Parameter):
    cls_to_become = Parameter
    def __new__(cls, requires_grad: bool = True, device=None, dtype=None) -> None: ...
    def __deepcopy__(self, memo): ...

class _BufferMeta(torch._C._TensorMeta):
    def __instancecheck__(self, instance) -> bool: ...

class Buffer(torch.Tensor, metaclass=_BufferMeta):
    def __new__(cls, data=None, *, persistent: bool = True): ...
    __torch_function__: Incomplete

class UninitializedBuffer(UninitializedTensorMixin, torch.Tensor):
    cls_to_become: Incomplete
    def __new__(cls, requires_grad: bool = False, device=None, dtype=None, persistent: bool = True) -> None: ...
