"""
This type stub file was generated by pyright.
"""

import torch.nn.functional as F
import torch
from typing import Union
from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...image_utils import SizeDict
from ...processing_utils import Unpack
from ...utils import auto_docstring, is_torch_available

if is_torch_available(): ...

class DeepseekVLFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    r"""
    min_size (`int`, *optional*, defaults to 14):
        The minimum allowed size for the resized image. Ensures that neither the height nor width
        falls below this value after resizing.
    """

    min_size: int
    ...

@auto_docstring
class DeepseekVLImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    min_size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    valid_kwargs = DeepseekVLFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[DeepseekVLFastImageProcessorKwargs]) -> None: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        min_size: int,
        interpolation: F.InterpolationMode = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...
    def pad_to_square(self, images: torch.Tensor, background_color: int | tuple[int, int, int] = ...) -> torch.Tensor:
        """
        Pads an image to a square based on the longest edge.

        Args:
            images (`torch.Tensor`):
                The images to pad.
            background_color (`int` or `tuple[int, int, int]`, *optional*, defaults to 0):
                The color to use for the padding. Can be an integer for single channel or a
                tuple of integers representing for multi-channel images. If passed as integer
                in mutli-channel mode, it will default to `0` in subsequent channels.

        Returns:
            `torch.Tensor`: The padded images.
        """
        ...

__all__ = ["DeepseekVLImageProcessorFast"]
