from abc import ABC, abstractmethod
from collections.abc import Callable
from dataclasses import dataclass

import torch
from torchaudio.models import RNNT, RNNTBeamSearch

__all__ = []
_decibel = ...
_gain = ...

class _FunctionalModule(torch.nn.Module):
    def __init__(self, functional) -> None: ...
    def forward(self, input): ...

class _GlobalStatsNormalization(torch.nn.Module):
    def __init__(self, global_stats_path) -> None: ...
    def forward(self, input): ...

class _FeatureExtractor(ABC):
    @abstractmethod
    def __call__(self, input: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]: ...

class _TokenProcessor(ABC):
    @abstractmethod
    def __call__(self, tokens: list[int], **kwargs) -> str: ...

class _ModuleFeatureExtractor(torch.nn.Module, _FeatureExtractor):
    def __init__(self, pipeline: torch.nn.Module) -> None: ...
    def forward(self, input: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]: ...

class _SentencePieceTokenProcessor(_TokenProcessor):
    def __init__(self, sp_model_path: str) -> None: ...
    def __call__(self, tokens: list[int], lstrip: bool = ...) -> str: ...

@dataclass
class RNNTBundle:
    class FeatureExtractor(_FeatureExtractor): ...
    class TokenProcessor(_TokenProcessor): ...

    _rnnt_path: str
    _rnnt_factory_func: Callable[[], RNNT]
    _global_stats_path: str
    _sp_model_path: str
    _right_padding: int
    _blank: int
    _sample_rate: int
    _n_fft: int
    _n_mels: int
    _hop_length: int
    _segment_length: int
    _right_context_length: int
    @property
    def sample_rate(self) -> int: ...
    @property
    def n_fft(self) -> int: ...
    @property
    def n_mels(self) -> int: ...
    @property
    def hop_length(self) -> int: ...
    @property
    def segment_length(self) -> int: ...
    @property
    def right_context_length(self) -> int: ...
    def get_decoder(self) -> RNNTBeamSearch: ...
    def get_feature_extractor(self) -> FeatureExtractor: ...
    def get_streaming_feature_extractor(self) -> FeatureExtractor: ...
    def get_token_processor(self) -> TokenProcessor: ...

EMFORMER_RNNT_BASE_LIBRISPEECH = ...
