from collections.abc import Callable
from typing import Any, NamedTuple, Self, TypeVar, overload

import torch
from torch import Tensor

__all__ = [
    "PackedSequence",
    "invert_permutation",
    "pack_padded_sequence",
    "pack_sequence",
    "pad_packed_sequence",
    "pad_sequence",
    "unpack_sequence",
    "unpad_sequence",
]
_T = TypeVar("_T")
_R = TypeVar("_R")

class PackedSequence_(NamedTuple):
    data: torch.Tensor
    batch_sizes: torch.Tensor
    sorted_indices: torch.Tensor | None
    unsorted_indices: torch.Tensor | None

def bind(optional: _T | None, fn: Callable[[_T], _R]) -> _R | None: ...

class PackedSequence(PackedSequence_):
    def __new__(
        cls,
        data: Tensor,
        batch_sizes: Tensor | None = ...,
        sorted_indices: Tensor | None = ...,
        unsorted_indices: Tensor | None = ...,
    ) -> Self: ...
    def pin_memory(self) -> Self: ...
    @overload
    def to(self, dtype: torch.dtype, non_blocking: bool = ..., copy: bool = ...) -> Self: ...
    @overload
    def to(
        self,
        device: str | torch.device | int | None = ...,
        dtype: torch.dtype | None = ...,
        non_blocking: bool = ...,
        copy: bool = ...,
    ) -> Self: ...
    @overload
    def to(self, other: Tensor, non_blocking: bool = ..., copy: bool = ...) -> Self: ...
    def to(self, *args: Any, **kwargs: Any) -> Self: ...
    def cuda(self, *args: Any, **kwargs: Any) -> Self: ...
    def cpu(self, *args: Any, **kwargs: Any) -> Self: ...
    def double(self) -> Self: ...
    def float(self) -> Self: ...
    def half(self) -> Self: ...
    def long(self) -> Self: ...
    def int(self) -> Self: ...
    def short(self) -> Self: ...
    def char(self) -> Self: ...
    def byte(self) -> Self: ...
    @property
    def is_cuda(self) -> bool: ...
    def is_pinned(self) -> bool: ...

def invert_permutation(permutation: Tensor | None) -> Tensor | None: ...
def pack_padded_sequence(
    input: Tensor, lengths: Tensor | list[int], batch_first: bool = ..., enforce_sorted: bool = ...
) -> PackedSequence: ...
def pad_packed_sequence(
    sequence: PackedSequence, batch_first: bool = ..., padding_value: float = ..., total_length: int | None = ...
) -> tuple[Tensor, Tensor]: ...
def pad_sequence(
    sequences: Tensor | list[Tensor], batch_first: bool = ..., padding_value: float = ..., padding_side: str = ...
) -> Tensor: ...
def unpad_sequence(padded_sequences: Tensor, lengths: Tensor, batch_first: bool = ...) -> list[Tensor]: ...
def pack_sequence(sequences: list[Tensor], enforce_sorted: bool = ...) -> PackedSequence: ...
def unpack_sequence(packed_sequences: PackedSequence) -> list[Tensor]: ...
