"""Triton Implementation of the flex_attention Kernel for short query length (FlexDecoding)"""

from ...select_algorithm import SymbolicGridFn

aten = ...
prims = ...

@SymbolicGridFn
def flex_decoding_grid(batch_size, kv_heads, gqa_group_size, n_keys, d_model, meta): ...

flex_decoding_template = ...

def get_split_k(B: int, H: int, Mk: int) -> int: ...
def create_flex_decoding_kernel(*args, **kwargs):
    """Flex decode lowering that is optimized for small Q_LEN and GQA packing"""
