"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional, Union
from torch import nn
from ...cache_utils import Cache
from ...generation import GenerationMixin
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from ...modeling_utils import PreTrainedModel
from ...utils import auto_docstring
from .configuration_cpmant import CpmAntConfig

logger = ...

class CpmAntLayerNorm(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor): ...

class CpmAntAttention(nn.Module):
    def __init__(self, config: CpmAntConfig, layer_idx=...) -> None: ...
    def forward(
        self,
        hidden_q: torch.Tensor,
        hidden_kv: torch.Tensor,
        attention_mask: torch.BoolTensor,
        position_bias: torch.Tensor,
        output_attentions: Optional[bool] = ...,
        past_key_values: Optional[Cache] = ...,
        use_cache: Optional[bool] = ...,
        cache_position: Optional[torch.Tensor] = ...,
    ): ...

class CpmAntSelfAttentionBlock(nn.Module):
    def __init__(self, config: CpmAntConfig, layer_idx=...) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        position_bias: Optional[torch.Tensor] = ...,
        output_attentions: Optional[bool] = ...,
        past_key_values: Optional[Cache] = ...,
        use_cache: Optional[bool] = ...,
        cache_position: Optional[torch.Tensor] = ...,
    ): ...

class CpmAntDenseGatedACT(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor): ...

class CpmAntFeedForward(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor): ...

class CpmAntFFNBlock(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor): ...

class CpmAntTransformerBlock(nn.Module):
    def __init__(self, config: CpmAntConfig, layer_idx=...) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        position_bias: Optional[torch.Tensor] = ...,
        output_attentions: Optional[bool] = ...,
        past_key_values: Optional[Cache] = ...,
        use_cache: Optional[bool] = ...,
        cache_position: Optional[torch.Tensor] = ...,
    ): ...

class CpmAntEncoder(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        position_bias: torch.Tensor,
        output_attentions: Optional[bool] = ...,
        output_hidden_states: Optional[bool] = ...,
        past_key_values: Optional[Cache] = ...,
        use_cache: Optional[bool] = ...,
        cache_postion: Optional[torch.Tensor] = ...,
    ): ...

class CpmAntIntermediate(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class CpmAntSegmentPositionEmbedding(nn.Module):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def forward(
        self, key_pos: torch.Tensor, query_pos: torch.Tensor, key_segment: torch.Tensor, query_segment: torch.Tensor
    ): ...

class CpmAntOutput(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

@auto_docstring
class CpmAntPreTrainedModel(PreTrainedModel):
    config: CpmAntConfig
    base_model_prefix = ...

@auto_docstring
class CpmAntModel(CpmAntPreTrainedModel):
    def __init__(self, config: CpmAntConfig) -> None: ...
    def get_input_embeddings(self): ...
    def set_input_embeddings(self, embeddings, **kwargs): ...
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.Tensor] = ...,
        output_attentions: Optional[bool] = ...,
        output_hidden_states: Optional[bool] = ...,
        past_key_values: Optional[tuple[tuple[torch.Tensor]]] = ...,
        use_cache: Optional[bool] = ...,
        return_dict: Optional[bool] = ...,
        cache_position: Optional[torch.Tensor] = ...,
        **kwargs,
    ) -> Union[tuple[torch.Tensor], BaseModelOutputWithPast]: ...

@auto_docstring(custom_intro=...)
class CpmAntForCausalLM(CpmAntPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ...
    def __init__(self, config: CpmAntConfig) -> None: ...
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.Tensor] = ...,
        past_key_values: Optional[list[tuple[torch.Tensor, torch.Tensor]]] = ...,
        use_cache: Optional[bool] = ...,
        output_attentions: Optional[bool] = ...,
        output_hidden_states: Optional[bool] = ...,
        labels: Optional[torch.Tensor] = ...,
        return_dict: Optional[bool] = ...,
        attention_mask: Optional[torch.Tensor] = ...,
        cache_position: Optional[torch.Tensor] = ...,
        **kwargs,
    ) -> Union[tuple, CausalLMOutputWithPast]: ...
    def get_input_embeddings(self): ...
    def set_input_embeddings(self, embeddings): ...

__all__ = ["CpmAntForCausalLM", "CpmAntModel", "CpmAntPreTrainedModel"]
