from transformers.utils import is_jieba_available

from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for CPMAnt."""
if is_jieba_available(): ...
logger = ...
VOCAB_FILES_NAMES = ...

def load_vocab(vocab_file):  # -> OrderedDict[Any, Any]:

    ...

class WordpieceTokenizer:
    def __init__(self, vocab, unk_token=..., max_input_chars_per_word=...) -> None: ...
    def tokenize(self, token):  # -> list[str] | list[Any]:
        ...

class CpmAntTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    add_prefix_space = ...
    def __init__(
        self,
        vocab_file,
        bod_token=...,
        eod_token=...,
        bos_token=...,
        eos_token=...,
        pad_token=...,
        unk_token=...,
        line_token=...,
        space_token=...,
        padding_side=...,
        **kwargs,
    ) -> None: ...
    @property
    def bod_token_id(self): ...
    @property
    def eod_token_id(self): ...
    @property
    def newline_id(self): ...
    @property
    def vocab_size(self) -> int: ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def check(self, token):  # -> bool:
        ...
    def convert_tokens_to_string(self, tokens: list[str]) -> str: ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...

__all__ = ["CpmAntTokenizer"]
