import functools
from enum import IntEnum

from . import ir

log = ...

class NCCL_COLL(IntEnum):
    ALL_REDUCE = ...
    ALL_GATHER = ...
    REDUCE_SCATTER = ...
    ALL_TO_ALL = ...

class NVIDIA_GPU_TYPE(IntEnum):
    VOLTA = ...
    AMPERE = ...
    HOPPER = ...

@functools.lru_cache
def get_gpu_type() -> NVIDIA_GPU_TYPE: ...
def get_collective_type(node: ir.IRNode) -> NCCL_COLL: ...
def get_collective_input_size_bytes(node: ir.IRNode) -> int: ...
def get_collective_group_size(node: ir.IRNode) -> int: ...

class NCCL_HW(IntEnum):
    NVLINK = ...
    PCI = ...
    NET = ...

class NCCL_ALGO(IntEnum):
    TREE = ...
    RING = ...

class NCCL_PROTO(IntEnum):
    LL = ...

baseLat = ...
hwLat = ...
llMaxBws = ...

def estimate_nccl_collective_runtime_nccl_estimator(snode) -> float | None: ...
def estimate_nccl_collective_runtime(node: ir.IRNode) -> float: ...
