from collections.abc import Callable
from typing import Any

import torch

aten = ...
META_TAG = ...
MODULE_TAG = ...
CONST_MODULE_TAG = ...
_dont_constant_fold: list[torch.fx.node.Target] = ...

def add_dont_constant_fold(op: torch.fx.node.Target) -> None: ...
def clear_dont_constant_fold() -> None: ...
def replace_node_with_constant(
    gm: torch.fx.GraphModule, node: torch.fx.Node, constant: torch.Tensor | None = ..., name: str | None = ...
) -> None: ...
def is_const_source(node: torch.fx.Node, lifted_constant_names: list[str] | None) -> bool: ...

class ConstantFolder(torch.fx.Interpreter):
    def __init__(
        self,
        gm: torch.fx.GraphModule,
        skip_constructors: bool = ...,
        lifted_constant_names: list[str] | None = ...,
        skip_folding_node_fn: Callable[[torch.fx.Node], bool] | None = ...,
    ) -> None: ...
    def is_impure(self, node: torch.fx.node.Node) -> bool: ...
    def node_to_last_non_output_use(self) -> dict[torch.fx.Node, list[torch.fx.Node]]: ...
    def run_node(self, node: torch.fx.Node) -> Any: ...
    def insertable_tensor_check(self, tensor: torch.Tensor) -> bool: ...
    def add_node_replacement(self, node: torch.fx.Node, tensor: torch.Tensor) -> None: ...
    def run(self) -> Any: ...
    def insert_placerholder_values(self, env: dict[torch.fx.Node, Any]) -> None: ...

def constant_fold(gm: torch.fx.GraphModule, constraint_fn: Callable[[torch.fx.Node], bool] | None = ...) -> None: ...
def constant_graph_tag(
    gm: torch.fx.GraphModule,
    skip_constructors: bool = ...,
    lifted_constant_names: list[str] | None = ...,
    skip_folding_node_fn: Callable[[torch.fx.Node], bool] | None = ...,
) -> None: ...
def run_and_get_constant_graph(
    gm: torch.fx.GraphModule,
    skip_constructors: bool = ...,
    lifted_constant_names: list[str] | None = ...,
    skip_folding_node_fn: Callable[[torch.fx.Node], bool] | None = ...,
) -> torch.fx.GraphModule:
    """
    Construct a GraphModule which corresponds to the part which could be
    constant folded in provided gm.
    """
