from collections.abc import Callable
from typing import Any

import torch
import torch.fx

def matches_module_function_pattern(
    pattern: tuple[type[torch.nn.modules.Module], Callable[..., Any]],
    node: torch.fx.node.Node,
    modules: dict[str, torch.nn.modules.Module],
) -> bool: ...

class FakeTensorUpdater:
    def __init__(self, graph: torch.fx.Graph) -> None: ...
    def hash_node(self, node: torch.fx.Node): ...
    def incremental_update(self): ...

def get_storage(t: torch.Tensor) -> int: ...
def get_node_storage(node: torch.fx.Node) -> int | None: ...
def get_fake(x): ...
def get_fake_args_kwargs(x: torch.fx.Node) -> tuple[bool, tuple[Any], dict[str, Any]]: ...
def is_node_realized(node: torch.fx.Node) -> bool: ...
def count_flops_fx(node: torch.fx.Node) -> int | None: ...
def countable_fx(node: torch.fx.Node) -> bool: ...
