from collections.abc import Sequence
from typing import TYPE_CHECKING, Optional

import torch
from torch import Tensor

if TYPE_CHECKING: ...
log = ...

def make_prim(schema: str, impl_aten, return_type=..., doc: str = ..., tags: Sequence[torch.Tag] | None = ...): ...
def eager_force_stride(input_tensor: Tensor, stride) -> Tensor: ...
def eager_prepare_softmax(x: Tensor, dim: int) -> tuple[Tensor, Tensor]: ...

seed = ...
seeds = ...
lookup_seed = ...
random = ...
randint = ...
force_stride_order = ...
_unsafe_index_put_ = ...
fma = ...
prepare_softmax_online = ...
_low_memory_max_pool_with_offsets = ...
_low_memory_max_pool_offsets_to_indices = ...
