log = ...
aten__weight_int8pack_mm = ...
aten__weight_int4pack_mm_cpu = ...
quantized = ...
_quantized = ...
aten = ...

def register_quantized_ops() -> None: ...
def register_woq_mm_ops() -> None: ...
