import atexit
import dataclasses
from abc import abstractmethod
from collections.abc import Callable
from typing import Any, TypeVar

import redis
from rfe.scubadata.scubadata_py3 import Sample as Sample_
from torch._inductor import config

log = ...
if config.is_fbcode():
    type Sample = Sample_
else:
    type Sample = type[object]
_T = TypeVar("_T")
_U = TypeVar("_U")
remote_fx_cache_get_timed = ...
remote_fx_cache_put_timed = ...

class RemoteCacheBackend[T]:
    """
    A backend implementation for accessing a remote/distributed cache.  Only
    works with bytes in/out.  For structured data use a RemoteCache.
    """
    def __init__(self) -> None: ...
    def get(self, key: str) -> _T | None: ...
    def put(self, key: str, data: _T) -> None: ...

class RemoteCacheSerde[T, U]:
    @abstractmethod
    def encode(self, data: _T) -> _U: ...
    @abstractmethod
    def decode(self, data: _U) -> _T: ...

type JsonDataTy = int | float | str | bool | dict[str, JsonDataTy] | list[JsonDataTy] | None

class RemoteCacheJsonSerde(RemoteCacheSerde[JsonDataTy, bytes]):
    def encode(self, data: JsonDataTy) -> bytes: ...
    def decode(self, data: bytes) -> JsonDataTy: ...

class RemoteCachePassthroughSerde(RemoteCacheSerde[_T, _T]):
    def encode(self, data: _T) -> _T: ...
    def decode(self, data: _T) -> _T: ...

class RemoteCache[T]:
    backend_override_cls: Callable[[], RemoteCacheBackend[Any]] | None = ...
    def __init__(self, backend: RemoteCacheBackend[_U], serde: RemoteCacheSerde[_T, _U]) -> None: ...
    def get(self, key: str) -> _T | None: ...
    def put(self, key: str, value: _T) -> None: ...

class RedisRemoteCacheBackend(RemoteCacheBackend[bytes]):
    """A Redis implementation of a remote/distributed cache."""

    _redis: redis.Redis | None = ...
    def __init__(self, cache_id: str) -> None: ...

class RedisRemoteCache(RemoteCache[JsonDataTy]):
    def __init__(self, cache_id: str) -> None: ...

class RemoteAutotuneCache(RedisRemoteCache): ...
class RemoteBundledAutotuneCache(RedisRemoteCache): ...
class RemoteFxGraphCache(RedisRemoteCache): ...
class RemoteAOTAutogradCache(RedisRemoteCache): ...
class RemoteDynamoPGOCache(RedisRemoteCache): ...

def create_cache(
    key: str, is_fbcode: bool, fb_cache_cls: str, oss_cache_cls: str
) -> RemoteCache[JsonDataTy] | None: ...

@dataclasses.dataclass
class _CacheStat:
    """_CacheStat(miss: 'int' = 0, hit: 'int' = 0, put: 'int' = 0, exception: 'int' = 0)"""

    miss: int = ...
    hit: int = ...
    put: int = ...
    exception: int = ...

class _CacheStats:
    _stats: dict[str, _CacheStat]
    def __init__(self) -> None: ...
    def miss(self, name: str, count: int = ...) -> None: ...
    def hit(self, name: str, count: int = ...) -> None: ...
    def get(self, name: str, value: object | None) -> None: ...
    def put(self, name: str, count: int = ...) -> None: ...
    def exception(self, name: str, count: int = ...) -> None: ...

cache_stats = ...

@atexit.register
def dump_cache_stats() -> None: ...
