from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, TypeVar

import torch
from torch._inductor.choices import InductorChoices
from torch._inductor.codegen.cpp_utils import LocalBufferContext
from torch._inductor.debug import DebugContext
from torch._inductor.graph import GraphLowering
from torch._inductor.ir import ExternKernelNode
from torch._inductor.loop_body import InterpreterShim
from torch._subclasses import FakeTensorMode

from .ops_handler import DefaultHandler, KernelFormatterHandler, MockHandler, OpsHandler, WrapperHandler

threadlocal = ...
T = TypeVar("T")

class NullHandler: ...

_PoisonedVirtual = ...

class Virtualized[T]:
    def __init__(self, vname: str, default: Callable[[], T] | type[NullHandler]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class NullKernelHandler(NullHandler):
    def __init__(self) -> None: ...
    def get_index_dtype_as_torch_dtype(self): ...

_ops: Virtualized[OpsHandler[Any]] = ...
_graph: Virtualized[GraphLowering] = ...
_extern_kernel_nodes: Virtualized[list[ExternKernelNode]] = ...
_real_inputs: Virtualized[list[torch.Tensor]] = ...
_fake_mode: Virtualized[FakeTensorMode] = ...
_kernel: Virtualized[NullKernelHandler] = ...
_debug: Virtualized[DebugContext] = ...
_interpreter: Virtualized[InterpreterShim] = ...
_aot_compilation: Virtualized[bool] = ...
_current_node: Virtualized[torch.fx.Node] = ...
_local_buffer_context: Virtualized[LocalBufferContext] = ...
_choices: Virtualized[InductorChoices] = ...

class OpsValue:
    value: Any
    def __init__(self, value) -> None: ...
    def __add__(self, other): ...
    def __mul__(self, other): ...
    def __sub__(self, other): ...
    def __neg__(self): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __mod__(self, other): ...
    def __pow__(self, other): ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def __xor__(self, other): ...
    def __invert__(self): ...
    def __rshfit__(self, n): ...
    def __lshift__(self, n): ...

class OpsWrapper(DefaultHandler):
    @staticmethod
    def indirect_indexing(index, size, check=..., wrap_neg=...): ...

ops: OpsHandler[Any] = ...

class _V:
    MockHandler = MockHandler
    KernelFormatterHandler = KernelFormatterHandler
    WrapperHandler = WrapperHandler
    set_ops_handler: Callable[[OpsHandler[Any]], AbstractContextManager[None]] = ...
    get_ops_handler: Callable[[], OpsHandler[Any]] = ...
    set_graph_handler: Callable[[GraphLowering], Any] = ...
    set_extern_kernel_nodes: Callable[[list[ExternKernelNode]], Any] = ...
    set_real_inputs: Callable[[Any], Any] = ...
    get_real_inputs: Callable[[], Any] = ...
    set_fake_mode: Callable[[Any], Any] = ...
    get_fake_mode: Callable[[], Any] = ...
    set_kernel_handler: Callable[[Any], Any] = ...
    set_debug_handler: Callable[[Any], Any] = ...
    set_interpreter_handler: Callable[[Any], Any] = ...
    set_aot_compilation: Callable[[bool], Any] = ...
    get_aot_compilation: Callable[[], Any] = ...
    set_current_node: Callable[[Any], Any] = ...
    get_current_node: Callable[[], Any] = ...
    set_local_buffer_context: Callable[[Any], Any] = ...
    get_local_buffer_context: Callable[[], Any] = ...
    set_choices_handler: Callable[[Any], Any] = ...
    @property
    def ops(self) -> OpsHandler[Any]: ...
    @property
    def graph(self) -> GraphLowering: ...
    @property
    def extern_kernel_nodes(self) -> list[ExternKernelNode]: ...
    @property
    def real_inputs(self): ...
    @property
    def fake_mode(self): ...
    @property
    def kernel(self): ...
    @property
    def debug(self): ...
    @property
    def interpreter(self): ...
    @property
    def aot_compilation(self): ...
    @property
    def current_node(self): ...
    @property
    def local_buffer_context(self): ...
    @property
    def choices(self) -> InductorChoices: ...

V = ...
