from dataclasses import dataclass

import torch
from torch import nn

from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, BaseModelOutputWithPooling
from ...modeling_utils import PreTrainedModel
from ...utils import ModelOutput
from .configuration_yolos import YolosConfig

"""PyTorch YOLOS model."""
logger = ...

@dataclass
class YolosObjectDetectionOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    loss_dict: dict | None = ...
    logits: torch.FloatTensor | None = ...
    pred_boxes: torch.FloatTensor | None = ...
    auxiliary_outputs: list[dict] | None = ...
    last_hidden_state: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

class YolosEmbeddings(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(self, pixel_values: torch.Tensor) -> torch.Tensor: ...

class InterpolateInitialPositionEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pos_embed, img_size=...) -> torch.Tensor: ...

class InterpolateMidPositionEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pos_embed, img_size=...) -> torch.Tensor: ...

class YolosPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.Tensor) -> torch.Tensor: ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class YolosSelfAttention(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(
        self, hidden_states, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class YolosSelfOutput(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class YolosAttention(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def prune_heads(self, heads: set[int]) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class YolosIntermediate(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class YolosOutput(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class YolosLayer(GradientCheckpointingLayer):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class YolosEncoder(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        height,
        width,
        head_mask: torch.Tensor | None = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ) -> tuple | BaseModelOutput: ...

class YolosPreTrainedModel(PreTrainedModel):
    config: YolosConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _no_split_modules = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...

class YolosModel(YolosPreTrainedModel):
    def __init__(self, config: YolosConfig, add_pooling_layer: bool = ...) -> None: ...
    def get_input_embeddings(self) -> YolosPatchEmbeddings: ...
    def forward(
        self,
        pixel_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutputWithPooling: ...

class YolosPooler(nn.Module):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(self, hidden_states):  # -> Any:
        ...

class YolosMLPPredictionHead(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers) -> None: ...
    def forward(self, x):  # -> Tensor | Any:
        ...

class YolosForObjectDetection(YolosPreTrainedModel):
    def __init__(self, config: YolosConfig) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        labels: list[dict] | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | YolosObjectDetectionOutput: ...

__all__ = ["YolosForObjectDetection", "YolosModel", "YolosPreTrainedModel"]
