from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

from .base import VariableTracker

def was_instancecheck_override(obj): ...
def raise_unhashable(arg, tx=...): ...
def is_hashable(x): ...

class ConstDictVariable(VariableTracker):
    CONTAINS_GUARD = ...
    _nonvar_fields = ...
    class _HashableTracker:
        def __init__(self, vt) -> None: ...
        @property
        def underlying_value(self): ...
        def __hash__(self) -> int: ...
        def __eq__(self, other: ConstDictVariable._HashableTracker) -> bool: ...

    def __init__(self, items: dict[VariableTracker, VariableTracker], user_cls=..., **kwargs) -> None: ...
    def as_proxy(self): ...
    def debug_repr(self): ...
    def as_python_constant(self): ...
    def keys_as_python_constant(self): ...
    def python_type(self): ...
    def __contains__(self, vt) -> bool: ...
    def len(self) -> int: ...
    def has_new_items(self) -> bool: ...
    def is_new_item(self, value, other): ...
    def reconstruct_kvs_into_new_dict(self, codegen): ...
    def reconstruct(self, codegen: PyCodegen): ...
    def getitem_const_raise_exception_if_absent(self, tx: InstructionTranslator, arg: VariableTracker): ...
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker): ...
    def maybe_getitem_const(self, arg: VariableTracker): ...
    def realize_key_vt(self, arg: VariableTracker): ...
    def install_dict_keys_match_guard(self): ...
    def install_dict_contains_guard(self, tx, args): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def unpack_var_sequence(self, tx): ...
    def call_obj_hasattr(self, tx, name): ...
    def clone(self, **kwargs): ...

class MappingProxyVariable(VariableTracker):
    def __init__(self, dv_dict: ConstDictVariable, **kwargs) -> None: ...
    def python_type(self): ...
    def unpack_var_sequence(self, tx): ...
    def reconstruct(self, codegen: PyCodegen): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...

class NNModuleHooksDictVariable(ConstDictVariable):
    def install_dict_keys_match_guard(self): ...
    def install_dict_contains_guard(self, tx, args): ...

class DefaultDictVariable(ConstDictVariable):
    def __init__(self, items, user_cls, default_factory=..., **kwargs) -> None: ...
    def is_python_constant(self): ...
    def debug_repr(self): ...
    @staticmethod
    def is_supported_arg(arg): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def reconstruct(self, codegen): ...

class SetVariable(ConstDictVariable):
    CONTAINS_GUARD = ...
    def __init__(self, items: list[VariableTracker], **kwargs) -> None: ...
    def debug_repr(self): ...
    @property
    def set_items(self): ...
    def as_proxy(self): ...
    def python_type(self): ...
    def as_python_constant(self): ...
    def reconstruct(self, codegen: PyCodegen): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker): ...
    def install_dict_keys_match_guard(self): ...
    def install_dict_contains_guard(self, tx, args): ...

class FrozensetVariable(SetVariable):
    def __init__(self, items: list[VariableTracker], **kwargs) -> None: ...
    def debug_repr(self): ...
    @property
    def set_items(self): ...
    def python_type(self): ...
    def as_python_constant(self): ...
    def reconstruct(self, codegen: PyCodegen): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...

class DictKeySetVariable(SetVariable):
    def __init__(self, items: list[VariableTracker], **kwargs) -> None: ...
    def debug_repr(self): ...
    def install_dict_keys_match_guard(self): ...
    def install_dict_contains_guard(self, tx, args): ...
    @property
    def set_items(self): ...
    def python_type(self): ...
    def as_python_constant(self): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...

class DictViewVariable(VariableTracker):
    kv: str | None = ...
    def __init__(self, dv_dict: ConstDictVariable, **kwargs) -> None: ...
    @property
    def view_items(self): ...
    @property
    def view_items_vt(self): ...
    def unpack_var_sequence(self, tx): ...
    def reconstruct(self, codegen: PyCodegen): ...
    def call_obj_hasattr(self, tx, name): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...

class DictKeysVariable(DictViewVariable):
    kv = ...
    @property
    def set_items(self): ...
    @property
    def view_items_vt(self): ...
    def python_type(self): ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...

class DictValuesVariable(DictViewVariable):
    kv = ...
    @property
    def view_items_vt(self): ...
    def python_type(self): ...

class DictItemsVariable(DictViewVariable):
    kv = ...
    @property
    def view_items_vt(self): ...
    def python_type(self): ...
