from typing import Any, Optional, Union, final
from typing_extensions import Self
from .base import VariableTracker
from .tensor import SymNodeVariable

class LazyCache:
    def __init__(self, value: Any, source: Any) -> None: ...
    def realize(self) -> None: ...

@final
class LazyVariableTracker(VariableTracker):
    _nonvar_fields = ...
    @staticmethod
    def create(value: Any, source: Any, **options: Any) -> LazyVariableTracker: ...
    def __init__(self, _cache: LazyCache, **kwargs: Any) -> None: ...
    def realize(self) -> VariableTracker: ...
    def unwrap(self) -> Union[VariableTracker, Self]: ...
    def is_realized(self) -> bool: ...
    def clone(self, **kwargs: Any) -> VariableTracker: ...
    def peek_type(self) -> type[Any]: ...
    def peek_value(self) -> Any: ...
    def set_name_hint(self, name: str) -> None: ...
    def __getattr__(self, item: str) -> Any: ...

    visit = ...
    __repr__ = ...
    @classmethod
    def realize_all(cls, value: Any, cache: Optional[dict[int, tuple[Any, Any]]] = ...) -> Any: ...
    def is_hashable(self) -> bool: ...
    def original_value(self) -> Any: ...
    def original_source(self) -> Any: ...

class LazySymNodeFormatString:
    def __init__(self, sym_node_variable: SymNodeVariable, fmt_spec_var: VariableTracker) -> None: ...
