from contextlib import contextmanager

import torch.nn
from torch._dynamo.symbolic_convert import InstructionTranslator

from .base import VariableTracker
from .user_defined import UserDefinedObjectVariable

def initialize_lazy_module(tx: InstructionTranslator, mod, args, kwargs): ...
@contextmanager
def record_nn_module_stack(module_key: str, source, tx, mod: torch.nn.Module): ...
def guard_to_detect_forward_monkeypatching(source, mod): ...

class NNModuleVariable(VariableTracker):
    _nonvar_fields = ...
    def __init__(self, module_type: type, module_key: str, value: torch.nn.Module, **kwargs) -> None: ...
    def get_nn_module_stack_source(self): ...
    def set_nn_module_stack_source(self, source): ...
    def python_type(self): ...
    def unpack_var_sequence(self, tx): ...
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> VariableTracker: ...
    def is_training(self, tx): ...
    def convert_to_unspecialized(self, tx): ...
    def has_key_in_generic_dict(self, tx: InstructionTranslator, key): ...
    def var_getattr(self, tx: InstructionTranslator, name): ...
    def call_function(self, tx, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker: ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker], constant=...
    ) -> VariableTracker: ...

class UnspecializedNNModuleVariable(UserDefinedObjectVariable):
    _nonvar_fields = ...
    def __init__(self, value, **kwargs) -> None: ...
    def get_nn_module_stack_source(self): ...
    def set_nn_module_stack_source(self, source): ...
    def unpack_var_sequence(self, tx): ...
    def call_function(
        self, tx: InstructionTranslator, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def getattr_helper(self, tx: InstructionTranslator, field, name_vt): ...
    def var_getattr(self, tx: InstructionTranslator, name): ...
    def manually_trace_nn_module_getattr(self, tx: InstructionTranslator, name): ...

class UnspecializedBuiltinNNModuleVariable(UnspecializedNNModuleVariable): ...

class FSDPManagedNNModuleVariable(UnspecializedNNModuleVariable):
    def __init__(self, value, **kwargs) -> None: ...
