from torch._dynamo.symbolic_convert import InstructionTranslator

from .base import VariableTracker
from .user_defined import UserDefinedObjectVariable

class ArgMappingException(Exception): ...
class GuardInstallException(Exception): ...

perf_hint_log = ...

class OptimizerVariable(UserDefinedObjectVariable):
    _nonvar_fields = ...
    def __init__(self, value, grad_to_source=..., static_tensor_names=..., tensor_to_source=..., **kwargs) -> None: ...
    def call_method(
        self, tx, name, args: list[VariableTracker], kwargs: dict[str, VariableTracker]
    ) -> VariableTracker: ...
    def var_getattr(self, tx: InstructionTranslator, name): ...
    def graph_break_if_pending_mutation(self, tx): ...
    def get_python_args(self, *args, **kwargs): ...
    def move_step_if_cpu(self): ...
    def map_sources_and_install_guards(self, tx): ...
    def wrap_tensor(self, tx: InstructionTranslator, tensor_value): ...
    def update_list_args(self, tx: InstructionTranslator, args, kwargs, py_args, py_kwargs): ...
    def create_finalizer(self, tx): ...
