from .base import VariableTracker
from .user_defined import UserDefinedObjectVariable

class TorchScriptObjectVariable(UserDefinedObjectVariable):
    _fake_script_object_cache: dict[int, TorchScriptObjectVariable] = ...
    @classmethod
    def is_matching_cls(cls, user_cls: type): ...
    @staticmethod
    def create(proxy, value, **options): ...
    def __init__(self, proxy, value, source, **kwargs) -> None: ...
    def as_proxy(self): ...
    @_raise_hard_error_if_graph_break(...)
    def var_getattr(self, tx, name: str) -> VariableTracker: ...
    @_raise_hard_error_if_graph_break(...)
    def call_method(self, tx, name, args, kwargs): ...
