from typing import TYPE_CHECKING

from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

from .base import VariableTracker

if TYPE_CHECKING: ...
PARAM_NAMES = ...

class SDPAParamsVariable(VariableTracker):
    @staticmethod
    def create(tx: InstructionTranslator, value, source):  # -> VariableTracker:
        ...
    def __init__(self, proxy, param_vars, **kwargs) -> None: ...
    def reconstruct(self, codegen: PyCodegen):  # -> None:
        ...
    def as_proxy(self):  # -> Any:
        ...
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker: ...
    @staticmethod
    def is_sdpa_params(value):  # -> bool:
        ...
