from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Literal

from .lfs import UploadInfo

"""
Type definitions and utilities for the `create_commit` API
"""

logger = ...
type UploadMode = Literal["lfs", "regular"]
FETCH_LFS_BATCH_SIZE = ...
UPLOAD_BATCH_MAX_NUM_FILES = ...

@dataclass
class CommitOperationDelete:
    path_in_repo: str
    is_folder: bool | Literal["auto"] = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class CommitOperationCopy:
    src_path_in_repo: str
    path_in_repo: str
    src_revision: str | None = ...
    _src_oid: str | None = ...
    _dest_oid: str | None = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class CommitOperationAdd:
    path_in_repo: str
    path_or_fileobj: str | Path | bytes | BinaryIO
    upload_info: UploadInfo = ...
    _upload_mode: UploadMode | None = ...
    _should_ignore: bool | None = ...
    _remote_oid: str | None = ...
    _is_uploaded: bool = ...
    _is_committed: bool = ...
    def __post_init__(self) -> None: ...
    @contextmanager
    def as_file(self, with_tqdm: bool = ...) -> Iterator[BinaryIO]: ...
    def b64content(self) -> bytes: ...

type CommitOperation = CommitOperationAdd | CommitOperationCopy | CommitOperationDelete
