from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum

class SpaceStage(StrEnum):
    NO_APP_FILE = ...
    CONFIG_ERROR = ...
    BUILDING = ...
    BUILD_ERROR = ...
    RUNNING = ...
    RUNNING_BUILDING = ...
    RUNTIME_ERROR = ...
    DELETING = ...
    STOPPED = ...
    PAUSED = ...

class SpaceHardware(StrEnum):
    CPU_BASIC = ...
    CPU_UPGRADE = ...
    CPU_XL = ...
    ZERO_A10G = ...
    T4_SMALL = ...
    T4_MEDIUM = ...
    L4X1 = ...
    L4X4 = ...
    L40SX1 = ...
    L40SX4 = ...
    L40SX8 = ...
    A10G_SMALL = ...
    A10G_LARGE = ...
    A10G_LARGEX2 = ...
    A10G_LARGEX4 = ...
    A100_LARGE = ...
    H100 = ...
    H100X8 = ...

class SpaceStorage(StrEnum):
    SMALL = ...
    MEDIUM = ...
    LARGE = ...

@dataclass
class SpaceRuntime:
    stage: SpaceStage
    hardware: SpaceHardware | None
    requested_hardware: SpaceHardware | None
    sleep_time: int | None
    storage: SpaceStorage | None
    raw: dict
    def __init__(self, data: dict) -> None: ...

@dataclass
class SpaceVariable:
    key: str
    value: str
    description: str | None
    updated_at: datetime | None
    def __init__(self, key: str, values: dict) -> None: ...
