from collections.abc import Iterator
from dataclasses import dataclass
from datetime import datetime
from typing import Any

import fsspec

SPECIAL_REFS_REVISION_REGEX = ...

@dataclass
class HfFileSystemResolvedPath:
    repo_type: str
    repo_id: str
    revision: str
    path_in_repo: str
    _raw_revision: str | None = ...
    def unresolve(self) -> str: ...

class HfFileSystem(fsspec.AbstractFileSystem):
    root_marker = ...
    protocol = ...
    def __init__(
        self,
        *args,
        endpoint: str | None = ...,
        token: bool | str | None = ...,
        block_size: int | None = ...,
        **storage_options,
    ) -> None: ...
    def resolve_path(self, path: str, revision: str | None = ...) -> HfFileSystemResolvedPath: ...
    def invalidate_cache(self, path: str | None = ...) -> None: ...
    def rm(
        self, path: str, recursive: bool = ..., maxdepth: int | None = ..., revision: str | None = ..., **kwargs
    ) -> None: ...
    def ls(
        self, path: str, detail: bool = ..., refresh: bool = ..., revision: str | None = ..., **kwargs
    ) -> list[str | dict[str, Any]]: ...
    def walk(self, path: str, *args, **kwargs) -> Iterator[tuple[str, list[str], list[str]]]: ...
    def glob(self, path: str, **kwargs) -> list[str]: ...
    def find(
        self,
        path: str,
        maxdepth: int | None = ...,
        withdirs: bool = ...,
        detail: bool = ...,
        refresh: bool = ...,
        revision: str | None = ...,
        **kwargs,
    ) -> list[str] | dict[str, dict[str, Any]]: ...
    def cp_file(self, path1: str, path2: str, revision: str | None = ..., **kwargs) -> None: ...
    def modified(self, path: str, **kwargs) -> datetime: ...
    def info(self, path: str, refresh: bool = ..., revision: str | None = ..., **kwargs) -> dict[str, Any]: ...
    def exists(self, path, **kwargs):  # -> bool:

        ...
    def isdir(self, path):  # -> Any | Literal[False]:

        ...
    def isfile(self, path):  # -> Any | Literal[False]:

        ...
    def url(self, path: str) -> str: ...
    def get_file(self, rpath, lpath, callback=..., outfile=..., **kwargs) -> None: ...
    @property
    def transaction(self): ...
    def start_transaction(self): ...
    def __reduce__(
        self,
    ):  # -> tuple[Callable[..., Any], tuple[type[Self], Any, Any, dict[str, Dict[str, List[Dict[str, Any]]] | Dict[Tuple[str, str, str | None], Tuple[bool, Exception | None]]]]]:
        ...

class HfFileSystemFile(fsspec.spec.AbstractBufferedFile):
    def __init__(self, fs: HfFileSystem, path: str, revision: str | None = ..., **kwargs) -> None: ...
    def __del__(self) -> None:  # -> None:
        ...
    def read(self, length=...): ...
    def url(self) -> str: ...

class HfFileSystemStreamFile(fsspec.spec.AbstractBufferedFile):
    def __init__(
        self,
        fs: HfFileSystem,
        path: str,
        mode: str = ...,
        revision: str | None = ...,
        block_size: int = ...,
        cache_type: str = ...,
        **kwargs,
    ) -> None: ...
    def seek(self, loc: int, whence: int = ...):  # -> None:
        ...
    def read(self, length: int = ...):  # -> bytes | Any:
        ...
    def url(self) -> str: ...
    def __del__(self) -> None:  # -> None:
        ...
    def __reduce__(self):  # -> tuple[Callable[..., Any], tuple[HfFileSystem, Any, Any, Any, Any]]:
        ...

def safe_revision(revision: str) -> str: ...
def safe_quote(s: str) -> str: ...
def reopen(fs: HfFileSystem, path: str, mode: str, block_size: int, cache_type: str): ...
def make_instance(cls, args, kwargs, instance_cache_attributes_dict): ...
