import subprocess
from collections.abc import Callable
from contextlib import contextmanager
from pathlib import Path
from typing import TypedDict

from .hf_api import HfApi
from .utils import tqdm, validate_hf_hub_args
from .utils._deprecation import _deprecate_method

logger = ...

class CommandInProgress:
    def __init__(
        self,
        title: str,
        is_done_method: Callable,
        status_method: Callable,
        process: subprocess.Popen,
        post_method: Callable | None = ...,
    ) -> None: ...
    @property
    def is_done(self) -> bool: ...
    @property
    def status(self) -> int: ...
    @property
    def failed(self) -> bool: ...
    @property
    def stderr(self) -> str: ...
    @property
    def stdout(self) -> str: ...

def is_git_repo(folder: str | Path) -> bool: ...
def is_local_clone(folder: str | Path, remote_url: str) -> bool: ...
def is_tracked_with_lfs(filename: str | Path) -> bool: ...
def is_git_ignored(filename: str | Path) -> bool: ...
def is_binary_file(filename: str | Path) -> bool: ...
def files_to_be_staged(pattern: str = ..., folder: str | Path | None = ...) -> list[str]: ...
def is_tracked_upstream(folder: str | Path) -> bool: ...
def commits_to_push(folder: str | Path, upstream: str | None = ...) -> int: ...

class PbarT(TypedDict):
    bar: tqdm
    past_bytes: int

class Repository:
    command_queue: list[CommandInProgress]
    @validate_hf_hub_args
    @_deprecate_method(
        version="1.0",
        message=...,
    )
    def __init__(
        self,
        local_dir: str | Path,
        clone_from: str | None = ...,
        repo_type: str | None = ...,
        token: bool | str = ...,
        git_user: str | None = ...,
        git_email: str | None = ...,
        revision: str | None = ...,
        skip_lfs_files: bool = ...,
        client: HfApi | None = ...,
    ) -> None: ...
    @property
    def current_branch(self) -> str: ...
    def check_git_versions(self):  # -> None:

        ...
    @validate_hf_hub_args
    def clone_from(self, repo_url: str, token: bool | str | None = ...):  # -> None:

        ...
    def git_config_username_and_email(self, git_user: str | None = ..., git_email: str | None = ...):  # -> None:

        ...
    def git_credential_helper_store(self):  # -> None:

        ...
    def git_head_hash(self) -> str: ...
    def git_remote_url(self) -> str: ...
    def git_head_commit_url(self) -> str: ...
    def list_deleted_files(self) -> list[str]: ...
    def lfs_track(self, patterns: str | list[str], filename: bool = ...):  # -> None:

        ...
    def lfs_untrack(self, patterns: str | list[str]):  # -> None:

        ...
    def lfs_enable_largefiles(self):  # -> None:

        ...
    def auto_track_binary_files(self, pattern: str = ...) -> list[str]: ...
    def auto_track_large_files(self, pattern: str = ...) -> list[str]: ...
    def lfs_prune(self, recent=...):  # -> None:

        ...
    def git_pull(self, rebase: bool = ..., lfs: bool = ...):  # -> None:

        ...
    def git_add(self, pattern: str = ..., auto_lfs_track: bool = ...):  # -> None:

        ...
    def git_commit(self, commit_message: str = ...):  # -> None:

        ...
    def git_push(
        self, upstream: str | None = ..., blocking: bool = ..., auto_lfs_prune: bool = ...
    ) -> str | tuple[str, CommandInProgress]: ...
    def git_checkout(self, revision: str, create_branch_ok: bool = ...):  # -> None:

        ...
    def tag_exists(self, tag_name: str, remote: str | None = ...) -> bool: ...
    def delete_tag(self, tag_name: str, remote: str | None = ...) -> bool: ...
    def add_tag(self, tag_name: str, message: str | None = ..., remote: str | None = ...):  # -> None:

        ...
    def is_repo_clean(self) -> bool: ...
    def push_to_hub(
        self, commit_message: str = ..., blocking: bool = ..., clean_ok: bool = ..., auto_lfs_prune: bool = ...
    ) -> None | str | tuple[str, CommandInProgress]: ...
    @contextmanager
    def commit(
        self,
        commit_message: str,
        branch: str | None = ...,
        track_large_files: bool = ...,
        blocking: bool = ...,
        auto_lfs_prune: bool = ...,
    ):  # -> Generator[Self, Any, None]:

        ...
    def repocard_metadata_load(self) -> dict | None: ...
    def repocard_metadata_save(self, data: dict) -> None: ...
    @property
    def commands_failed(self):  # -> list[CommandInProgress]:

        ...
    @property
    def commands_in_progress(self):  # -> list[CommandInProgress]:

        ...
    def wait_for_commands(self):  # -> None:

        ...
