"""
This type stub file was generated by pyright.
"""

from contextvars import ContextVar
from typing import Protocol

class Buffer(Protocol):
    def data_ptr(self) -> int: ...

class Allocator(Protocol):
    def __call__(self, size: int, alignment: int, stream: int | None) -> Buffer: ...

class NullAllocator:
    def __call__(self, size: int, alignment: int, stream: int | None) -> Buffer: ...

_allocator: ContextVar[Allocator] = ...

def set_allocator(allocator: Allocator):  # -> None:
    """
    The allocator function is called during kernel launch for kernels that
    require additional global memory workspace.
    """

_profile_allocator: Allocator = ...

def set_profile_allocator(allocator: Allocator | None):  # -> None:
    """
    The profile allocator function is called before kernel launch for kernels
    that require additional global memory workspace.
    """
