from ...processing_utils import ProcessorMixin

"""
Processor class for TVP.
"""

class TvpProcessor(ProcessorMixin):
    attributes = ...
    image_processor_class = ...
    tokenizer_class = ...
    def __init__(self, image_processor=..., tokenizer=..., **kwargs) -> None: ...
    def __call__(self, text=..., videos=..., return_tensors=..., **kwargs):  # -> BatchEncoding:

        ...
    def batch_decode(self, *args, **kwargs): ...
    def decode(self, *args, **kwargs): ...
    def post_process_video_grounding(self, logits, video_durations):  # -> tuple[Any, Any]:

        ...
    @property
    def model_input_names(self):  # -> list[Any]:
        ...

__all__ = ["TvpProcessor"]
