from .. import lowering as L
from ..select_algorithm import SymbolicGridFn

log = ...
aten = ...

@SymbolicGridFn
def bmm_grid(b, m, n, meta, *, cdiv): ...

bmm_template = ...
aten_bmm = ...
aten_bmm_dtype = ...
aten_baddbmm = ...

@L.register_lowering(aten.bmm)
def tuned_bmm(mat1, mat2, out_dtype=..., *, layout=...):
    """Lowering for autotuning aten.bmm with different backends (Aten, Triton, CUTLASS, etc.)"""

@L.register_lowering(aten.baddbmm)
def tuned_baddbmm(inp, mat1, mat2, *, alpha=..., beta=..., layout=...):
    """Lowering for autotuning aten.mm with different backends (Aten, Triton, CUTLASS, etc.)"""
