from typing import TYPE_CHECKING
from .. import lowering as L
from ..select_algorithm import SymbolicGridFn

if TYPE_CHECKING: ...
log = ...
aten = ...

@SymbolicGridFn
def bmm_grid(b, m, n, meta, *, cdiv):  # -> tuple[Any, Any, Literal[1]]:
    ...

bmm_template = ...
aten_bmm = ...
aten_bmm_dtype = ...
aten_baddbmm = ...

@L.register_lowering(aten.bmm)
def tuned_bmm(mat1, mat2, out_dtype=..., *, layout=...):  # -> TensorBox | ShapeAsConstantBuffer:

    ...
@L.register_lowering(aten.baddbmm)
def tuned_baddbmm(inp, mat1, mat2, *, alpha=..., beta=..., layout=...):  # -> TensorBox | ShapeAsConstantBuffer:

    ...
