from typing import Any

from torch._inductor.select_algorithm import SymbolicGridFn

from ..ir import TensorBox

log = ...

@SymbolicGridFn
def mm_grid(m, n, meta, *, cdiv):  # -> tuple[Any, Literal[1], Literal[1]]:

    ...
@SymbolicGridFn
def persistent_mm_grid(M: int, N: int, meta: dict[str, Any], *, cdiv, min):  # -> tuple[Any, Literal[1], Literal[1]]:

    ...
@SymbolicGridFn
def persistent_grouped_mm_grid(*args):  # -> tuple[Any, Literal[1], Literal[1]]:
    ...
def acc_type(dtype):  # -> str:
    ...
def mm_args(
    mat1, mat2, *others, layout=..., out_dtype=..., use_4x2_dim=..., mat2_transposed=...
):  # -> list[Any | FixedLayout | list[Any | list[Any]] | list[Any | list[Any | list[Any]]]]:

    ...
def addmm_epilogue(dtype, alpha, beta):  # -> Callable[..., Any]:
    ...
def scale_mm_epilogue():  # -> Callable[..., Any]:

    ...
def check_supported_striding(mat_a: TensorBox, mat_b: TensorBox) -> None: ...
def is_batch_stride_largest_or_zero(mat1, mat2, layout) -> bool: ...
