from ..utils import cache_on_self

log = ...

class MultiKernelState:
    def __init__(self) -> None: ...
    def define_kernel(self, kernels):  # -> str:

        ...

class MultiKernel:
    def __init__(self, kernels) -> None: ...
    @staticmethod
    def merge_workspaces_inplace(kernels):  # -> list[Any] | None:
        ...
    def call_kernel(self, kernel_name):  # -> None:

        ...
    def codegen_nan_check(self):  # -> None:
        ...
    @property
    def removed_buffers(self):  # -> OrderedSet[Any]:
        ...
    @property
    def inplaced_to_remove(self):  # -> OrderedSet[Any]:
        ...
    @property
    @cache_on_self
    def inplace_update_buffers(self): ...
    def warn_mix_layout(self, kernel_name: str):  # -> None:
        ...

class MultiKernelCall:
    def __init__(self, multi_kernel_name, kernels, arg_index, shape_specialize=...) -> None: ...
    def cache_file_path(self):  # -> Path:
        ...
    def load_cache(self):  # -> None:
        ...
    def store_cache(self):  # -> None:
        ...
    @property
    def kernels(self):  # -> Any:

        ...
    def benchmark_sub_kernels(self, *args, **kwargs):  # -> list[float | list[float]]:

        ...
    @staticmethod
    def record_choice(multi_kernel_name: str, picked_kernel_name: str):  # -> None:

        ...
    @staticmethod
    def lookup_choice(multi_kernel_name: str) -> str: ...
    def run(self, *args, **kwargs):  # -> None:
        ...
