import sympy
from torch._inductor.codegen.triton import TritonKernel

class TritonSplitScanKernel(TritonKernel):
    def __init__(self, tiling: dict[str, sympy.Expr], pid_cache=..., fixed_config=..., **kwargs) -> None: ...
    def should_use_persistent_reduction(self) -> bool: ...
    def should_use_cooperative_reduction(self) -> bool: ...
    def initialize_range_tree(self, pid_cache):  # -> None:
        ...
    def reduction(self, dtype, src_dtype, reduction_type, value): ...
    def scan(self, dtypes, combine_fn, values):  # -> tuple[TritonCSEVariable]:

        ...
