def is_available() -> bool: ...

VERBOSE_OFF = ...
VERBOSE_ON = ...

class verbose:
    def __init__(self, enable) -> None: ...
    def __enter__(self) -> Self | None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> Literal[False]: ...
