DefaultDTypes = ...
_default_dtypes = ...

def default_dtypes(): ...
def get_default_dtype_for(dtype): ...
def can_cast_impl(from_torch_dtype, to_torch_dtype, casting): ...
def result_type_impl(*tensors): ...
def python_type_for_torch(dtyp): ...

_SCALAR_TYPES = ...
_SCALAR_AND_SYMBOLIC_TYPES = ...
_NEP50_FUNCS_TENSOR_ONLY = ...

def is_scalar(x): ...
def is_scalar_or_symbolic(x): ...
def is_float_or_fp_tensor(x): ...
def is_complex_or_complex_tensor(x): ...
def nep50_to_tensors(x1, x2, handle_weaks, function_name): ...
