from ._normalizations import ArrayLike, NotImplementedType, normalizer

newaxis = ...
FLAGS = ...
SHORTHAND_TO_FLAGS = ...

class Flags:
    def __init__(self, flag_to_value: dict) -> None: ...
    def __getattr__(self, attr: str): ...
    def __getitem__(self, key): ...
    def __setattr__(self, attr, value) -> None: ...
    def __setitem__(self, key, value) -> None: ...

def create_method(fn, name=...): ...

methods = ...
dunder = ...
ri_dunder = ...

class _Unspecified: ...

class ndarray:
    def __init__(self, t=...) -> None: ...

    conj = ...
    conjugate = ...
    __divmod__ = ...
    __rdivmod__ = ...
    @property
    def shape(self): ...
    @property
    def size(self): ...
    @property
    def ndim(self): ...
    @property
    def dtype(self): ...
    @property
    def strides(self): ...
    @property
    def itemsize(self): ...
    @property
    def flags(self): ...
    @property
    def data(self): ...
    @property
    def nbytes(self): ...
    @property
    def T(self): ...
    @property
    def real(self): ...
    @real.setter
    def real(self, value): ...
    @property
    def imag(self): ...
    @imag.setter
    def imag(self, value): ...
    def astype(self, dtype, order=..., casting=..., subok=..., copy=...): ...
    @normalizer
    def copy(self: ArrayLike, order: NotImplementedType = ...): ...
    @normalizer
    def flatten(self: ArrayLike, order: NotImplementedType = ...): ...
    def resize(self, *new_shape, refcheck=...): ...
    def view(self, dtype=..., type=...): ...
    @normalizer
    def fill(self, value: ArrayLike): ...
    def tolist(self): ...
    def __iter__(self): ...

    __repr__ = ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __index__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def is_integer(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, x) -> bool: ...
    def transpose(self, *axes): ...
    def reshape(self, *shape, order=...): ...
    def sort(self, axis=..., kind=..., order=...): ...
    def item(self, *args): ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, value) -> None: ...

    take = ...
    put = ...
    def __dlpack__(self, *, stream=...): ...
    def __dlpack_device__(self): ...

def array(obj, dtype=..., *, copy=..., order=..., subok=..., ndmin=..., like=...): ...
def asarray(a, dtype=..., order=..., *, like=...): ...
def ascontiguousarray(a, dtype=..., *, like=...): ...
def from_dlpack(x, /): ...
def can_cast(from_, to, casting=...): ...
def result_type(*arrays_and_dtypes): ...
