""" "Normalize" arguments: convert array_likes to tensors, dtypes to torch dtypes and so on."""

import typing

ArrayLike = typing.TypeVar("ArrayLike")
type Scalar = int | float | complex | bool
type ArrayLikeOrScalar[ArrayLike] = ArrayLike | Scalar
DTypeLike = typing.TypeVar("DTypeLike")
AxisLike = typing.TypeVar("AxisLike")
NDArray = typing.TypeVar("NDArray")
CastingModes = typing.TypeVar("CastingModes")
KeepDims = typing.TypeVar("KeepDims")
OutArray = typing.TypeVar("OutArray")

def normalize_array_like(x, parm=...): ...
def normalize_array_like_or_scalar(x, parm=...): ...
def normalize_optional_array_like_or_scalar(x, parm=...): ...
def normalize_optional_array_like(x, parm=...): ...
def normalize_seq_array_like(x, parm=...): ...
def normalize_dtype(dtype, parm=...): ...
def normalize_not_implemented(arg, parm): ...
def normalize_axis_like(arg, parm=...): ...
def normalize_ndarray(arg, parm=...): ...
def normalize_outarray(arg, parm=...): ...
def normalize_casting(arg, parm=...): ...

normalizers = ...

def maybe_normalize(arg, parm):
    """Normalize arg if a normalizer is registered."""

def maybe_copy_to(out, result, promote_scalar_result=...): ...
def wrap_tensors(result): ...
def array_or_scalar(values, py_type=..., return_scalar=...): ...
def normalizer(_func=..., *, promote_scalar_result=...): ...
