import dataclasses
from abc import ABC, abstractmethod
from collections import defaultdict
from collections.abc import Generator
from contextlib import contextmanager
from typing import Any, Optional, TypeAlias
from torch.utils._appending_byte_serializer import AppendingByteSerializer, BytesReader, BytesWriter
from torch.utils._ordered_set import OrderedSet

log = ...

@dataclasses.dataclass(frozen=True)
class CacheArtifact(ABC):
    key: str
    content: bytes = ...
    @staticmethod
    def serialize(writer: BytesWriter, cls: CacheArtifact) -> None: ...
    @staticmethod
    def deserialize(artifact_type: str, reader: BytesReader) -> CacheArtifact: ...
    @staticmethod
    def encode(content: Any) -> bytes: ...
    @abstractmethod
    def populate_cache(self) -> None: ...
    def precompile_compatible(self) -> bool: ...
    @staticmethod
    def type() -> str: ...

class CacheArtifactFactory:
    _artifact_types: dict[str, type[CacheArtifact]] = ...
    @classmethod
    def register(cls, artifact_cls: type[CacheArtifact]) -> type[CacheArtifact]: ...
    @classmethod
    def create(cls, artifact_type_key: str, key: str, content: bytes) -> CacheArtifact: ...
    @classmethod
    def encode_create(cls, artifact_type_key: str, key: str, content: Any) -> CacheArtifact: ...

@dataclasses.dataclass
class CacheInfo:
    artifacts: defaultdict[str, list[str]] = ...
    @property
    def inductor_artifacts(self) -> list[str]: ...
    @property
    def autotune_artifacts(self) -> list[str]: ...
    @property
    def aot_autograd_artifacts(self) -> list[str]: ...
    @property
    def pgo_artifacts(self) -> list[str]: ...
    @property
    def precompile_aot_autograd_artifacts(self) -> list[str]: ...
    @property
    def precompile_dynamo_artifacts(self) -> list[str]: ...
    def add(self, artifact: CacheArtifact) -> None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...

CacheArtifactsResult: TypeAlias = dict[str, list[CacheArtifact]]

class CacheArtifactManager:
    _new_cache_artifacts: CacheArtifactsResult = ...
    _seen_artifacts: OrderedSet[CacheArtifact] = ...
    _serializer: AppendingByteSerializer[tuple[str, list[CacheArtifact]]] = ...
    _cache_info: CacheInfo = ...
    @classmethod
    def clear(cls) -> None: ...
    @classmethod
    @contextmanager
    def with_fresh_cache(cls) -> Generator[None, None, None]: ...
    @classmethod
    def record_artifact(cls, artifact_type: str, key: str, content: Any) -> None: ...
    @classmethod
    def need_serialize(cls) -> bool: ...
    @classmethod
    def serialize(cls) -> Optional[tuple[bytes, CacheInfo]]: ...
    @staticmethod
    def deserialize(serialized_artifacts: bytes) -> Optional[CacheArtifactsResult]: ...
    @staticmethod
    def populate_caches(artifacts: CacheArtifactsResult) -> CacheInfo: ...
