from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for FastSpeech2Conformer."""
logger = ...
VOCAB_FILES_NAMES = ...

class FastSpeech2ConformerTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self, vocab_file, bos_token=..., eos_token=..., pad_token=..., unk_token=..., should_strip_spaces=..., **kwargs
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, Any]:

        ...
    def prepare_for_tokenization(self, text, is_split_into_words=..., **kwargs):  # -> tuple[str, dict[str, Any]]:
        ...
    def decode(self, token_ids, **kwargs): ...
    def convert_tokens_to_string(self, tokens, **kwargs): ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...
    def __getstate__(self):  # -> dict[str, Any]:
        ...
    def __setstate__(self, d):  # -> None:
        ...

__all__ = ["FastSpeech2ConformerTokenizer"]
