from types import TracebackType
from typing import Self

class LivePanelDisplay:
    def __init__(self, msg: str | None = ...) -> None: ...
    def update(self, msg: str, add_sleep: float | None = ...):  # -> None:
        ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> None: ...
