import torch
from torch import nn

from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, ImageClassifierOutput
from ...modeling_utils import PreTrainedModel
from .configuration_timesformer import TimesformerConfig

"""PyTorch TimeSformer model."""
logger = ...

class TimesformerPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values):  # -> tuple[Any, Any, Any]:
        ...

class TimesformerEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values):  # -> Tensor | Any:
        ...

def drop_path(input: torch.Tensor, drop_prob: float = ..., training: bool = ...) -> torch.Tensor: ...

class TimeSformerDropPath(nn.Module):
    def __init__(self, drop_prob: float | None = ...) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class TimesformerSelfAttention(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(self, hidden_states, output_attentions: bool = ...):  # -> tuple[Any, Any] | tuple[Any]:
        ...

class TimesformerSelfOutput(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class TimeSformerAttention(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class TimesformerIntermediate(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class TimesformerOutput(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class TimesformerLayer(GradientCheckpointingLayer):
    def __init__(self, config: TimesformerConfig, layer_index: int) -> None: ...
    def forward(self, hidden_states: torch.Tensor, output_attentions: bool = ...):  # -> Any | None:
        ...

class TimesformerEncoder(nn.Module):
    def __init__(self, config: TimesformerConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ) -> tuple | BaseModelOutput: ...

class TimesformerPreTrainedModel(PreTrainedModel):
    config: TimesformerConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _no_split_modules = ...

class TimesformerModel(TimesformerPreTrainedModel):
    def __init__(self, config) -> None: ...
    def get_input_embeddings(self):  # -> TimesformerPatchEmbeddings:
        ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.FloatTensor] | BaseModelOutput: ...

class TimesformerForVideoClassification(TimesformerPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.Tensor | None = ...,
        labels: torch.Tensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | ImageClassifierOutput: ...

__all__ = ["TimesformerForVideoClassification", "TimesformerModel", "TimesformerPreTrainedModel"]
