
import torch
from torchaudio._internal.module_utils import deprecated, dropping_support

sox_ext = ...

@deprecated(...)
def init_sox_effects():  # -> None:
    ...
@deprecated(...)
def shutdown_sox_effects():  # -> None:
    ...
@dropping_support
def effect_names() -> list[str]: ...
@dropping_support
def apply_effects_tensor(
    tensor: torch.Tensor, sample_rate: int, effects: list[list[str]], channels_first: bool = ...
) -> tuple[torch.Tensor, int]: ...
@dropping_support
def apply_effects_file(
    path: str, effects: list[list[str]], normalize: bool = ..., channels_first: bool = ..., format: str | None = ...
) -> tuple[torch.Tensor, int]: ...
