from ...processing_utils import ProcessorMixin

"""Speech processor class for SpeechT5."""

class SpeechT5Processor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def __call__(self, *args, **kwargs):  # -> None:

        ...
    def pad(self, *args, **kwargs):  # -> None:

        ...
    def batch_decode(self, *args, **kwargs): ...
    def decode(self, *args, **kwargs): ...

__all__ = ["SpeechT5Processor"]
