from ...processing_utils import ProcessorMixin

"""
Image/Text processor class for XCLIP
"""

class XCLIPProcessor(ProcessorMixin):
    attributes = ...
    image_processor_class = ...
    tokenizer_class = ...
    def __init__(self, image_processor=..., tokenizer=..., **kwargs) -> None: ...
    def __call__(self, text=..., videos=..., return_tensors=..., **kwargs):  # -> BatchEncoding:

        ...
    def batch_decode(self, *args, **kwargs): ...
    def decode(self, *args, **kwargs): ...
    @property
    def model_input_names(self):  # -> list[str]:
        ...
    @property
    def feature_extractor_class(self):  # -> str:
        ...
    @property
    def feature_extractor(self): ...

__all__ = ["XCLIPProcessor"]
