from ...processing_utils import Unpack, VideosKwargs
from ...utils import is_vision_available
from ...utils.import_utils import requires
from ...video_processing_utils import BaseVideoProcessor

"""Video processor class for Video-LLaVA."""
if is_vision_available(): ...

class VideoLlavaFastVideoProcessorInitKwargs(VideosKwargs): ...

@requires(backends=("torchvision",))
class VideoLlavaVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_sample_frames = ...
    valid_kwargs = VideoLlavaFastVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[VideoLlavaFastVideoProcessorInitKwargs]) -> None: ...

__all__ = ["VideoLlavaVideoProcessor"]
