from torch._export.db.case import _EXAMPLE_CONFLICT_CASES, SupportLevel

def all_examples(): ...

if len(_EXAMPLE_CONFLICT_CASES) > 0:
    def get_name(case): ...

    msg = ...

def filter_examples_by_support_level(support_level: SupportLevel): ...
def get_rewrite_cases(case): ...
