import weakref
from enum import Enum
from typing import TYPE_CHECKING, Any

import torch
from torch.distributed._composable_state import _State

"""
This file includes private common utilities for FSDP.
"""
if TYPE_CHECKING: ...
FSDP_WRAPPED_MODULE = ...
FSDP_PREFIX = ...
FSDP_FLATTENED = ...
_MODULE_TO_INP_DTYPE: weakref.WeakKeyDictionary = ...

class _FSDPDeviceHandle:
    def __init__(self, device: torch.device, backend: Any = ...) -> None: ...
    @classmethod
    def from_device(cls, device: torch.device) -> _FSDPDeviceHandle: ...
    def __getattr__(self, name: str, /) -> Any: ...

class _UninitializedDeviceHandle(_FSDPDeviceHandle):
    def __init__(self) -> None: ...
    def __getattribute__(self, name: str, /) -> Any: ...

class _FSDPState(_State):
    def __init__(self) -> None: ...

class TrainingState(Enum):
    IDLE = ...
    FORWARD_BACKWARD = ...
    SUMMON_FULL_PARAMS = ...

class HandleTrainingState(Enum):
    IDLE = ...
    FORWARD = ...
    BACKWARD_PRE = ...
    BACKWARD_POST = ...
    SUMMON_FULL_PARAMS = ...

def clean_tensor_name(tensor_name: str) -> str: ...
