from dataclasses import dataclass
from typing import Any, override

from torch._inductor.utils import clear_on_fresh_cache

from ...autotune_process import TensorMeta
from ...ir import Buffer, IRNode, Layout
from ...utils import IndentedBuffer
from ..common import KernelTemplate
from .cuda_kernel import CUDATemplateCaller

type GemmOperation = Any
autotuning_log = ...

@dataclass(frozen=True)
class ArgInfo:
    name: str
    ty: str

@clear_on_fresh_cache
class CUDATemplate(KernelTemplate):
    index_counter = ...
    code_cache: dict[str, tuple[str, tuple[int, ...], tuple[int, ...]]] = ...
    cache_clear = ...
    def __init__(
        self, name: str, input_nodes: list[Buffer], layout: Layout, input_reorder: list[int] | None = ...
    ) -> None: ...
    @staticmethod
    def supports_epilogue_fusion(op: GemmOperation) -> bool: ...
    def make_key(self, name: str, input_key: str, layout_repr: str) -> str: ...
    def generate_code_and_args(
        self, name: str, input_key: str, layout_repr: str, **kwargs
    ) -> tuple[str, tuple[int, ...]]: ...
    def generate(
        self,
        name: str,
        description: str,
        input_key: str,
        layout_repr: str,
        input_tensor_meta: TensorMeta | list[TensorMeta],
        output_tensor_meta: TensorMeta | list[TensorMeta],
        **kwargs,
    ) -> CUDATemplateCaller: ...
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def render(self, **kwargs) -> str: ...
    def get_runtime_arg_info(self) -> list[ArgInfo]: ...
    def get_runtime_arg_values(self, **kwargs) -> list[Any]: ...

class CUTLASSTemplate(CUDATemplate):
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def cute_int(self, int_str: str, var_name: str) -> str: ...

    _DTYPE_TO_CUTLASS = ...
    _DTYPE_TO_CUTLASS_SPARSE_META = ...
    def cutlass_type_cast(self, node: IRNode, ptr: str) -> str: ...
    def cutlass_sparse_meta_type_cast(self, node: IRNode, ptr: str) -> str: ...
    @override
    def get_runtime_arg_info(self) -> list[ArgInfo]: ...
    @override
    def get_runtime_arg_values(self, **kwargs) -> list[Any]: ...
