from functools import cached_property
from typing import Any

import torch

from ..modeling_utils import PreTrainedModel
from ..utils import is_torch_available
from .base import HfQuantizer

if is_torch_available(): ...
logger = ...

class Bnb4BitHfQuantizer(HfQuantizer):
    use_keep_in_fp32_modules = ...
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def adjust_target_dtype(self, target_dtype: torch.dtype) -> torch.dtype: ...
    def check_quantized_param(
        self, model: PreTrainedModel, param_value: torch.Tensor, param_name: str, state_dict: dict[str, Any], **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        state_dict: dict[str, Any],
        unexpected_keys: list[str] | None = ...,
    ):  # -> None:

        ...
    def adjust_max_memory(self, max_memory: dict[str, int | str]) -> dict[str, int | str]: ...
    def update_torch_dtype(self, torch_dtype: torch.dtype) -> torch.dtype: ...
    def update_device_map(self, device_map):  # -> dict[str, int] | dict[str, str] | dict[str, Any]:
        ...
    def is_serializable(self, safe_serialization=...):  # -> bool:
        ...
    @cached_property
    def is_bnb_supports_quant_storage_module(self) -> bool: ...
    @property
    def is_trainable(self) -> bool: ...
