from typing import TYPE_CHECKING

import torch

from ..utils import is_torch_available
from ..utils.quantization_config import QuantizationConfigMixin
from .base import HfQuantizer

if TYPE_CHECKING: ...
if is_torch_available(): ...
logger = ...

class AutoRoundQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config: QuantizationConfigMixin, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_torch_dtype(self, torch_dtype: torch.dtype) -> torch.dtype: ...
    @property
    def is_trainable(self) -> bool: ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
