from typing import TYPE_CHECKING, Any

import torch

from ..modeling_utils import PreTrainedModel
from ..utils import is_torch_available
from .base import HfQuantizer

if TYPE_CHECKING: ...
if is_torch_available(): ...
logger = ...

class FbgemmFp8HfQuantizer(HfQuantizer):
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_torch_dtype(self, torch_dtype: torch.dtype) -> torch.dtype: ...
    def check_quantized_param(
        self, model: PreTrainedModel, param_value: torch.Tensor, param_name: str, state_dict: dict[str, Any], **kwargs
    ):  # -> bool:
        ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        state_dict: dict[str, Any],
        unexpected_keys: list[str] | None = ...,
    ):  # -> None:

        ...
    def update_missing_keys(self, model, missing_keys: list[str], prefix: str) -> list[str]: ...
    def update_tp_plan(self, config): ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
    @property
    def is_trainable(self) -> bool: ...
