from typing import Any

import torch

from ..modeling_utils import PreTrainedModel
from ..utils import is_torch_available
from ..utils.quantization_config import QuantizationConfigMixin
from .base import HfQuantizer

if is_torch_available(): ...
logger = ...

class FPQuantHfQuantizer(HfQuantizer):
    requires_calibration = ...
    requires_parameters_quantization = ...
    is_qat_trainable = ...
    required_packages = ...
    def __init__(self, quantization_config: QuantizationConfigMixin, **kwargs) -> None: ...
    def validate_environment(self, device_map, **kwargs):  # -> None:
        ...
    def update_torch_dtype(self, torch_dtype: torch.dtype) -> torch.dtype: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        state_dict: dict[str, Any],
        unexpected_keys: list[str] | None = ...,
    ):  # -> None:
        ...
    def update_missing_keys(self, model, missing_keys: list[str], prefix: str) -> list[str]: ...
    @property
    def is_trainable(self, model: PreTrainedModel | None = ...):  # -> Literal[False]:
        ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
    def check_quantized_param(
        self, model: PreTrainedModel, param_value: torch.Tensor, param_name: str, state_dict: dict[str, Any], **kwargs
    ) -> bool: ...
