from typing import TYPE_CHECKING, Any

import torch

from ..modeling_utils import PreTrainedModel
from ..utils import is_torch_available
from .base import HfQuantizer

if TYPE_CHECKING: ...
if is_torch_available(): ...
logger = ...

def fuzzy_match_size(config_name: str) -> str | None: ...
def find_parent(model, name): ...

class TorchAoHfQuantizer(HfQuantizer):
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_torch_dtype(self, torch_dtype):  # -> dtype:
        ...
    def adjust_target_dtype(self, torch_dtype: torch.dtype) -> torch.dtype: ...
    def adjust_max_memory(self, max_memory: dict[str, int | str]) -> dict[str, int | str]: ...
    def check_quantized_param(
        self, model: PreTrainedModel, param_value: torch.Tensor, param_name: str, state_dict: dict[str, Any], **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        state_dict: dict[str, Any],
        unexpected_keys: list[str],
    ):  # -> None:

        ...
    def is_serializable(self, safe_serialization=...) -> bool: ...
    def get_cuda_warm_up_factor(self):  # -> int:

        ...
    @property
    def is_trainable(self) -> bool: ...
    @property
    def is_compileable(self) -> bool: ...
