from collections.abc import Generator
from contextlib import contextmanager

def cache_dir() -> str: ...
def default_cache_dir() -> str: ...
def triton_cache_dir(device: int) -> str: ...
@contextmanager
def temporary_cache_dir(directory: str) -> Generator[None, None, None]: ...
