from collections.abc import Callable

from .triton_compat import triton

log = ...

def get_field(config, name): ...
def set_field(config, name, value): ...

class CoordescTuner:
    def __init__(self, is_mm=..., name=..., size_hints=..., inductor_meta=...) -> None: ...
    def get_config_max(self, prefix: str) -> int: ...
    def get_warpsmax(self): ...
    def cache_benchmark_result(self, config, timing): ...
    def lookup_in_cache(self, config): ...
    def call_func(self, func, config): ...
    @property
    def tunable_fields(self): ...
    def value_too_large(self, name: str, val: int) -> bool: ...
    def get_neighbour_values(self, name, orig_val, radius=..., include_self=...): ...
    @staticmethod
    def has_improvement(baseline, test): ...
    def check_all_tuning_directions(self, func: Callable[[triton.Config], float], best_config, best_timing): ...
    def compare_config(self, func, candidate_config, best_config, best_timing): ...
    def autotune(
        self,
        func: Callable[[triton.Config], float],
        baseline_config: triton.Config,
        baseline_timing: float | None = ...,
    ) -> triton.Config: ...
