import functools

import torch

log = ...
local = ...

class BufferMemoryTracker:
    """
    Tracks inductor runtime allocations and deallocations to compare against
    expected behavior.
    """
    def __init__(self) -> None: ...
    def set_tensor(self, name: str, tensor: torch.Tensor) -> None: ...
    def advance_step(self) -> None: ...
    def log_or_raise(self, msg: str) -> None: ...
    def check_step_delta(self, expected_allocated: list[str], expected_freed: list[str], is_final_step: bool) -> None:
        """Check only the delta changes since last step"""

def get_mem_tracker() -> BufferMemoryTracker: ...
def track_tensor(tensor: torch.Tensor, name: str) -> None: ...
def tracked_empty_strided(
    size: list[int], stride: list[int], *, dtype: torch.dtype, device: torch.device, name: str
) -> torch.Tensor: ...
def check_memory_step(allocated: list[str], freed: list[str], is_final_step: bool = ...) -> None: ...
@functools.lru_cache(None)
def register_check_mem_op() -> None: ...
