from typing import Any

logger = ...
console_handler = ...
formatter = ...

def get_fburl(url: str) -> str: ...
def get_strobelight_url(identifier: str) -> str: ...

class StrobelightCompileTimeProfiler:
    success_profile_count: int = ...
    failed_profile_count: int = ...
    ignored_profile_runs: int = ...
    inside_profile_compile_time: bool = ...
    enabled: bool = ...
    frame_id_filter: str | None = ...
    identifier: str | None = ...
    current_phase: str | None = ...
    profiler: Any | None = ...
    max_stack_length: int = ...
    max_profile_time: int = ...
    sample_each: int = ...
    @classmethod
    def get_frame(cls) -> str: ...
    @classmethod
    def enable(cls, profiler_class: Any = ...) -> None: ...
    @classmethod
    def profile_compile_time(cls, func: Any, phase_name: str, *args: Any, **kwargs: Any) -> Any: ...
