from typing import Any

from torch.types import _dtype

HAS_NUMPY = ...
__all__ = [
    "autocast",
    "autocast_decorator",
    "custom_bwd",
    "custom_fwd",
    "is_autocast_available",
]

def is_autocast_available(device_type: str) -> bool: ...
def autocast_decorator(autocast_instance, func) -> _Wrapped[..., Any, ..., Any]: ...

class autocast:
    def __init__(
        self,
        device_type: str,
        dtype: _dtype | None = ...,
        enabled: bool = ...,
        cache_enabled: bool | None = ...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Literal[False] | None: ...
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]: ...

def custom_fwd(
    fwd=..., *, device_type: str, cast_inputs: _dtype | None = ...
) -> partial[Any] | _Wrapped[..., Any, ..., Any]: ...
def custom_bwd(bwd=..., *, device_type: str) -> partial[Any] | _Wrapped[..., Any, ..., Any]: ...
