"""
Constants for annotations in the mapping.

The constants defined here are used to annotate the mapping tuples in cuda_to_hip_mappings.py.
They are based on
https://github.com/ROCm/HIPIFY/blob/master/src/Statistics.h
and fall in three categories: 1) type of mapping, 2) API of mapping, 3) unsupported
mapping.
"""

CONV_VERSION = ...
CONV_INIT = ...
CONV_DEVICE = ...
CONV_MEM = ...
CONV_KERN = ...
CONV_COORD_FUNC = ...
CONV_MATH_FUNC = ...
CONV_DEVICE_FUNC = ...
CONV_SPECIAL_FUNC = ...
CONV_STREAM = ...
CONV_EVENT = ...
CONV_OCCUPANCY = ...
CONV_CONTEXT = ...
CONV_PEER = ...
CONV_MODULE = ...
CONV_CACHE = ...
CONV_EXEC = ...
CONV_ERROR = ...
CONV_DEF = ...
CONV_TEX = ...
CONV_GL = ...
CONV_GRAPHICS = ...
CONV_SURFACE = ...
CONV_JIT = ...
CONV_D3D9 = ...
CONV_D3D10 = ...
CONV_D3D11 = ...
CONV_VDPAU = ...
CONV_EGL = ...
CONV_THREAD = ...
CONV_OTHER = ...
CONV_INCLUDE = ...
CONV_INCLUDE_CUDA_MAIN_H = ...
CONV_TYPE = ...
CONV_LITERAL = ...
CONV_NUMERIC_LITERAL = ...
CONV_LAST = ...
API_DRIVER = ...
API_RUNTIME = ...
API_BLAS = ...
API_SPECIAL = ...
API_RAND = ...
API_LAST = ...
API_FFT = ...
API_RTC = ...
API_ROCTX = ...
HIP_UNSUPPORTED = ...
API_PYTORCH = ...
API_CAFFE2 = ...
API_C10 = ...
API_ROCMSMI = ...
