__all__ = [
    "audio",
    "compute_curve",
    "custom_scalars",
    "draw_boxes",
    "half_to_int",
    "histogram",
    "histogram_raw",
    "hparams",
    "image",
    "image_boxes",
    "int_to_half",
    "make_histogram",
    "make_image",
    "make_video",
    "mesh",
    "pr_curve",
    "pr_curve_raw",
    "scalar",
    "tensor_proto",
    "text",
    "video",
]
logger = ...

def half_to_int(f: float) -> int: ...
def int_to_half(i: int) -> float: ...

_TENSOR_TYPE_MAP = ...

def hparams(hparam_dict=..., metric_dict=..., hparam_domain_discrete=...) -> tuple[Any, Any, Any]: ...
def scalar(name, tensor, collections=..., new_style=..., double_precision=...): ...
def tensor_proto(tag, tensor): ...
def histogram_raw(name, min, max, num, sum, sum_squares, bucket_limits, bucket_counts): ...
def histogram(name, values, bins, max_bins=...): ...
def make_histogram(values, bins, max_bins=...): ...
def image(tag, tensor, rescale=..., dataformats=...): ...
def image_boxes(tag, tensor_image, tensor_boxes, rescale=..., dataformats=..., labels=...): ...
def draw_boxes(disp_image, boxes, labels=...): ...
def make_image(tensor, rescale=..., rois=..., labels=...): ...
def video(tag, tensor, fps=...): ...
def make_video(tensor, fps) -> None: ...
def audio(tag, tensor, sample_rate=...): ...
def custom_scalars(layout): ...
def text(tag, text): ...
def pr_curve_raw(tag, tp, fp, tn, fn, precision, recall, num_thresholds=..., weights=...): ...
def pr_curve(tag, labels, predictions, num_thresholds=..., weights=...): ...
def compute_curve(labels, predictions, num_thresholds=..., weights=...) -> NDArray[float64]: ...
def mesh(tag, vertices, colors, faces, config_dict, display_name=..., description=...): ...
