import torch

from ...image_processing_utils_fast import BaseImageProcessorFast
from ...utils import is_torch_available, is_torchvision_available

"""Fast Image processor class for Perceiver."""
if is_torch_available(): ...
if is_torchvision_available(): ...

class PerceiverImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    def center_crop(
        self, image: torch.Tensor, crop_size: dict[str, int], size: dict[str, int], **kwargs
    ) -> torch.Tensor: ...

__all__ = ["PerceiverImageProcessorFast"]
