import torch.ao.nn.quantized as nnq

__all__ = ["Linear"]

class Linear(nnq.Linear):
    _version = ...
    def __init__(self, in_features, out_features, bias_=..., dtype=...) -> None: ...
    def forward(self, x) -> Any: ...
    def extra_repr(self) -> str: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> Self: ...
    @classmethod
    def from_reference(cls, ref_qlinear) -> Self: ...
