import torch

from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...image_utils import SizeDict
from ...utils import is_torch_available, is_torchvision_available

"""Fast Image processor class for Vilt."""
if is_torch_available(): ...
if is_torchvision_available(): ...
MAX_LONGER_EDGE = ...
MAX_SHORTER_EDGE = ...

class ViltFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_pad: bool | None
    size_divisor: int | None
    rescale_factor: float | None

class ViltImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    size_divisor = ...
    do_pad = ...
    default_to_square = ...
    model_input_names = ...
    valid_kwargs = ViltFastImageProcessorKwargs
    def resize(
        self,
        images: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        size_divisor: int | None = ...,
    ) -> torch.Tensor: ...

__all__ = ["ViltImageProcessorFast"]
