class Warning:
    def __init__(self, setter, getter) -> None: ...
    def set_enabled(self, value) -> None: ...
    def get_enabled(self): ...

    enabled = ...

broadcast_warning = ...
keepdim_warning = ...
