import contextlib

from torch._C import _SDPBackend as SDPBackend

"""This module contains functions and classes that alter the behavior of torch.nn.functional.scaled_dot_product_attention"""
__all__: list[str] = ...
WARN_FOR_UNFUSED_KERNELS = ...
SDPBackend = ...
_backend_names = ...

@contextlib.contextmanager
def sdpa_kernel(
    backends: list[SDPBackend] | SDPBackend, set_priority: bool = ...
) -> Generator[dict[Any, Any], Any, None]: ...
