class Color:
    all = ...
    def __init__(
        self,
        c50: str,
        c100: str,
        c200: str,
        c300: str,
        c400: str,
        c500: str,
        c600: str,
        c700: str,
        c800: str,
        c900: str,
        c950: str,
        name: str | None = ...,
    ) -> None: ...
    def expand(self) -> list[str]: ...

slate = ...
gray = ...
zinc = ...
neutral = ...
stone = ...
red = ...
orange = ...
amber = ...
yellow = ...
lime = ...
green = ...
emerald = ...
teal = ...
cyan = ...
sky = ...
blue = ...
indigo = ...
violet = ...
purple = ...
fuchsia = ...
pink = ...
rose = ...
