import json
from collections.abc import Iterable

class FontEncoder(json.JSONEncoder):
    def default(self, obj):  # -> dict[str, bool | str | Iterable[int] | None] | Any:
        ...

def as_font(dct):  # -> GoogleFont | LocalFont | Font:
    ...

class Font:
    def __init__(self, name: str) -> None: ...
    def stylesheet(self) -> dict: ...
    def __eq__(self, other: Font) -> bool: ...

class GoogleFont(Font):
    def __init__(self, name: str, weights: Iterable[int] = ...) -> None: ...
    def stylesheet(self) -> dict: ...

class LocalFont(Font):
    def __init__(self, name: str, weights: Iterable[int] = ...) -> None: ...
    def stylesheet(self) -> dict: ...
