from .utils import ExplicitEnum, is_torch_available

if is_torch_available(): ...
logger = ...

class DebugUnderflowOverflow:
    def __init__(self, model, max_frames_to_save=..., trace_batch_nums=..., abort_after_batch_num=...) -> None: ...
    def save_frame(self, frame=...):  # -> None:
        ...
    def expand_frame(self, line):  # -> None:
        ...
    def trace_frames(self):  # -> None:
        ...
    def reset_saved_frames(self):  # -> None:
        ...
    def dump_saved_frames(self):  # -> None:
        ...
    def analyse_model(self):  # -> None:
        ...
    def analyse_variable(self, var, ctx):  # -> None:
        ...
    def batch_start_frame(self):  # -> None:
        ...
    def batch_end_frame(self):  # -> None:
        ...
    def create_frame(self, module, input, output):  # -> None:
        ...
    def register_forward_hook(self):  # -> None:
        ...
    def forward_hook(self, module, input, output):  # -> None:
        ...

def get_abs_min_max(var, ctx):  # -> str:
    ...
def detect_overflow(var, ctx):  # -> bool:

    ...

class DebugOption(ExplicitEnum):
    UNDERFLOW_OVERFLOW = ...
    TPU_METRICS_DEBUG = ...
