import os
from collections import UserDict
from typing import Any, Self, TypeVar

import torch

from .utils import PushToHubMixin, TensorType

"""
Feature extraction saving/loading class for common feature extractors.
"""

type PreTrainedFeatureExtractor = SequenceFeatureExtractor
SpecificFeatureExtractorType = TypeVar("SpecificFeatureExtractorType", bound=FeatureExtractionMixin)

class BatchFeature[T](UserDict[str, T]):
    def __init__(self, data: dict[str, T] | None = ..., tensor_type: str | TensorType | None = ...) -> None: ...
    def __getitem__(self, item: str) -> T: ...
    def __getattr__(self, item: str): ...
    def __getstate__(self):  # -> dict[str, dict[Any, Any]]:
        ...
    def __setstate__(self, state):  # -> None:
        ...
    def convert_to_tensors(self, tensor_type: str | TensorType | None = ...):  # -> Self:
        ...
    def to(self, device: torch.device | str, dtype: torch.dtype | None = ..., *args: Any, **kwargs: Any) -> Self: ...

class FeatureExtractionMixin(PushToHubMixin):
    _auto_class = ...
    def __init__(self, **kwargs) -> None: ...
    @classmethod
    def from_pretrained(
        cls,
        pretrained_model_name_or_path: str | os.PathLike[str],
        cache_dir: str | os.PathLike[str] | None = ...,
        force_download: bool = ...,
        local_files_only: bool = ...,
        token: str | bool | None = ...,
        revision: str = ...,
        **kwargs: Any,
    ) -> Self: ...
    def save_pretrained(self, save_directory: str | os.PathLike, push_to_hub: bool = ..., **kwargs):  # -> list[str]:
        ...
    @classmethod
    def get_feature_extractor_dict(
        cls, pretrained_model_name_or_path: str | os.PathLike, **kwargs
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
    @classmethod
    def from_dict(cls, feature_extractor_dict: dict[str, Any], **kwargs) -> PreTrainedFeatureExtractor: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_json_file(cls, json_file: str | os.PathLike) -> PreTrainedFeatureExtractor: ...
    def to_json_string(self) -> str: ...
    def to_json_file(self, json_file_path: str | os.PathLike):  # -> None:
        ...
    @classmethod
    def register_for_auto_class(cls, auto_class=...):  # -> None:
        ...

if FeatureExtractionMixin.push_to_hub.__doc__ is not None: ...
