import flax
import jax.numpy as jnp

from .utils import ModelOutput

@flax.struct.dataclass
class FlaxBaseModelOutput(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithNoAttention(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithPoolingAndNoAttention(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    pooler_output: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxImageClassifierOutputWithNoAttention(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithPast(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    past_key_values: dict[str, jnp.ndarray] | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithPooling(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    pooler_output: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithPoolingAndCrossAttentions(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    pooler_output: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxBaseModelOutputWithPastAndCrossAttentions(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxSeq2SeqModelOutput(ModelOutput):
    last_hidden_state: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    decoder_hidden_states: tuple[jnp.ndarray] | None = ...
    decoder_attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...
    encoder_last_hidden_state: jnp.ndarray | None = ...
    encoder_hidden_states: tuple[jnp.ndarray] | None = ...
    encoder_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxCausalLMOutputWithCrossAttentions(ModelOutput):
    logits: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxMaskedLMOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

FlaxCausalLMOutput = FlaxMaskedLMOutput

@flax.struct.dataclass
class FlaxSeq2SeqLMOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    decoder_hidden_states: tuple[jnp.ndarray] | None = ...
    decoder_attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...
    encoder_last_hidden_state: jnp.ndarray | None = ...
    encoder_hidden_states: tuple[jnp.ndarray] | None = ...
    encoder_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxNextSentencePredictorOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxSequenceClassifierOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxSeq2SeqSequenceClassifierOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    decoder_hidden_states: tuple[jnp.ndarray] | None = ...
    decoder_attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...
    encoder_last_hidden_state: jnp.ndarray | None = ...
    encoder_hidden_states: tuple[jnp.ndarray] | None = ...
    encoder_attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxMultipleChoiceModelOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxTokenClassifierOutput(ModelOutput):
    logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxQuestionAnsweringModelOutput(ModelOutput):
    start_logits: jnp.ndarray | None = ...
    end_logits: jnp.ndarray | None = ...
    hidden_states: tuple[jnp.ndarray] | None = ...
    attentions: tuple[jnp.ndarray] | None = ...

@flax.struct.dataclass
class FlaxSeq2SeqQuestionAnsweringModelOutput(ModelOutput):
    start_logits: jnp.ndarray | None = ...
    end_logits: jnp.ndarray | None = ...
    past_key_values: tuple[tuple[jnp.ndarray]] | None = ...
    decoder_hidden_states: tuple[jnp.ndarray] | None = ...
    decoder_attentions: tuple[jnp.ndarray] | None = ...
    cross_attentions: tuple[jnp.ndarray] | None = ...
    encoder_last_hidden_state: jnp.ndarray | None = ...
    encoder_hidden_states: tuple[jnp.ndarray] | None = ...
    encoder_attentions: tuple[jnp.ndarray] | None = ...
