from dataclasses import dataclass
from pathlib import Path

from .generation.configuration_utils import GenerationConfig
from .training_args import TrainingArguments
from .utils import add_start_docstrings

logger = ...

@dataclass
@add_start_docstrings(TrainingArguments.__doc__)
class Seq2SeqTrainingArguments(TrainingArguments):
    sortish_sampler: bool = ...
    predict_with_generate: bool = ...
    generation_max_length: int | None = ...
    generation_num_beams: int | None = ...
    generation_config: str | Path | GenerationConfig | None = ...
    def to_dict(self):  # -> dict[str, Any]:

        ...
