import os
from typing import Any

import torch

from .image_processing_utils import BatchFeature
from .image_processing_utils_fast import BaseImageProcessorFast
from .processing_utils import Unpack, VideosKwargs
from .utils import add_start_docstrings, is_torch_available, is_torchvision_available, is_vision_available
from .utils.import_utils import requires
from .video_utils import VideoInput, VideoMetadata

if is_vision_available(): ...
if is_torch_available(): ...
if is_torchvision_available(): ...
logger = ...
BASE_VIDEO_PROCESSOR_DOCSTRING = ...

@add_start_docstrings("Constructs a base VideoProcessor.", BASE_VIDEO_PROCESSOR_DOCSTRING)
@requires(backends=("vision", "torchvision"))
class BaseVideoProcessor(BaseImageProcessorFast):
    _auto_class = ...
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    size_divisor = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_pad = ...
    do_rescale = ...
    rescale_factor = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_sample_frames = ...
    fps = ...
    num_frames = ...
    video_metadata = ...
    valid_kwargs = VideosKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[VideosKwargs]) -> None: ...
    def __call__(self, videos, **kwargs) -> BatchFeature: ...
    def convert_to_rgb(self, video: torch.Tensor) -> VideoInput: ...
    def sample_frames(
        self,
        video: torch.Tensor,
        metadata: VideoMetadata | dict | None = ...,
        num_frames: int | None = ...,
        fps: float | None = ...,
    ):  # -> Tensor:

        ...
    @add_start_docstrings(BASE_VIDEO_PROCESSOR_DOCSTRING)
    def preprocess(self, videos: VideoInput, **kwargs: Unpack[VideosKwargs]) -> BatchFeature: ...
    @classmethod
    def from_pretrained(
        cls,
        pretrained_model_name_or_path: str | os.PathLike,
        cache_dir: str | os.PathLike | None = ...,
        force_download: bool = ...,
        local_files_only: bool = ...,
        token: str | bool | None = ...,
        revision: str = ...,
        **kwargs,
    ):  # -> tuple[Self, dict[str, Any]] | Self:

        ...
    def save_pretrained(self, save_directory: str | os.PathLike, push_to_hub: bool = ..., **kwargs):  # -> list[str]:

        ...
    @classmethod
    def get_video_processor_dict(
        cls, pretrained_model_name_or_path: str | os.PathLike, **kwargs
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
    @classmethod
    def from_dict(cls, video_processor_dict: dict[str, Any], **kwargs):  # -> tuple[Self, dict[str, Any]] | Self:

        ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json_string(self) -> str: ...
    def to_json_file(self, json_file_path: str | os.PathLike):  # -> None:

        ...
    @classmethod
    def from_json_file(cls, json_file: str | os.PathLike):  # -> Self:

        ...
    @classmethod
    def register_for_auto_class(cls, auto_class=...):  # -> None:

        ...
    def fetch_videos(self, video_url_or_urls: str | list[str]):  # -> list[list[list[Any] | Any] | Any]:

        ...

if BaseVideoProcessor.push_to_hub.__doc__ is not None: ...
