from typing import Any

from ...tokenization_utils import PreTrainedTokenizer
from ...utils.import_utils import requires

SPIECE_UNDERLINE = ...
VOCAB_FILES_NAMES = ...
logger = ...

@requires(backends=("sentencepiece",))
class PegasusTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self,
        vocab_file,
        pad_token=...,
        eos_token=...,
        unk_token=...,
        mask_token=...,
        mask_token_sent=...,
        additional_special_tokens=...,
        offset=...,
        sp_model_kwargs: dict[str, Any] | None = ...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self) -> int: ...
    def get_vocab(self) -> dict[str, int]: ...
    def __getstate__(self):  # -> dict[str, Any]:
        ...
    def __setstate__(self, d):  # -> None:
        ...
    def convert_tokens_to_string(self, tokens): ...
    def num_special_tokens_to_add(self, pair=...):  # -> Literal[1]:

        ...
    def get_special_tokens_mask(
        self, token_ids_0: list, token_ids_1: list | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=...) -> list[int]: ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["PegasusTokenizer"]
