THRESHOLD = ...

def conv_picker(func, conv1dOpt, conv2dOpt, conv3dOpt): ...
def conv_args_and_kwargs(
    kwarg_names, expanded_args_and_kwargs
):  # -> tuple[tuple[Any, Any], dict[str, Any | int | None]]:
    ...
def conv_normalizer(
    input, weight, bias=..., stride=..., padding=..., dilation=..., groups=...
):  # -> tuple[tuple[Any, Any], dict[str, Any | int | None]]:
    ...
def conv_input_for_string_padding(func, padding_style, input, dilation, kernel_size): ...
def int_padding_for_string_padding(func, padding_style, dilation, kernel_size):  # -> list[int]:
    ...
def conv_padding_for_same(dilation, kernel_size):  # -> tuple[Any, Any]:
    ...
def conv_backward(func, ctx, grad_output):  # -> tuple[Tensor | None, ...]:
    ...
def conv_unfold_weight_grad_sample(
    input, grad_output, weight_shape, kernel_size, stride, padding, dilation, groups, func
):  # -> Tensor:
    ...
def conv_group_weight_grad_sample(input, grad_output, weight_shape, stride, padding, dilation, batch_size, func): ...
def unfold3d(tensor, kernel_size, padding, stride, dilation): ...
