from dataclasses import dataclass
from enum import Enum

from torch.distributed.tensor import DeviceMesh

_compiled_autograd_enabled: bool = ...

def detect_compiled_autograd(): ...
def compiled_autograd_enabled(): ...

@dataclass
class DataParallelMeshInfo:
    mesh: DeviceMesh
    shard_mesh_dim: int | None = ...
    replicate_mesh_dim: int | None = ...
    def __post_init__(self): ...

@dataclass
class FSDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): ...

@dataclass
class DDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): ...

@dataclass
class HSDPMeshInfo(FSDPMeshInfo, DDPMeshInfo):
    def __post_init__(self): ...

class TrainingState(Enum):
    FORWARD = ...
    PRE_BACKWARD = ...
    POST_BACKWARD = ...
    IDLE = ...
