from collections.abc import Callable, Iterable
from typing import Any, ParamSpec, TypeVar

import torch

log = ...
P = ParamSpec("P")
R = TypeVar("R")

class AotAutograd:
    def __init__(self, **kwargs: Any) -> None: ...
    def __call__(
        self, gm: torch.fx.GraphModule, example_inputs: Iterable[Any], **kwargs: Any
    ) -> Callable[..., Any]: ...

def aot_autograd(**kwargs: Any) -> AotAutograd: ...
def mem_efficient_fusion_kwargs(use_decomps: bool) -> dict[str, Any]: ...
def fake_tensor_unsupported[R](fn: Callable[[Any, list[Any], Any], R]) -> Any: ...
def device_from_inputs(example_inputs: Iterable[Any]) -> torch.device: ...
def dtype_from_inputs(example_inputs: Iterable[Any]) -> torch.dtype: ...
