from contextvars import ContextVar
from typing import TYPE_CHECKING

from gradio.blocks import BlockContext, Blocks, BlocksConfig
from gradio.helpers import Progress
from gradio.renderable import Renderable
from gradio.routes import Request

if TYPE_CHECKING: ...

class Context:
    root_block: Blocks | None = ...
    block: BlockContext | None = ...
    id: int = ...
    token: str | None = ...

class LocalContext:
    blocks: ContextVar[Blocks | None] = ...
    blocks_config: ContextVar[BlocksConfig | None] = ...
    renderable: ContextVar[Renderable | None] = ...
    render_block: ContextVar[BlockContext | None] = ...
    in_event_listener: ContextVar[bool] = ...
    event_id: ContextVar[str | None] = ...
    request: ContextVar[Request | None] = ...
    progress: ContextVar[Progress | None] = ...
    key_to_id_map: ContextVar[dict[int | str | tuple[str | int, ...], int] | None] = ...

def get_render_context() -> BlockContext | None: ...
def set_render_context(block: BlockContext | None):  # -> None:
    ...
def get_blocks_context() -> BlocksConfig | None: ...
