from gradio_client.documentation import document
from gradio_client.exceptions import AppError

class DuplicateBlockError(ValueError): ...
class InvalidComponentError(ValueError): ...
class ModelNotFoundError(Exception): ...
class RenderError(Exception): ...
class InvalidApiNameError(ValueError): ...
class ServerFailedToStartError(Exception): ...
class InvalidBlockError(ValueError): ...
class ReloadError(ValueError): ...
class GradioVersionIncompatibleError(Exception): ...

InvalidApiName = InvalidApiNameError

@document(documentation_group="modals")
class Error(AppError):
    def __init__(
        self,
        message: str = ...,
        duration: float | None = ...,
        visible: bool = ...,
        title: str = ...,
        print_exception: bool = ...,
    ) -> None: ...

class ComponentDefinitionError(NotImplementedError): ...
class InvalidPathError(ValueError): ...
class ChecksumMismatchError(Exception): ...

class TooManyRequestsError(Error):
    def __init__(self, message: str = ...) -> None: ...
