from abc import ABC, abstractmethod
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

import gradio as gr
from gradio.components import Component
from gradio.events import LikeData
from gradio_client.documentation import document

if TYPE_CHECKING: ...

class FlaggingCallback(ABC):
    @abstractmethod
    def setup(self, components: Sequence[Component], flagging_dir: str):  # -> None:

        ...
    @abstractmethod
    def flag(self, flag_data: list[Any], flag_option: str | None = ..., username: str | None = ...) -> int: ...

@document()
class SimpleCSVLogger(FlaggingCallback):
    def __init__(self) -> None: ...
    def setup(self, components: Sequence[Component], flagging_dir: str | Path):  # -> None:
        ...
    def flag(self, flag_data: list[Any], flag_option: str | None = ..., username: str | None = ...) -> int: ...

@document()
class ClassicCSVLogger(FlaggingCallback):
    def __init__(self, simplify_file_data: bool = ...) -> None: ...
    def setup(self, components: Sequence[Component], flagging_dir: str | Path):  # -> None:
        ...
    def flag(self, flag_data: list[Any], flag_option: str | None = ..., username: str | None = ...) -> int: ...

@document()
class CSVLogger(FlaggingCallback):
    def __init__(
        self, simplify_file_data: bool = ..., verbose: bool = ..., dataset_file_name: str | None = ...
    ) -> None: ...
    def setup(self, components: Sequence[Component], flagging_dir: str | Path):  # -> None:
        ...
    def flag(self, flag_data: list[Any], flag_option: str | None = ..., username: str | None = ...) -> int: ...

class ChatCSVLogger:
    def __init__(self) -> None: ...
    def setup(self, flagging_dir: str):  # -> None:
        ...
    def flag(self, like_data: LikeData, messages: list):  # -> None:
        ...

class FlagMethod:
    def __init__(
        self, flagging_callback: FlaggingCallback, label: str, value: str | None, visual_feedback: bool = ...
    ) -> None: ...
    def __call__(self, request: gr.Request, *flag_data):  # -> Button | Literal['Error!'] | None:
        ...
    def reset(self):  # -> Button:
        ...
