MEDIA_ROOT = ...
MEDIA_PATHS = ...

def get_image(filename: str | None = ...) -> str: ...
def get_video(filename: str | None = ...) -> str: ...
def get_audio(filename: str | None = ...) -> str: ...
def get_model3d(filename: str | None = ...) -> str: ...
def get_file(filename: str | None = ...) -> str: ...
