from collections import UserString, deque
from collections.abc import AsyncGenerator, Callable
from contextlib import AbstractAsyncContextManager
from dataclasses import dataclass as python_dataclass
from typing import Any, BinaryIO

import fastapi
import httpx
from gradio.blocks import BlockFunction, Blocks, BlocksConfig
from gradio.data_classes import BlocksConfigDict, MediaStreamChunk, PredictBody, PredictBodyInternal
from gradio.helpers import EventData
from gradio.routes import App
from gradio_client.documentation import document
from starlette.datastructures import FormData, Headers, MutableHeaders, UploadFile
from starlette.responses import Response
from starlette.types import ASGIApp, Receive, Scope, Send

config_lock = ...
API_PREFIX = ...

class Obj:
    def __init__(self, dict_) -> None: ...
    def __getitem__(self, item):  # -> Any:
        ...
    def __setitem__(self, item, value) -> None:  # -> None:
        ...
    def __iter__(self):  # -> Generator[tuple[str, dict[str, Any]] | tuple[str, Any], Any, None]:
        ...
    def __contains__(self, item) -> bool: ...
    def get(self, item, default=...):  # -> Any | None:
        ...
    def keys(self):  # -> dict_keys[str, Any]:
        ...
    def values(self):  # -> dict_values[str, Any]:
        ...
    def items(self):  # -> dict_items[str, Any]:
        ...
    def pop(self, item, default=...):  # -> Any | None:
        ...

@document()
class Request:
    def __init__(
        self,
        request: fastapi.Request | None = ...,
        username: str | None = ...,
        session_hash: str | None = ...,
        **kwargs,
    ) -> None: ...
    def dict_to_obj(self, d):  # -> Any:
        ...
    def __getattr__(self, name: str):  # -> Any:
        ...
    def __getstate__(self) -> dict[str, Any]: ...
    def __setstate__(self, state: dict[str, Any]):  # -> None:
        ...

@document()
class Header(UserString): ...

class FnIndexInferError(Exception): ...

def get_fn(blocks: Blocks, api_name: str | None, body: PredictBody) -> BlockFunction: ...
def compile_gr_request(
    body: PredictBodyInternal, fn: BlockFunction, username: str | None, request: fastapi.Request | None
):  # -> list[Request] | Request:
    ...
def restore_session_state(app: App, body: PredictBodyInternal):  # -> tuple[SessionState, AsyncIterator[Any] | None]:
    ...
def prepare_event_data(blocks_config: BlocksConfig, body: PredictBodyInternal) -> EventData: ...
async def call_process_api(
    app: App, body: PredictBodyInternal, gr_request: Request | list[Request], fn: BlockFunction, root_path: str
):  # -> dict[str, Any]:
    ...
def get_first_header_value(request: fastapi.Request, header_name: str):  # -> str | None:
    ...
def get_request_origin(request: fastapi.Request, route_path: str) -> httpx.URL: ...
def get_api_call_path(request: fastapi.Request) -> str: ...
def get_root_url(request: fastapi.Request, route_path: str, root_path: str | None) -> str: ...

class GradioUploadFile(UploadFile):
    def __init__(
        self, file: BinaryIO, *, size: int | None = ..., filename: str | None = ..., headers: Headers | None = ...
    ) -> None: ...

@python_dataclass(frozen=True)
class FileUploadProgressUnit:
    filename: str
    chunk_size: int

@python_dataclass
class FileUploadProgressTracker:
    deque: deque[FileUploadProgressUnit]
    is_done: bool

class FileUploadProgressNotTrackedError(Exception): ...
class FileUploadProgressNotQueuedError(Exception): ...

class FileUploadProgress:
    def __init__(self) -> None: ...
    def track(self, upload_id: str):  # -> None:
        ...
    async def is_tracked(self, upload_id: str) -> bool: ...
    def append(self, upload_id: str, filename: str, message_bytes: bytes):  # -> None:
        ...
    def set_done(self, upload_id: str):  # -> None:
        ...
    def is_done(self, upload_id: str):  # -> bool:
        ...
    def stop_tracking(self, upload_id: str):  # -> None:
        ...
    def pop(self, upload_id: str) -> FileUploadProgressUnit: ...

class GradioMultiPartParser:
    max_header_size = ...
    def __init__(
        self,
        headers: Headers,
        stream: AsyncGenerator[bytes],
        *,
        max_files: float = ...,
        max_fields: float = ...,
        upload_id: str | None = ...,
        upload_progress: FileUploadProgress | None = ...,
        max_file_size: float,
        max_header_size: int = ...,
    ) -> None: ...
    def on_part_begin(self) -> None: ...
    def on_part_data(self, data: bytes, start: int, end: int) -> None: ...
    def on_part_end(self) -> None: ...
    def on_header_field(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_value(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_end(self) -> None: ...
    def on_headers_finished(self) -> None: ...
    def on_end(self) -> None: ...
    async def parse(self) -> FormData: ...

def move_uploaded_files_to_cache(files: list[str], destinations: list[str]) -> None: ...
def update_root_in_config(config: BlocksConfigDict, root: str) -> BlocksConfigDict: ...
def update_example_values_to_use_public_url(api_info: dict[str, Any]) -> dict[str, Any]: ...
def compare_passwords_securely(input_password: str, correct_password: str) -> bool: ...
def starts_with_protocol(string: str) -> bool: ...
def get_hostname(url: str) -> str: ...

class CustomCORSMiddleware:
    def __init__(self, app: ASGIApp, strict_cors: bool = ...) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    def preflight_response(self, request_headers: Headers) -> Response: ...
    async def simple_response(self, scope: Scope, receive: Receive, send: Send, request_headers: Headers) -> None: ...
    def is_valid_origin(self, request_headers: Headers) -> bool: ...
    @staticmethod
    def allow_explicit_origin(headers: MutableHeaders, origin: str) -> None: ...

def delete_files_created_by_app(blocks: Blocks, age: int | None) -> None: ...
async def delete_files_on_schedule(app: App, frequency: int, age: int) -> None: ...
def create_lifespan_handler(
    user_lifespan: Callable[[App], AbstractAsyncContextManager] | None,
    frequency: int | None = ...,
    age: int | None = ...,
) -> Callable[[App], AbstractAsyncContextManager]: ...

class MediaStream:
    def __init__(self, desired_output_format: str | None = ...) -> None: ...
    async def add_segment(self, data: MediaStreamChunk | None):  # -> None:
        ...
    def end_stream(self):  # -> None:
        ...

def create_url_safe_hash(data: bytes, digest_size=...):  # -> str:

    ...
def slugify(value):  # -> str:

    ...
