from collections.abc import Generator

import torch
from torch._C._distributed_c10d import Store

from .api import *

__all__ = ["is_available"]
logger = ...
_init_counter = ...
_init_counter_lock = ...

def is_available() -> bool: ...

if is_available() and not torch._C._rpc_init(): ...
if is_available():
    _is_tensorpipe_available = ...
    rendezvous_iterator: Generator[tuple[Store, int, int]]
    def init_rpc(name, backend=..., rank=..., world_size=..., rpc_backend_options=...) -> None: ...
