from torch.autograd.profiler_legacy import profile

__all__: list[str] = ...

class _server_process_global_profile(profile):
    def __init__(self, *args, **kwargs) -> None: ...
    def __enter__(self) -> Self | None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> Literal[False] | None: ...
