from ...image_processing_utils_fast import BaseImageProcessorFast, BatchFeature, DefaultFastImageProcessorKwargs
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import is_torch_available, is_torchvision_available

"""Fast Image processor class for LayoutLMv3."""
logger = ...
if is_torch_available(): ...
if is_torchvision_available(): ...

class LayoutLMv3FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    apply_ocr: bool | None
    ocr_lang: str | None
    tesseract_config: str | None

class LayoutLMv3ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    apply_ocr = ...
    ocr_lang = ...
    tesseract_config = ...
    valid_kwargs = LayoutLMv3FastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[LayoutLMv3FastImageProcessorKwargs]) -> None: ...
    def preprocess(self, images: ImageInput, **kwargs: Unpack[LayoutLMv3FastImageProcessorKwargs]) -> BatchFeature: ...

__all__ = ["LayoutLMv3ImageProcessorFast"]
