"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from ...utils import _LazyModule
from ...utils.import_utils import define_import_structure
from .configuration_trocr import *
from .modeling_trocr import *
from .processing_trocr import *

if TYPE_CHECKING: ...
else: ...
