from typing import Any

import torch
from torch import Tensor, nn
from transformers import PreTrainedModel
from transformers.modeling_outputs import (
    BackboneOutput,
    BaseModelOutputWithNoAttention,
    BaseModelOutputWithPoolingAndNoAttention,
    ImageClassifierOutputWithNoAttention,
)
from transformers.models.textnet.configuration_textnet import TextNetConfig
from transformers.utils.backbone_utils import BackboneMixin

"""PyTorch TextNet model."""
logger = ...

class TextNetConvLayer(nn.Module):
    def __init__(self, config: TextNetConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class TextNetRepConvLayer(nn.Module):
    def __init__(
        self, config: TextNetConfig, in_channels: int, out_channels: int, kernel_size: int, stride: int
    ) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class TextNetStage(nn.Module):
    def __init__(self, config: TextNetConfig, depth: int) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class TextNetEncoder(nn.Module):
    def __init__(self, config: TextNetConfig) -> None: ...
    def forward(
        self, hidden_state: torch.Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> BaseModelOutputWithNoAttention: ...

class TextNetPreTrainedModel(PreTrainedModel):
    config: TextNetConfig
    base_model_prefix = ...
    main_input_name = ...

class TextNetModel(TextNetPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> tuple[Any, list[Any]] | tuple[Any] | BaseModelOutputWithPoolingAndNoAttention: ...

class TextNetForImageClassification(TextNetPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> ImageClassifierOutputWithNoAttention: ...

class TextNetBackbone(TextNetPreTrainedModel, BackboneMixin):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: Tensor, output_hidden_states: bool | None = ..., return_dict: bool | None = ...
    ) -> tuple[tuple] | BackboneOutput: ...

__all__ = ["TextNetBackbone", "TextNetForImageClassification", "TextNetModel", "TextNetPreTrainedModel"]
