import torch

from ...image_processing_utils_fast import BaseImageProcessorFast, SizeDict
from ...utils import is_torch_available, is_torchvision_available

"""Fast Image processor class for LeViT."""
if is_torch_available(): ...
if is_torchvision_available(): ...

class LevitImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    def resize(
        self, image: torch.Tensor, size: SizeDict, interpolation: F.InterpolationMode = ..., **kwargs
    ) -> torch.Tensor: ...

__all__ = ["LevitImageProcessorFast"]
