from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for BERTweet"""
logger = ...
VOCAB_FILES_NAMES = ...

def get_pairs(word):  # -> set[Any]:

    ...

class BertweetTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    def __init__(
        self,
        vocab_file,
        merges_file,
        normalization=...,
        bos_token=...,
        eos_token=...,
        sep_token=...,
        cls_token=...,
        unk_token=...,
        pad_token=...,
        mask_token=...,
        **kwargs,
    ) -> None: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def bpe(self, token):  # -> LiteralString:
        ...
    def normalizeTweet(self, tweet):  # -> str:

        ...
    def normalizeToken(self, token):  # -> str:

        ...
    def convert_tokens_to_string(self, tokens):  # -> str:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...
    def add_from_file(self, f):  # -> None:

        ...

EMOTICONS = ...
URLS = ...
REGEXPS = ...
WORD_RE = ...
HANG_RE = ...
EMOTICON_RE = ...
ENT_RE = ...

class TweetTokenizer:
    def __init__(self, preserve_case=..., reduce_len=..., strip_handles=...) -> None: ...
    def tokenize(self, text):  # -> list[Any]:

        ...

def reduce_lengthening(text):  # -> str:

    ...
def remove_handles(text):  # -> str:

    ...
def casual_tokenize(text, preserve_case=..., reduce_len=..., strip_handles=...):  # -> list[Any]:

    ...

__all__ = ["BertweetTokenizer"]
