from dataclasses import dataclass

import torch
from torch import nn

from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, DepthEstimatorOutput, SemanticSegmenterOutput
from ...modeling_utils import PreTrainedModel
from ...utils import ModelOutput
from .configuration_dpt import DPTConfig

"""PyTorch DPT (Dense Prediction Transformers) model.

This implementation is heavily inspired by OpenMMLab's implementation, found here:
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/dpt_head.py.

"""
logger = ...

@dataclass
class BaseModelOutputWithIntermediateActivations(ModelOutput):
    last_hidden_states: torch.FloatTensor | None = ...
    intermediate_activations: tuple[torch.FloatTensor, ...] | None = ...

@dataclass
class BaseModelOutputWithPoolingAndIntermediateActivations(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    pooler_output: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor, ...] | None = ...
    attentions: tuple[torch.FloatTensor, ...] | None = ...
    intermediate_activations: tuple[torch.FloatTensor, ...] | None = ...

class DPTViTHybridEmbeddings(nn.Module):
    def __init__(self, config, feature_size=...) -> None: ...
    def forward(
        self, pixel_values: torch.Tensor, interpolate_pos_encoding: bool = ..., return_dict: bool = ...
    ) -> torch.Tensor: ...

class DPTViTEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values, return_dict=...):  # -> tuple[Any] | BaseModelOutputWithIntermediateActivations:
        ...

class DPTViTPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values):  # -> Any:
        ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class DPTSelfAttention(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class DPTViTSelfOutput(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class DPTViTAttention(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def prune_heads(self, heads: set[int]) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class DPTViTIntermediate(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class DPTViTOutput(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor: ...

class DPTViTLayer(GradientCheckpointingLayer):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ..., output_attentions: bool = ...
    ) -> tuple[torch.Tensor, torch.Tensor] | tuple[torch.Tensor]: ...

class DPTViTEncoder(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        head_mask: torch.Tensor | None = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ) -> tuple | BaseModelOutput: ...

class DPTReassembleStage(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor], patch_height=..., patch_width=...) -> list[torch.Tensor]: ...

class DPTReassembleLayer(nn.Module):
    def __init__(self, config, channels, factor) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class DPTFeatureFusionStage(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states):  # -> list[Any]:
        ...

class DPTPreActResidualLayer(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...

class DPTFeatureFusionLayer(nn.Module):
    def __init__(self, config, align_corners=...) -> None: ...
    def forward(self, hidden_state, residual=...):  # -> Any:
        ...

class DPTPreTrainedModel(PreTrainedModel):
    config: DPTConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...

class DPTModel(DPTPreTrainedModel):
    def __init__(self, config, add_pooling_layer=...) -> None: ...
    def get_input_embeddings(
        self,
    ):  # -> DPTViTHybridEmbeddings | DPTViTEmbeddings | Tensor | Module | DPTViTPatchEmbeddings:
        ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        head_mask: torch.FloatTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | BaseModelOutputWithPoolingAndIntermediateActivations: ...

class DPTViTPooler(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states): ...

class DPTNeck(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor], patch_height=..., patch_width=...) -> list[torch.Tensor]: ...

class DPTDepthEstimationHead(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor]) -> torch.Tensor: ...

class DPTForDepthEstimation(DPTPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        head_mask: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.Tensor] | DepthEstimatorOutput: ...

class DPTSemanticSegmentationHead(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor]) -> torch.Tensor: ...

class DPTAuxiliaryHead(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states):  # -> Any:
        ...

class DPTForSemanticSegmentation(DPTPreTrainedModel):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        head_mask: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.Tensor] | SemanticSegmenterOutput: ...

__all__ = ["DPTForDepthEstimation", "DPTForSemanticSegmentation", "DPTModel", "DPTPreTrainedModel"]
