from typing import TYPE_CHECKING

from torch._C._monitor import *
from torch.utils.tensorboard import SummaryWriter

if TYPE_CHECKING: ...
STAT_EVENT = ...

class TensorboardEventHandler:
    def __init__(self, writer: SummaryWriter) -> None: ...
    def __call__(self, event: Event) -> None: ...
