from torch.fx.graph_module import GraphModule
from torch.package import PackageExporter

from ._compatibility import compatibility

_use_lazy_graph_module_flag = ...
_force_skip_lazy_graph_module_flag = ...

@compatibility(is_backward_compatible=False)
class _LazyGraphModule(GraphModule):
    @classmethod
    def from_graphmodule(cls, gm: GraphModule): ...
    @staticmethod
    def force_recompile(gm): ...
    def real_recompile(self): ...

    forward = ...
    def __reduce_package__(self, exporter: PackageExporter): ...
    def __reduce__(self): ...
    @classmethod
    def recompile(cls): ...
    @property
    def code(self) -> str: ...
