import torch
from typing import Optional

def lazy_format_graph_code(name, gm, maybe_id=..., **kwargs):  # -> LazyString[[]]:

    ...
def first_call_function_nn_module_stack(graph: torch.fx.Graph) -> Optional[dict]: ...
def get_node_context(node, num_nodes=...) -> str: ...
