import os
from typing import Any

import torch
from torch.package import PackageExporter, PackageImporter

from ._compatibility import compatibility
from .graph import Graph, PythonCode

__all__ = ["GraphModule", "reduce_graph_module", "reduce_package_graph_module"]
_USER_PRESERVED_ATTRIBUTES_KEY = ...

class _EvalCacheLoader:
    def __init__(self) -> None: ...
    def cache(self, src: str, globals: dict[str, Any], co_fields=...): ...
    def get_source(self, module_name) -> str | None: ...

_loader = ...

@compatibility(is_backward_compatible=True)
def reduce_graph_module(body: dict[Any, Any], import_block: str) -> torch.nn.Module: ...
@compatibility(is_backward_compatible=True)
def reduce_package_graph_module(
    importer: PackageImporter, body: dict[Any, Any], generated_module_name: str
) -> torch.nn.Module: ...

class _CodeOnlyModule(torch.nn.Module):
    def __init__(self, body) -> None: ...

class _WrappedCall:
    def __init__(self, cls, cls_call) -> None: ...
    def __call__(self, obj, *args, **kwargs): ...

@compatibility(is_backward_compatible=True)
class GraphModule(torch.nn.Module):
    def __new__(cls: type[GraphModule], *args, **kwargs): ...
    @compatibility(is_backward_compatible=True)
    def __init__(self, root: torch.nn.Module | dict[str, Any], graph: Graph, class_name: str = ...) -> None: ...

    __jit_unused_properties__ = ...
    @property
    def graph(self) -> Graph: ...
    @graph.setter
    def graph(self, g: Graph) -> None: ...
    @compatibility(is_backward_compatible=False)
    def to_folder(self, folder: str | os.PathLike, module_name: str = ...): ...
    @compatibility(is_backward_compatible=True)
    def add_submodule(self, target: str, m: torch.nn.Module) -> bool: ...
    @compatibility(is_backward_compatible=True)
    def delete_submodule(self, target: str) -> bool: ...
    @compatibility(is_backward_compatible=True)
    def delete_all_unused_submodules(self) -> None: ...
    @property
    def code(self) -> str: ...
    @compatibility(is_backward_compatible=True)
    def recompile(self) -> PythonCode: ...
    def __reduce_package__(self, exporter: PackageExporter): ...
    def __reduce__(self): ...
    def __deepcopy__(self, memo): ...
    def __copy__(self): ...
    @compatibility(is_backward_compatible=False)
    def print_readable(
        self,
        print_output=...,
        include_stride=...,
        include_device=...,
        colored=...,
        *,
        fast_sympy_print: bool = ...,
        expanded_def: bool = ...,
    ): ...
