from ...tokenization_utils_fast import PreTrainedTokenizerFast
from ...utils import is_sentencepiece_available
from .tokenization_xlnet import XLNetTokenizer

"""Tokenization classes for XLNet model."""
if is_sentencepiece_available(): ...
else:
    XLNetTokenizer = ...
logger = ...
VOCAB_FILES_NAMES = ...
SPIECE_UNDERLINE = ...
SEG_ID_A = ...
SEG_ID_B = ...
SEG_ID_CLS = ...
SEG_ID_SEP = ...
SEG_ID_PAD = ...

class XLNetTokenizerFast(PreTrainedTokenizerFast):
    vocab_files_names = ...
    padding_side = ...
    slow_tokenizer_class = ...
    def __init__(
        self,
        vocab_file=...,
        tokenizer_file=...,
        do_lower_case=...,
        remove_space=...,
        keep_accents=...,
        bos_token=...,
        eos_token=...,
        unk_token=...,
        sep_token=...,
        pad_token=...,
        cls_token=...,
        mask_token=...,
        additional_special_tokens=...,
        **kwargs,
    ) -> None: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["XLNetTokenizerFast"]
