import torch
from torch import Tensor

from . import profiler
from .event import Event

r"""
This package enables an interface for accessing MPS (Metal Performance Shaders) backend in Python.
Metal is Apple's API for programming metal GPU (graphics processor unit). Using MPS means that increased
performance can be achieved, by running work on the metal GPU(s).
See https://developer.apple.com/documentation/metalperformanceshaders for more details.
"""
_is_in_bad_fork = ...
_default_mps_generator: torch._C.Generator = ...

def device_count() -> int: ...
def synchronize() -> None: ...
def get_rng_state(device: int | str | torch.device = ...) -> Tensor: ...
def set_rng_state(new_state: Tensor, device: int | str | torch.device = ...) -> None: ...
def manual_seed(seed: int) -> None: ...
def seed() -> None: ...
def empty_cache() -> None: ...
def set_per_process_memory_fraction(fraction) -> None: ...
def current_allocated_memory() -> int: ...
def driver_allocated_memory() -> int: ...
def recommended_max_memory() -> int: ...
def compile_shader(source: str): ...
def is_available() -> bool: ...

__all__ = [
    "Event",
    "compile_shader",
    "current_allocated_memory",
    "device_count",
    "driver_allocated_memory",
    "empty_cache",
    "get_rng_state",
    "is_available",
    "manual_seed",
    "profiler",
    "recommended_max_memory",
    "seed",
    "set_per_process_memory_fraction",
    "set_rng_state",
    "synchronize",
]
