from typing import Any

from ._typing import CallableT

"""Contains utilities to validate argument values in `huggingface_hub`."""
REPO_ID_REGEX = ...

def validate_hf_hub_args(fn: CallableT) -> CallableT: ...
def validate_repo_id(repo_id: str) -> None: ...
def smoothly_deprecate_use_auth_token(fn_name: str, has_token: bool, kwargs: dict[str, Any]) -> dict[str, Any]: ...
