from hf_xet import PyItemProgressUpdate, PyTotalProgressUpdate

class XetProgressReporter:
    def __init__(self, n_lines: int = ..., description_width: int = ...) -> None: ...
    def format_desc(self, name: str, indent: bool) -> str: ...
    def update_progress(
        self, total_update: PyTotalProgressUpdate, item_updates: list[PyItemProgressUpdate]
    ):  # -> None:
        ...
    def close(self, _success):  # -> None:
        ...
