from .backend_config import BackendConfig

__all__ = ["get_executorch_backend_config"]
executorch_weighted_op_int8_dtype_config = ...
executorch_default_op_quint8_dtype_config = ...
executorch_default_dynamic_quint8_dtype_config = ...
executorch_act_qint8_scale_min_2_neg_12 = ...
executorch_weight_qint8_neg_127_to_127_scale_min_2_neg_12 = ...
executorch_default_dynamic_qint8_dtype_config = ...
executorch_default_dynamic_float16_dtype_config = ...
executorch_weight_only_quint8_dtype_config = ...

def get_executorch_backend_config() -> BackendConfig: ...
