from .backend_config import BackendConfig

__all__ = ["get_fbgemm_backend_config"]
fbgemm_weighted_op_quint8_dtype_config = ...
fbgemm_default_op_quint8_dtype_config = ...
fbgemm_default_op_fp16_dtype_config = ...
fbgemm_default_dynamic_int8_dtype_config = ...
fbgemm_default_dynamic_float16_dtype_config = ...
fbgemm_weight_only_quint8_dtype_config = ...
fbgemm_weight_only_quint4x2_dtype_config = ...

def get_fbgemm_backend_config() -> BackendConfig: ...
