from .backend_config import BackendConfig

__all__ = [
    "default_dynamic_float16_dtype_config",
    "default_dynamic_int8_dtype_config",
    "default_op_fp16_dtype_config",
    "default_op_quint8_dtype_config",
    "get_native_backend_config",
    "get_native_backend_config_dict",
    "get_test_only_legacy_native_backend_config",
    "get_test_only_legacy_native_backend_config_dict",
    "input_output_only_quint8_dtype_config",
    "weight_only_quint4x2_dtype_config",
    "weight_only_quint8_dtype_config",
]
weighted_op_quint8_dtype_config = ...
default_op_quint8_dtype_config = ...
default_op_fp16_dtype_config = ...
default_dynamic_int8_dtype_config = ...
default_dynamic_float16_dtype_config = ...
input_output_only_quint8_dtype_config = ...
weight_only_quint8_dtype_config = ...
weight_only_quint4x2_dtype_config = ...

def get_test_only_legacy_native_backend_config() -> BackendConfig: ...
def get_native_backend_config() -> BackendConfig: ...
def get_native_backend_config_dict() -> dict[str, Any]: ...
def get_test_only_legacy_native_backend_config_dict() -> dict[str, Any]: ...
