from .backend_config import BackendConfig

__all__ = ["get_qnnpack_backend_config"]
qnnpack_weighted_op_quint8_dtype_config = ...
qnnpack_default_op_quint8_dtype_config = ...
qnnpack_default_op_fp16_dtype_config = ...
qnnpack_default_dynamic_int8_dtype_config = ...
qnnpack_default_dynamic_float16_dtype_config = ...
qnnpack_weight_only_quint8_dtype_config = ...
qnnpack_weight_only_quint4x2_dtype_config = ...
qnnpack_act_qint8_scale_min_2_neg_12 = ...
qnnpack_weight_qint8_neg_127_to_127_scale_min_2_neg_12 = ...
qnnpack_weighted_op_qint8_symmetric_dtype_config = ...
qnnpack_default_op_qint8_symmetric_dtype_config = ...

def get_qnnpack_backend_config() -> BackendConfig:
    """Return the `BackendConfig` for PyTorch's native QNNPACK backend."""
