import torch

def throw_on_non_cuda(device): ...
def register_rng_prim(name, schema, impl_aten, impl_meta, doc, tags=...): ...
def philox_rand_offset_meta(shape: torch.Size): ...
def philox_rand_offset(shape: torch.Size): ...
def register_philox_rand(): ...
def get_device(args, kwargs): ...
def register_run_and_save_rng_state_op() -> None: ...
def register_run_with_rng_state_op() -> None: ...

run_and_save_rng_state = ...
run_with_rng_state = ...

def register_graphsafe_run_with_rng_state_op() -> None: ...

graphsafe_run_with_rng_state = ...

def register_rng_prims(): ...
