from ...image_processing_utils_fast import BaseImageProcessorFast
from ...utils import TensorType, is_torch_available, is_torchvision_available
from ...utils.import_utils import requires
from .modeling_depth_pro import DepthProDepthEstimatorOutput

"""Fast Image processor class for DepthPro."""

logger = ...
if is_torch_available(): ...
if is_torchvision_available(): ...

@requires(backends=("torchvision", "torch"))
class DepthProImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    def post_process_depth_estimation(
        self,
        outputs: DepthProDepthEstimatorOutput,
        target_sizes: TensorType | list[tuple[int, int]] | None = ...,
    ) -> dict[str, list[TensorType]]: ...

__all__ = ["DepthProImageProcessorFast"]
