from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization class for model ByT5."""
logger = ...

class ByT5Tokenizer(PreTrainedTokenizer):
    model_input_names = ...
    def __init__(
        self, eos_token=..., unk_token=..., pad_token=..., extra_ids=..., additional_special_tokens=..., **kwargs
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def convert_tokens_to_string(self, tokens):  # -> str:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["ByT5Tokenizer"]
