from dataclasses import dataclass
from typing import Any

import torch
from torch import Tensor
from torchaudio.models import Tacotron2, WaveRNN

from .interface import Tacotron2TTSBundle

__all__ = []
_BASE_URL = ...

class _EnglishCharProcessor(Tacotron2TTSBundle.TextProcessor):
    def __init__(self) -> None: ...
    @property
    def tokens(
        self,
    ):  # -> tuple[Literal['_'], Literal['-'], Literal['!'], Literal['\''], Literal['('], Literal[')'], Literal[','], Literal['.'], Literal[':'], Literal[';'], Literal['?'], Literal[' '], Literal['a'], Literal['b'], Literal['c'], Literal['d'], Literal['e'], Literal['f'], Literal['g'], Literal['h'], Literal['i'], Literal['j'], Literal['k'], Literal['l'], Literal['m'], Literal['n'], Literal['o'], Literal['p'], Literal['q'], Literal['r'], Literal['s'], Literal['t'], Literal['u'], Literal['v'], Literal['w'], Literal['x'], Literal['y'], Literal['z']]:
        ...
    def __call__(self, texts: str | list[str]) -> tuple[Tensor, Tensor]: ...

class _EnglishPhoneProcessor(Tacotron2TTSBundle.TextProcessor):
    def __init__(self, *, dl_kwargs=...) -> None: ...
    @property
    def tokens(
        self,
    ):  # -> tuple[Literal['_'], Literal['-'], Literal['!'], Literal['\''], Literal['('], Literal[')'], Literal[','], Literal['.'], Literal[':'], Literal[';'], Literal['?'], Literal[' '], Literal['AA'], Literal['AA0'], Literal['AA1'], Literal['AA2'], Literal['AE'], Literal['AE0'], Literal['AE1'], Literal['AE2'], Literal['AH'], Literal['AH0'], Literal['AH1'], Literal['AH2'], Literal['AO'], Literal['AO0'], Literal['AO1'], Literal['AO2'], Literal['AW'], Literal['AW0'], Literal['AW1'], Literal['AW2'], Literal['AY'], Literal['AY0'], Literal['AY1'], Literal['AY2'], Literal['B'], Literal['CH'], Literal['D'], Literal['DH'], Literal['EH'], Literal['EH0'], Literal['EH1'], Literal['EH2'], Literal['ER'], Literal['ER0'], Literal['ER1'], Literal['ER2'], Literal['EY'], Literal['EY0'], Literal['EY1'], Literal['EY2'], Literal['F'], Literal['G'], Literal['HH'], Literal['IH'], Literal['IH0'], Literal['IH1'], Literal['IH2'], Literal['IY'], Literal['IY0'], Literal['IY1'], Literal['IY2'], Literal['JH'], Literal['K'], Literal['L'], Literal['M'], Literal['N'], Literal['NG'], Literal['OW'], Literal['OW0'], Literal['OW1'], Literal['OW2'], Literal['OY'], Literal['OY0'], Literal['OY1'], Literal['OY2'], Literal['P'], Literal['R'], Literal['S'], Literal['SH'], Literal['T'], Literal['TH'], Literal['UH'], Literal['UH0'], Literal['UH1'], Literal['UH2'], Literal['UW'], Literal['UW0'], Literal['UW1'], Literal['UW2'], Literal['V'], Literal['W'], Literal['Y'], Literal['Z'], Literal['ZH']]:
        ...
    def __call__(self, texts: str | list[str]) -> tuple[Tensor, Tensor]: ...

class _WaveRNNVocoder(torch.nn.Module, Tacotron2TTSBundle.Vocoder):
    def __init__(self, model: WaveRNN, min_level_db: float | None = ...) -> None: ...
    @property
    def sample_rate(self):  # -> int:
        ...
    def forward(self, mel_spec, lengths=...):  # -> tuple[Tensor, Tensor | None]:
        ...

class _GriffinLimVocoder(torch.nn.Module, Tacotron2TTSBundle.Vocoder):
    def __init__(self) -> None: ...
    @property
    def sample_rate(self):  # -> int:
        ...
    def forward(self, mel_spec, lengths=...):  # -> tuple[Any, Any | None]:
        ...

class _CharMixin:
    def get_text_processor(self) -> Tacotron2TTSBundle.TextProcessor: ...

class _PhoneMixin:
    def get_text_processor(self, *, dl_kwargs=...) -> Tacotron2TTSBundle.TextProcessor: ...

@dataclass
class _Tacotron2Mixin:
    _tacotron2_path: str
    _tacotron2_params: dict[str, Any]
    def get_tacotron2(self, *, dl_kwargs=...) -> Tacotron2: ...

@dataclass
class _WaveRNNMixin:
    _wavernn_path: str | None
    _wavernn_params: dict[str, Any] | None
    def get_vocoder(self, *, dl_kwargs=...):  # -> _WaveRNNVocoder:
        ...

class _GriffinLimMixin:
    def get_vocoder(self, **_):  # -> _GriffinLimVocoder:
        ...

@dataclass
class _Tacotron2WaveRNNCharBundle(_WaveRNNMixin, _Tacotron2Mixin, _CharMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2WaveRNNPhoneBundle(_WaveRNNMixin, _Tacotron2Mixin, _PhoneMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2GriffinLimCharBundle(_GriffinLimMixin, _Tacotron2Mixin, _CharMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2GriffinLimPhoneBundle(_GriffinLimMixin, _Tacotron2Mixin, _PhoneMixin, Tacotron2TTSBundle): ...

TACOTRON2_GRIFFINLIM_CHAR_LJSPEECH = ...
TACOTRON2_GRIFFINLIM_PHONE_LJSPEECH = ...
TACOTRON2_WAVERNN_CHAR_LJSPEECH = ...
TACOTRON2_WAVERNN_PHONE_LJSPEECH = ...
