from dataclasses import dataclass
from typing import Any

import torch
from torch import Tensor
from torchaudio.models import Tacotron2, WaveRNN

from .interface import Tacotron2TTSBundle

__all__ = []
_BASE_URL = ...

class _EnglishCharProcessor(Tacotron2TTSBundle.TextProcessor):
    def __init__(self) -> None: ...
    @property
    def tokens(self): ...
    def __call__(self, texts: str | list[str]) -> tuple[Tensor, Tensor]: ...

class _EnglishPhoneProcessor(Tacotron2TTSBundle.TextProcessor):
    def __init__(self, *, dl_kwargs=...) -> None: ...
    @property
    def tokens(self): ...
    def __call__(self, texts: str | list[str]) -> tuple[Tensor, Tensor]: ...

class _WaveRNNVocoder(torch.nn.Module, Tacotron2TTSBundle.Vocoder):
    def __init__(self, model: WaveRNN, min_level_db: float | None = ...) -> None: ...
    @property
    def sample_rate(self): ...
    def forward(self, mel_spec, lengths=...): ...

class _GriffinLimVocoder(torch.nn.Module, Tacotron2TTSBundle.Vocoder):
    def __init__(self) -> None: ...
    @property
    def sample_rate(self): ...
    def forward(self, mel_spec, lengths=...): ...

class _CharMixin:
    def get_text_processor(self) -> Tacotron2TTSBundle.TextProcessor: ...

class _PhoneMixin:
    def get_text_processor(self, *, dl_kwargs=...) -> Tacotron2TTSBundle.TextProcessor: ...

@dataclass
class _Tacotron2Mixin:
    _tacotron2_path: str
    _tacotron2_params: dict[str, Any]
    def get_tacotron2(self, *, dl_kwargs=...) -> Tacotron2: ...

@dataclass
class _WaveRNNMixin:
    _wavernn_path: str | None
    _wavernn_params: dict[str, Any] | None
    def get_vocoder(self, *, dl_kwargs=...): ...

class _GriffinLimMixin:
    def get_vocoder(self, **_): ...

@dataclass
class _Tacotron2WaveRNNCharBundle(_WaveRNNMixin, _Tacotron2Mixin, _CharMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2WaveRNNPhoneBundle(_WaveRNNMixin, _Tacotron2Mixin, _PhoneMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2GriffinLimCharBundle(_GriffinLimMixin, _Tacotron2Mixin, _CharMixin, Tacotron2TTSBundle): ...

@dataclass
class _Tacotron2GriffinLimPhoneBundle(_GriffinLimMixin, _Tacotron2Mixin, _PhoneMixin, Tacotron2TTSBundle): ...

TACOTRON2_GRIFFINLIM_CHAR_LJSPEECH = ...
TACOTRON2_GRIFFINLIM_PHONE_LJSPEECH = ...
TACOTRON2_WAVERNN_CHAR_LJSPEECH = ...
TACOTRON2_WAVERNN_PHONE_LJSPEECH = ...
