from typing import Any

from ...tokenization_utils import PreTrainedTokenizer
from ...utils.import_utils import requires

"""Tokenization class for model DeBERTa."""
logger = ...
VOCAB_FILES_NAMES = ...

@requires(backends=("sentencepiece",))
class DebertaV2Tokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    def __init__(
        self,
        vocab_file,
        do_lower_case=...,
        split_by_punct=...,
        bos_token=...,
        eos_token=...,
        unk_token=...,
        sep_token=...,
        pad_token=...,
        cls_token=...,
        mask_token=...,
        sp_model_kwargs: dict[str, Any] | None = ...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    @property
    def vocab(self):  # -> dict[Any, int]:
        ...
    def get_vocab(self):  # -> dict[Any, int]:
        ...
    def convert_tokens_to_string(self, tokens):  # -> LiteralString:

        ...
    def build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=...):  # -> list[str | list[str] | Any | None]:

        ...
    def get_special_tokens_mask(self, token_ids_0, token_ids_1=..., already_has_special_tokens=...):  # -> list[int]:

        ...
    def prepare_for_tokenization(self, text, is_split_into_words=..., **kwargs):  # -> tuple[str, dict[str, Any]]:
        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

class SPMTokenizer:
    def __init__(
        self, vocab_file, special_tokens, split_by_punct=..., sp_model_kwargs: dict[str, Any] | None = ...
    ) -> None: ...
    def __getstate__(self):  # -> dict[str, Any]:
        ...
    def __setstate__(self, d):  # -> None:
        ...
    def tokenize(self, text):  # -> list[Any]:
        ...
    def convert_ids_to_tokens(self, ids):  # -> list[Any]:
        ...
    def decode(self, tokens, start=..., end=..., raw_text=...):  # -> LiteralString:
        ...
    def add_special_token(self, token):  # -> int:
        ...
    def part_of_whole_word(self, token, is_bos=...):  # -> bool:
        ...
    def pad(self):  # -> Literal['[PAD]']:
        ...
    def bos(self):  # -> Literal['[CLS]']:
        ...
    def eos(self):  # -> Literal['[SEP]']:
        ...
    def unk(self):  # -> Literal['[UNK]']:
        ...
    def mask(self):  # -> Literal['[MASK]']:
        ...
    def sym(self, id): ...
    def id(self, sym):  # -> int:
        ...
    def split_to_words(self, text):  # -> list[Any]:
        ...
    def save_pretrained(self, path: str, filename_prefix: str | None = ...):  # -> tuple[str]:
        ...

def convert_to_unicode(text):  # -> str:

    ...

__all__ = ["DebertaV2Tokenizer"]
