import types
from io import BytesIO as BytesIO

from _typeshed import Incomplete

from ._version import __version__ as __version__

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

class ImmutableSentencePieceText_ImmutableSentencePiece:
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
    piece: Incomplete
    piece_as_bytes: Incomplete
    surface: Incomplete
    surface_as_bytes: Incomplete
    id: Incomplete
    begin: Incomplete
    end: Incomplete
    def __eq__(self, other): ...
    def __hash__(self): ...

class ImmutableSentencePieceText:
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
    def SerializeAsString(self): ...
    text: Incomplete
    text_as_bytes: Incomplete
    score: Incomplete
    class ImmutableSentencePieceIterator:
        proto: Incomplete
        len: Incomplete
        def __init__(self, proto) -> None: ...
        def __len__(self) -> int: ...
        def __getitem__(self, index): ...

    @property
    def pieces(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class ImmutableNBestSentencePieceText:
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
    def SerializeAsString(self): ...
    class ImmutableSentencePieceTextIterator:
        proto: Incomplete
        len: Incomplete
        def __init__(self, proto) -> None: ...
        def __len__(self) -> int: ...
        def __getitem__(self, index): ...

    @property
    def nbests(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class SentencePieceProcessor:
    thisown: Incomplete
    def __init__(self, model_file: str) -> None: ...
    __swig_destroy__: Incomplete
    def LoadFromSerializedProto(self, serialized): ...
    def SetEncodeExtraOptions(self, extra_option): ...
    def SetDecodeExtraOptions(self, extra_option): ...
    def SetVocabulary(self, valid_vocab): ...
    def ResetVocabulary(self): ...
    def LoadVocabulary(self, filename, threshold): ...
    def CalculateEntropy(self, *args): ...
    def GetPieceSize(self): ...
    def PieceToId(self, piece): ...
    def IdToPiece(self, id): ...
    def GetScore(self, id): ...
    def IsUnknown(self, id): ...
    def IsControl(self, id): ...
    def IsUnused(self, id): ...
    def IsByte(self, id): ...
    def unk_id(self): ...
    def bos_id(self): ...
    def eos_id(self): ...
    def pad_id(self): ...
    def serialized_model_proto(self): ...
    def LoadFromFile(self, arg): ...
    def Init(
        self,
        model_file=None,
        model_proto=None,
        out_type=...,
        add_bos: bool = False,
        add_eos: bool = False,
        reverse: bool = False,
        emit_unk_piece: bool = False,
        enable_sampling: bool = False,
        nbest_size: int = -1,
        alpha: float = 0.1,
        num_threads: int = -1,
    ) -> None: ...
    def Encode(
        self,
        input,
        out_type=None,
        add_bos=None,
        add_eos=None,
        reverse=None,
        emit_unk_piece=None,
        enable_sampling=None,
        nbest_size=None,
        alpha=None,
        num_threads=None,
    ): ...
    def EncodeAsPieces(self, input, **kwargs): ...
    def EncodeAsIds(self, input, **kwargs): ...
    def EncodeAsSerializedProto(self, input, **kwargs): ...
    def EncodeAsImmutableProto(self, input, **kwargs): ...
    def SampleEncodeAsPieces(self, input, nbest_size=None, alpha=None, **kwargs): ...
    def SampleEncodeAsIds(self, input, nbest_size=None, alpha=None, **kwargs): ...
    def SampleEncodeAsSerializedProto(self, input, nbest_size=None, alpha=None, **kwargs): ...
    def SampleEncodeAsImmutableProto(self, input, nbest_size=None, alpha=None, **kwargs): ...
    def NBestEncode(
        self, input, out_type=None, add_bos=None, add_eos=None, reverse=None, emit_unk_piece=None, nbest_size=None
    ): ...
    def NBestEncodeAsPieces(self, input, nbest_size=None, **kwargs): ...
    def NBestEncodeAsIds(self, input, nbest_size=None, **kwargs): ...
    def NBestEncodeAsSerializedProto(self, input, nbest_size=None, **kwargs): ...
    def NBestEncodeAsImmutableProto(self, input, nbest_size=None, **kwargs): ...
    def SampleEncodeAndScore(
        self,
        input,
        out_type=None,
        add_bos=None,
        add_eos=None,
        reverse=None,
        emit_unk_piece=None,
        num_samples=None,
        alpha=None,
        wor=None,
        include_best=None,
    ): ...
    def SampleEncodeAndScoreAsPieces(self, input, num_samples=None, alpha=None, **kwargs): ...
    def SampleEncodeAndScoreAsIds(self, input, num_samples=None, alpha=None, **kwargs): ...
    def SampleEncodeAndScoreAsSerializedProto(self, input, num_samples=None, alpha=None, **kwargs): ...
    def SampleEncodeAndScoreAsImmutableProto(self, input, num_samples=None, alpha=None, **kwargs): ...
    def Decode(self, input, out_type=..., num_threads=None): ...
    def DecodePieces(self, input, out_type=..., **kwargs): ...
    def DecodeIds(self, input, out_type=..., **kwargs): ...
    def DecodePiecesAsSerializedProto(self, input, out_type: str = "serialized_proto", **kwargs): ...
    def DecodeIdsAsSerializedProto(self, input, out_type: str = "serialized_proto", **kwargs): ...
    def DecodePiecesAsImmutableProto(self, input, out_type: str = "immutable_proto", **kwargs): ...
    def DecodeIdsAsImmutableProto(self, input, out_type: str = "immutable_proto", **kwargs): ...
    def CalculateEntropy(self, input, alpha, num_threads=None): ...
    def Normalize(self, input, with_offsets=None): ...
    def OverrideNormalizerSpec(self, **kwargs): ...
    def piece_size(self): ...
    def vocab_size(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, piece): ...
    def Load(self, model_file=None, model_proto=None): ...

def SetRandomGeneratorSeed(seed): ...
def SetMinLogLevel(v): ...

class SentencePieceTrainer:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def Train(arg=None, logstream=None, **kwargs) -> None: ...

class SentencePieceNormalizer:
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
    def LoadFromSerializedProto(self, serialized): ...
    def LoadFromRuleTSV(self, filename): ...
    def LoadFromRuleName(self, name): ...
    def serialized_model_proto(self): ...
    def LoadFromFile(self, arg): ...
    def Init(
        self,
        model_file=None,
        model_proto=None,
        rule_tsv=None,
        rule_name=None,
        add_dummy_prefix: bool = False,
        escape_whitespaces: bool = False,
        remove_extra_whitespaces: bool = False,
    ) -> None: ...
    def Normalize(self, input, with_offsets=None): ...

def SetDataDir(data_dir): ...

set_random_generator_seed = SetRandomGeneratorSeed
set_min_log_level = SetMinLogLevel

class _LogStream:
    ostream: Incomplete
    orig_stream_fileno: Incomplete
    def __init__(self, ostream=None) -> None: ...
    orig_stream_dup: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None
    ) -> None: ...
