from torch._C import _cusparselt

__all__ = ["get_max_alg_id", "is_available", "version"]
__cusparselt_version: int | None = ...
__MAX_ALG_ID: int | None = ...
if _cusparselt is not None: ...

def version() -> int | None: ...
def is_available() -> bool: ...
def get_max_alg_id() -> int | None: ...
