from ...processing_utils import ProcessorMixin
from ...utils.import_utils import requires

"""
Text/audio processor class for MusicGen Melody
"""

@requires(backends=("torchaudio",))
class MusicgenMelodyProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def get_decoder_prompt_ids(self, task=..., language=..., no_timestamps=...): ...
    def __call__(self, audio=..., text=..., **kwargs): ...
    def batch_decode(self, *args, **kwargs):  # -> list[ndarray[_AnyShape, dtype[Any]]]:

        ...
    def decode(self, *args, **kwargs): ...
    def get_unconditional_inputs(self, num_samples=..., return_tensors=...): ...

__all__ = ["MusicgenMelodyProcessor"]
