import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import BaseImageProcessorFast, DefaultFastImageProcessorKwargs
from ...processing_utils import Unpack
from ...utils import is_torch_available, is_torchvision_available

"""Fast Image processor class for ViTMatte."""
if is_torch_available(): ...
if is_torchvision_available(): ...
logger = ...

class VitMatteFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_pad: bool | None
    size_divisibility: int

class VitMatteImageProcessorFast(BaseImageProcessorFast):
    do_rescale: bool = ...
    rescale_factor: int | float = ...
    do_normalize: bool = ...
    image_mean: float | list[float] | None = ...
    image_std: float | list[float] | None = ...
    do_pad: bool = ...
    size_divisibility: int = ...
    valid_kwargs = VitMatteFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[VitMatteFastImageProcessorKwargs]) -> None: ...
    def preprocess(
        self,
        images: list[torch.Tensor],
        trimaps: list[torch.Tensor],
        **kwargs: Unpack[VitMatteFastImageProcessorKwargs],
    ) -> BatchFeature: ...

__all__ = ["VitMatteImageProcessorFast"]
