import io
from types import ModuleType

import torch
from torch.library import register_fake

_pybind_ops: ModuleType | None = ...

def load_torchcodec_shared_libraries():  # -> tuple[Literal[8, 7, 6, 5, 4], str]:
    ...

create_from_file = ...
encode_audio_to_file = ...
encode_audio_to_tensor = ...
_encode_audio_to_file_like = ...
encode_video_to_file = ...
encode_video_to_tensor = ...
_encode_video_to_file_like = ...
create_from_tensor = ...
_create_from_file_like = ...
add_video_stream = ...
_add_video_stream = ...
add_audio_stream = ...
seek_to_pts = ...
get_next_frame = ...
get_frame_at_pts = ...
get_frame_at_index = ...
_get_frames_at_indices_tensor_input = ...
_get_frames_by_pts_tensor_input = ...
get_frames_in_range = ...
get_frames_by_pts_in_range = ...
get_frames_by_pts_in_range_audio = ...
get_json_metadata = ...
_test_frame_pts_equality = ...
_get_container_json_metadata = ...
_get_key_frame_indices = ...
scan_all_streams_to_update_metadata = ...
_get_stream_json_metadata = ...
_get_json_ffmpeg_library_versions = ...
_get_backend_details = ...

def create_from_bytes(video_bytes: bytes, seek_mode: str | None = ...) -> torch.Tensor: ...
def create_from_file_like(file_like: io.RawIOBase | io.BufferedReader, seek_mode: str | None = ...) -> torch.Tensor: ...
def encode_audio_to_file_like(
    samples: torch.Tensor,
    sample_rate: int,
    format: str,
    file_like: io.RawIOBase | io.BufferedIOBase,
    bit_rate: int | None = ...,
    num_channels: int | None = ...,
    desired_sample_rate: int | None = ...,
) -> None: ...
def encode_video_to_file_like(
    frames: torch.Tensor,
    frame_rate: float,
    format: str,
    file_like: io.RawIOBase | io.BufferedIOBase,
    codec: str | None = ...,
    pixel_format: str | None = ...,
    crf: float | None = ...,
    preset: str | None = ...,
    extra_options: list[str] | None = ...,
) -> None: ...
def get_frames_at_indices(
    decoder: torch.Tensor, *, frame_indices: torch.Tensor | list[int]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
def get_frames_by_pts(
    decoder: torch.Tensor, *, timestamps: torch.Tensor | list[float]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::create_from_file")
def create_from_file_abstract(filename: str, seek_mode: str | None) -> torch.Tensor: ...
@register_fake("torchcodec_ns::encode_audio_to_file")
def encode_audio_to_file_abstract(
    samples: torch.Tensor,
    sample_rate: int,
    filename: str,
    bit_rate: int | None = ...,
    num_channels: int | None = ...,
    desired_sample_rate: int | None = ...,
) -> None: ...
@register_fake("torchcodec_ns::encode_audio_to_tensor")
def encode_audio_to_tensor_abstract(
    samples: torch.Tensor,
    sample_rate: int,
    format: str,
    bit_rate: int | None = ...,
    num_channels: int | None = ...,
    desired_sample_rate: int | None = ...,
) -> torch.Tensor: ...
@register_fake("torchcodec_ns::encode_video_to_file")
def encode_video_to_file_abstract(
    frames: torch.Tensor,
    frame_rate: float,
    filename: str,
    codec: str | None = ...,
    pixel_format: str | None = ...,
    preset: str | None = ...,
    crf: float | None = ...,
    extra_options: list[str] | None = ...,
) -> None: ...
@register_fake("torchcodec_ns::encode_video_to_tensor")
def encode_video_to_tensor_abstract(
    frames: torch.Tensor,
    frame_rate: float,
    format: str,
    codec: str | None = ...,
    pixel_format: str | None = ...,
    preset: str | None = ...,
    crf: float | None = ...,
    extra_options: list[str] | None = ...,
) -> torch.Tensor: ...
@register_fake("torchcodec_ns::create_from_tensor")
def create_from_tensor_abstract(video_tensor: torch.Tensor, seek_mode: str | None) -> torch.Tensor: ...
@register_fake("torchcodec_ns::add_video_stream")
def add_video_stream_abstract(
    decoder: torch.Tensor,
    *,
    num_threads: int | None = ...,
    dimension_order: str | None = ...,
    stream_index: int | None = ...,
    device: str = ...,
    device_variant: str = ...,
    transform_specs: str = ...,
    custom_frame_mappings: tuple[torch.Tensor, torch.Tensor, torch.Tensor] | None = ...,
) -> None: ...
@register_fake("torchcodec_ns::add_audio_stream")
def add_audio_stream_abstract(
    decoder: torch.Tensor,
    *,
    stream_index: int | None = ...,
    sample_rate: int | None = ...,
    num_channels: int | None = ...,
) -> None: ...
@register_fake("torchcodec_ns::seek_to_pts")
def seek_abstract(decoder: torch.Tensor, seconds: float) -> None: ...
@register_fake("torchcodec_ns::get_next_frame")
def get_next_frame_abstract(
    decoder: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frame_at_pts")
def get_frame_at_pts_abstract(
    decoder: torch.Tensor, seconds: float
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frames_by_pts")
def get_frames_by_pts_abstract(
    decoder: torch.Tensor, *, timestamps: torch.Tensor | list[float]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frame_at_index")
def get_frame_at_index_abstract(
    decoder: torch.Tensor, *, frame_index: int
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frames_at_indices")
def get_frames_at_indices_abstract(
    decoder: torch.Tensor, *, frame_indices: torch.Tensor | list[int]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frames_in_range")
def get_frames_in_range_abstract(
    decoder: torch.Tensor, *, start: int, stop: int, step: int | None = ...
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frames_by_pts_in_range")
def get_frames_by_pts_in_range_abstract(
    decoder: torch.Tensor, *, start_seconds: float, stop_seconds: float
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::get_frames_by_pts_in_range_audio")
def get_frames_by_pts_in_range_audio_abstract(
    decoder: torch.Tensor,
    *,
    start_seconds: float,
    stop_seconds: float | None = ...,
) -> tuple[torch.Tensor, torch.Tensor]: ...
@register_fake("torchcodec_ns::_get_key_frame_indices")
def get_key_frame_indices_abstract(decoder: torch.Tensor) -> torch.Tensor: ...
@register_fake("torchcodec_ns::get_json_metadata")
def get_json_metadata_abstract(decoder: torch.Tensor) -> str: ...
@register_fake("torchcodec_ns::get_container_json_metadata")
def get_container_json_metadata_abstract(decoder: torch.Tensor) -> str: ...
@register_fake("torchcodec_ns::get_stream_json_metadata")
def get_stream_json_metadata_abstract(decoder: torch.Tensor, stream_idx: int) -> str: ...
@register_fake("torchcodec_ns::scan_all_streams_to_update_metadata")
def scan_all_streams_to_update_metadata_abstract(
    decoder: torch.Tensor,
) -> None: ...
def get_ffmpeg_library_versions():  # -> Any:
    ...
