themes = ...
colors = ...
sizes = ...
palette_range = ...
size_range = ...
docs_theme_core = ...
docs_theme_vars = ...

def get_docstr(var): ...
def get_doc_theme_var_groups():  # -> tuple[list[Any], list[Any]]:
    ...

css = ...
if __name__ == "__main__": ...
