"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from ...utils import _LazyModule
from ...utils.import_utils import define_import_structure
from .configuration_plbart import *
from .modeling_plbart import *
from .tokenization_plbart import *

if TYPE_CHECKING: ...
else: ...
