from torch.utils._python_dispatch import TorchDispatchMode

Mutation = ...
Aliasing = ...
SchemaArgument = ...
SchemaArgType = ...
SchemaInfo = ...

def is_iterable_of_tensors(iterable):  # -> bool:
    ...
def clone_inputs(args):  # -> list[Any]:
    ...

class SchemaCheckMode(TorchDispatchMode):
    def __init__(self) -> None: ...
    def reset_cache(self):  # -> None:
        ...
    def display_ops(self):  # -> None:
        ...
    def __torch_dispatch__(self, func, types, args=..., kwargs=...):  # -> tuple[Any, ...]:
        ...
