from torch.utils._python_dispatch import TorchDispatchMode

Mutation = ...
Aliasing = ...
SchemaArgument = ...
SchemaArgType = ...
SchemaInfo = ...

def is_iterable_of_tensors(iterable): ...
def clone_inputs(args): ...

class SchemaCheckMode(TorchDispatchMode):
    def __init__(self) -> None: ...
    def reset_cache(self): ...
    def display_ops(self): ...
    def __torch_dispatch__(self, func, types, args=..., kwargs=...): ...
