import torch

from ...processing_utils import Unpack, VideosKwargs
from ...utils import is_torch_available, is_torchvision_available, is_vision_available
from ...utils.import_utils import requires
from ...video_processing_utils import BaseVideoProcessor
from ...video_utils import VideoMetadata

"""Fast Video processor class for InternVL."""
if is_torchvision_available(): ...
if is_torch_available(): ...
if is_vision_available(): ...

class InternVLVideoProcessorInitKwargs(VideosKwargs):
    initial_shift: bool | float | int

@requires(backends=("torchvision",))
class InternVLVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    initial_shift = ...
    do_sample_frames = ...
    valid_kwargs = InternVLVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[InternVLVideoProcessorInitKwargs]) -> None: ...
    def sample_frames(
        self,
        video: torch.Tensor,
        metadata: VideoMetadata | dict | None = ...,
        num_frames: int | None = ...,
        fps: float | None = ...,
        initial_shift: bool | float | None = ...,
    ):  # -> Tensor:

        ...

__all__ = ["InternVLVideoProcessor"]
