from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization class for model MyT5."""
logger = ...
VOCAB_FILES_NAMES = ...

class ByteRewriter:
    LEAF = ...
    def __init__(self, rewriting_rules: str | dict[str, str]) -> None: ...
    def add_leaf(
        self, hash_tree: dict[str, dict | list[str]], byte_in_sequence: str, byte_out_sequence: str
    ):  # -> None:

        ...
    def construct_hash_tree(self, rewriting_rules: dict[str, str]) -> dict[str, dict | list[str]]: ...
    def search_hash_tree(self, byte_sequence: list[str]) -> None | list[str]: ...
    def rewrite_bytes(self, in_bytes: list[str], reverse=...) -> list[str]: ...

class MyT5Tokenizer(PreTrainedTokenizer):
    model_input_names = ...
    vocab_files_names = ...
    def __init__(
        self,
        vocab_file,
        eos_token=...,
        unk_token=...,
        pad_token=...,
        extra_ids=...,
        additional_special_tokens=...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def morphological_encode(self, indices: list[str]) -> list[str]: ...
    def morphological_decode(self, indices: list[str]) -> list[str]: ...
    def convert_tokens_to_string(self, tokens):  # -> str:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["MyT5Tokenizer"]
