import pdb
import typing
import torch
from torch._C._distributed_c10d import ProcessGroup as ProcessGroup
from .distributed_c10d import *

log = ...

def is_available() -> bool: ...

if is_available() and not torch._C._c10d_init(): ...
DistError = ...
DistBackendError = ...
DistNetworkError = ...
DistStoreError = ...
QueueEmptyError = ...
if is_available():
    class _DistributedPdb(pdb.Pdb):
        def interaction(self, *args, **kwargs) -> None: ...

    _breakpoint_cache: dict[int, typing.Any] = ...
    def breakpoint(rank: int = ..., skip: int = ..., timeout_s=...) -> None: ...

else:
    class _ProcessGroupStub: ...
