class ANSI:
    _bold = ...
    _gray = ...
    _red = ...
    _reset = ...
    _yellow = ...
    @classmethod
    def bold(cls, s: str) -> str: ...
    @classmethod
    def gray(cls, s: str) -> str: ...
    @classmethod
    def red(cls, s: str) -> str: ...
    @classmethod
    def yellow(cls, s: str) -> str: ...

def tabulate(rows: list[list[str | int]], headers: list[str]) -> str: ...
def show_deprecation_warning(old_command: str, new_command: str):  # -> None:

    ...
