"""
This type stub file was generated by pyright.
"""

import flax.linen as nn
import jax
import jax.numpy as jnp
from typing import Optional
from flax.core.frozen_dict import FrozenDict
from ...modeling_flax_utils import FlaxPreTrainedModel
from ...utils import add_start_docstrings, add_start_docstrings_to_model_forward
from .configuration_bloom import BloomConfig

logger = ...
_CHECKPOINT_FOR_DOC = ...
_CONFIG_FOR_DOC = ...
BLOOM_START_DOCSTRING = ...
BLOOM_INPUTS_DOCSTRING = ...

def build_alibi_tensor(attention_mask: jnp.ndarray, num_heads: int, dtype: Optional[jnp.dtype] = ...): ...

class FlaxBloomAttention(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(
        self,
        hidden_states,
        residual,
        alibi,
        attention_mask=...,
        deterministic: bool = ...,
        init_cache: bool = ...,
        output_attentions: bool = ...,
    ): ...

class BloomGELU(nn.Module):
    def setup(self): ...
    def __call__(self, x): ...

class FlaxBloomMLP(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(self, hidden_states, residual, deterministic: bool = ...): ...

class FlaxBloomBlock(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(
        self,
        hidden_states,
        alibi,
        attention_mask=...,
        deterministic: bool = ...,
        init_cache: bool = ...,
        output_attentions: bool = ...,
    ): ...

class FlaxBloomPreTrainedModel(FlaxPreTrainedModel):
    config_class = BloomConfig
    base_model_prefix = ...
    module_class: nn.Module = ...
    def __init__(
        self,
        config: BloomConfig,
        input_shape: tuple = ...,
        seed: int = ...,
        dtype: jnp.dtype = ...,
        _do_init: bool = ...,
        **kwargs,
    ) -> None: ...
    def init_weights(self, rng: jax.random.PRNGKey, input_shape: tuple, params: FrozenDict = ...) -> FrozenDict: ...
    def init_cache(self, batch_size, max_length): ...
    @add_start_docstrings_to_model_forward(BLOOM_INPUTS_DOCSTRING)
    def __call__(
        self,
        input_ids,
        attention_mask=...,
        past_key_values: Optional[dict] = ...,
        params: Optional[dict] = ...,
        dropout_rng: jax.random.PRNGKey = ...,
        train: bool = ...,
        output_attentions: Optional[bool] = ...,
        output_hidden_states: Optional[bool] = ...,
        return_dict: Optional[bool] = ...,
    ): ...

class FlaxBloomBlockCollection(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(
        self,
        hidden_states,
        alibi,
        attention_mask=...,
        deterministic: bool = ...,
        init_cache: bool = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
    ): ...

class FlaxBloomModule(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(
        self,
        input_ids=...,
        attention_mask=...,
        deterministic=...,
        init_cache: bool = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ): ...

@add_start_docstrings(..., BLOOM_START_DOCSTRING)
class FlaxBloomModel(FlaxBloomPreTrainedModel):
    module_class = ...

class FlaxBloomForCausalLMModule(nn.Module):
    config: BloomConfig
    dtype: jnp.dtype = ...
    def setup(self): ...
    def __call__(
        self,
        input_ids,
        attention_mask,
        deterministic: bool = ...,
        init_cache: bool = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        return_dict: bool = ...,
    ): ...

@add_start_docstrings(..., BLOOM_START_DOCSTRING)
class FlaxBloomForCausalLM(FlaxBloomPreTrainedModel):
    module_class = ...
    def prepare_inputs_for_generation(self, input_ids, max_length, attention_mask: Optional[jax.Array] = ...): ...
    def update_inputs_for_generation(self, model_outputs, model_kwargs): ...

__all__ = ["FlaxBloomForCausalLM", "FlaxBloomModel", "FlaxBloomPreTrainedModel"]
