from typing import Optional

from ..common import DeviceOpOverrides, TritonScratchWorkspace

class XPUDeviceOpOverrides(DeviceOpOverrides):
    def import_get_raw_stream_as(self, name: str) -> str: ...
    def set_device(self, device_idx: int) -> str: ...
    def synchronize(self) -> str: ...
    def device_guard(self, device_idx: int) -> str: ...
    def cpp_device_guard(self) -> str: ...
    def cpp_aoti_device_guard(self) -> str: ...
    def cpp_stream_guard(self) -> str: ...
    def cpp_aoti_stream_guard(self) -> str: ...
    def cpp_getStreamFromExternal(self) -> str: ...
    def kernel_header(self) -> str: ...
    def kernel_driver(self) -> str: ...
    def cpp_stream_type(self) -> str: ...
    def aoti_get_stream(self) -> str: ...
    def cpp_kernel_type(self) -> str: ...
    def cpp_device_ptr(self) -> str: ...
    def cpp_scratch(
        self, idx: int, workspace: TritonScratchWorkspace, prefix: str | None = ...
    ) -> tuple[list[str], str] | None: ...
