from ...image_processing_utils_fast import BaseImageProcessorFast

"""Fast Image processor class for SigLIP."""

class SiglipImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...

__all__ = ["SiglipImageProcessorFast"]
