from typing import TYPE_CHECKING, Any

from ...tokenization_utils import PreTrainedTokenizer
from ...tokenization_utils_base import TextInput
from ...utils.import_utils import requires

"""Tokenization class for SigLIP model."""
if TYPE_CHECKING: ...
logger = ...
VOCAB_FILES_NAMES = ...
SPIECE_UNDERLINE = ...

@requires(backends=("sentencepiece",))
class SiglipTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self,
        vocab_file,
        eos_token=...,
        unk_token=...,
        pad_token=...,
        additional_special_tokens=...,
        sp_model_kwargs: dict[str, Any] | None = ...,
        model_max_length=...,
        do_lower_case=...,
        **kwargs,
    ) -> None: ...
    def get_spm_processor(self):  # -> SentencePieceProcessor:
        ...
    @property
    def vocab_size(self): ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def get_special_tokens_mask(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ..., already_has_special_tokens: bool = ...
    ) -> list[int]: ...
    def create_token_type_ids_from_sequences(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def build_inputs_with_special_tokens(
        self, token_ids_0: list[int], token_ids_1: list[int] | None = ...
    ) -> list[int]: ...
    def __getstate__(self):  # -> dict[str, Any]:
        ...
    def __setstate__(self, d):  # -> None:
        ...
    def remove_punctuation(self, text: str) -> str: ...
    def canonicalize_text(self, text, *, keep_punctuation_exact_string=...):  # -> str:

        ...
    def tokenize(self, text: TextInput, add_special_tokens=..., **kwargs) -> list[str]: ...
    @property
    def unk_token_length(self):  # -> int:
        ...
    def convert_tokens_to_string(self, tokens): ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["SiglipTokenizer"]
