"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional, Union
from torch import nn
from ...modeling_outputs import (
    BackboneOutput,
    BaseModelOutputWithNoAttention,
    BaseModelOutputWithPoolingAndNoAttention,
    ImageClassifierOutputWithNoAttention,
)
from ...modeling_utils import PreTrainedModel
from ...utils import auto_docstring
from ...utils.backbone_utils import BackboneMixin
from .configuration_convnextv2 import ConvNextV2Config

logger = ...

def drop_path(input: torch.Tensor, drop_prob: float = ..., training: bool = ...) -> torch.Tensor: ...

class ConvNextV2DropPath(nn.Module):
    def __init__(self, drop_prob: Optional[float] = ...) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class ConvNextV2GRN(nn.Module):
    def __init__(self, dim: int) -> None: ...
    def forward(self, hidden_states: torch.FloatTensor) -> torch.FloatTensor: ...

class ConvNextV2LayerNorm(nn.Module):
    def __init__(self, normalized_shape, eps=..., data_format=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class ConvNextV2Embeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextV2Layer(nn.Module):
    def __init__(self, config, dim, drop_path=...) -> None: ...
    def forward(self, hidden_states: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextV2Stage(nn.Module):
    def __init__(
        self, config, in_channels, out_channels, kernel_size=..., stride=..., depth=..., drop_path_rates=...
    ) -> None: ...
    def forward(self, hidden_states: torch.FloatTensor) -> torch.Tensor: ...

class ConvNextV2Encoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        hidden_states: torch.FloatTensor,
        output_hidden_states: Optional[bool] = ...,
        return_dict: Optional[bool] = ...,
    ) -> Union[tuple, BaseModelOutputWithNoAttention]: ...

@auto_docstring
class ConvNextV2PreTrainedModel(PreTrainedModel):
    config: ConvNextV2Config
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...

@auto_docstring
class ConvNextV2Model(ConvNextV2PreTrainedModel):
    def __init__(self, config) -> None: ...
    @auto_docstring
    def forward(
        self,
        pixel_values: Optional[torch.FloatTensor] = ...,
        output_hidden_states: Optional[bool] = ...,
        return_dict: Optional[bool] = ...,
    ) -> Union[tuple, BaseModelOutputWithPoolingAndNoAttention]: ...

@auto_docstring(custom_intro=...)
class ConvNextV2ForImageClassification(ConvNextV2PreTrainedModel):
    def __init__(self, config) -> None: ...
    @auto_docstring
    def forward(
        self,
        pixel_values: Optional[torch.FloatTensor] = ...,
        labels: Optional[torch.LongTensor] = ...,
        output_hidden_states: Optional[bool] = ...,
        return_dict: Optional[bool] = ...,
    ) -> Union[tuple, ImageClassifierOutputWithNoAttention]: ...

@auto_docstring(custom_intro=...)
class ConvNextV2Backbone(ConvNextV2PreTrainedModel, BackboneMixin):
    def __init__(self, config) -> None: ...
    @auto_docstring
    def forward(
        self, pixel_values: torch.Tensor, output_hidden_states: Optional[bool] = ..., return_dict: Optional[bool] = ...
    ) -> BackboneOutput: ...

__all__ = ["ConvNextV2ForImageClassification", "ConvNextV2Model", "ConvNextV2PreTrainedModel", "ConvNextV2Backbone"]
