from torch import Tensor
from torch.distributions.exp_family import ExponentialFamily
from torch.types import _size

__all__ = ["Beta"]

class Beta(ExponentialFamily):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    def __init__(
        self, concentration1: Tensor | float, concentration0: Tensor | float, validate_args: bool | None = ...
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def entropy(self) -> Tensor: ...
    @property
    def concentration1(self) -> Tensor: ...
    @property
    def concentration0(self) -> Tensor: ...
