import torch
from torch import Tensor
from torch.distributions import constraints
from torch.distributions.distribution import Distribution
from torch.distributions.utils import lazy_property

__all__ = ["Categorical"]

class Categorical(Distribution):
    arg_constraints = ...
    has_enumerate_support = ...
    def __init__(
        self, probs: Tensor | None = ..., logits: Tensor | None = ..., validate_args: bool | None = ...
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @constraints.dependent_property(is_discrete=True, event_dim=0)
    def support(self) -> integer_interval: ...
    @lazy_property
    def logits(self) -> Tensor: ...
    @lazy_property
    def probs(self) -> Tensor: ...
    @property
    def param_shape(self) -> torch.Size: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def sample(self, sample_shape=...) -> Tensor: ...
    def log_prob(self, value) -> Any: ...
    def entropy(self) -> Tensor: ...
    def enumerate_support(self, expand=...) -> Tensor: ...
