__all__ = ["ConstraintRegistry", "biject_to", "transform_to"]

class ConstraintRegistry:
    def __init__(self) -> None: ...
    def register(self, constraint, factory=...) -> Callable[..., Callable[..., Any] | Any]: ...
    def __call__(self, constraint): ...

biject_to = ...
transform_to = ...
