from collections.abc import Callable
from typing import Any

__all__ = [
    "Constraint",
    "MixtureSameFamilyConstraint",
    "boolean",
    "cat",
    "corr_cholesky",
    "dependent",
    "dependent_property",
    "greater_than",
    "greater_than_eq",
    "half_open_interval",
    "independent",
    "integer_interval",
    "interval",
    "is_dependent",
    "less_than",
    "lower_cholesky",
    "lower_triangular",
    "multinomial",
    "nonnegative",
    "nonnegative_integer",
    "one_hot",
    "positive",
    "positive_definite",
    "positive_integer",
    "positive_semidefinite",
    "real",
    "real_vector",
    "simplex",
    "square",
    "stack",
    "symmetric",
    "unit_interval",
]

class Constraint:
    is_discrete = ...
    event_dim = ...
    def check(self, value): ...

class _Dependent(Constraint):
    def __init__(self, *, is_discrete=..., event_dim=...) -> None: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def event_dim(self) -> int: ...
    def __call__(self, *, is_discrete=..., event_dim=...) -> _Dependent: ...
    def check(self, x): ...

def is_dependent(constraint) -> bool: ...

class _DependentProperty(property, _Dependent):
    def __init__(
        self, fn: Callable[..., Any] | None = ..., *, is_discrete: bool | None = ..., event_dim: int | None = ...
    ) -> None: ...
    def __call__(self, fn: Callable[..., Any]) -> _DependentProperty: ...

class _IndependentConstraint(Constraint):
    def __init__(self, base_constraint, reinterpreted_batch_ndims) -> None: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def event_dim(self) -> int: ...
    def check(self, value): ...

class MixtureSameFamilyConstraint(Constraint):
    def __init__(self, base_constraint) -> None: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def event_dim(self) -> int: ...
    def check(self, value): ...

class _Boolean(Constraint):
    is_discrete = ...
    def check(self, value): ...

class _OneHot(Constraint):
    is_discrete = ...
    event_dim = ...
    def check(self, value): ...

class _IntegerInterval(Constraint):
    is_discrete = ...
    def __init__(self, lower_bound, upper_bound) -> None: ...
    def check(self, value): ...

class _IntegerLessThan(Constraint):
    is_discrete = ...
    def __init__(self, upper_bound) -> None: ...
    def check(self, value): ...

class _IntegerGreaterThan(Constraint):
    is_discrete = ...
    def __init__(self, lower_bound) -> None: ...
    def check(self, value): ...

class _Real(Constraint):
    def check(self, value): ...

class _GreaterThan(Constraint):
    def __init__(self, lower_bound) -> None: ...
    def check(self, value): ...

class _GreaterThanEq(Constraint):
    def __init__(self, lower_bound) -> None: ...
    def check(self, value): ...

class _LessThan(Constraint):
    def __init__(self, upper_bound) -> None: ...
    def check(self, value): ...

class _Interval(Constraint):
    def __init__(self, lower_bound, upper_bound) -> None: ...
    def check(self, value): ...

class _HalfOpenInterval(Constraint):
    def __init__(self, lower_bound, upper_bound) -> None: ...
    def check(self, value): ...

class _Simplex(Constraint):
    event_dim = ...
    def check(self, value): ...

class _Multinomial(Constraint):
    is_discrete = ...
    event_dim = ...
    def __init__(self, upper_bound) -> None: ...
    def check(self, x): ...

class _LowerTriangular(Constraint):
    event_dim = ...
    def check(self, value): ...

class _LowerCholesky(Constraint):
    event_dim = ...
    def check(self, value): ...

class _CorrCholesky(Constraint):
    event_dim = ...
    def check(self, value): ...

class _Square(Constraint):
    event_dim = ...
    def check(self, value) -> Tensor: ...

class _Symmetric(_Square):
    def check(self, value) -> Tensor: ...

class _PositiveSemidefinite(_Symmetric):
    def check(self, value) -> Tensor: ...

class _PositiveDefinite(_Symmetric):
    def check(self, value) -> Tensor: ...

class _Cat(Constraint):
    def __init__(self, cseq, dim=..., lengths=...) -> None: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def event_dim(self) -> int: ...
    def check(self, value) -> Tensor: ...

class _Stack(Constraint):
    def __init__(self, cseq, dim=...) -> None: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def event_dim(self) -> int: ...
    def check(self, value) -> Tensor: ...

dependent = ...
dependent_property = _DependentProperty
independent = _IndependentConstraint
boolean = ...
one_hot = ...
nonnegative_integer = ...
positive_integer = ...
integer_interval = _IntegerInterval
real = ...
real_vector = independent(real, 1)
positive = ...
nonnegative = ...
greater_than = _GreaterThan
greater_than_eq = _GreaterThanEq
less_than = _LessThan
multinomial = _Multinomial
unit_interval = ...
interval = _Interval
half_open_interval = _HalfOpenInterval
simplex = ...
lower_triangular = ...
lower_cholesky = ...
corr_cholesky = ...
square = ...
symmetric = ...
positive_semidefinite = ...
positive_definite = ...
cat = _Cat
stack = _Stack
