import torch
from torch import Tensor
from torch.distributions.exp_family import ExponentialFamily
from torch.distributions.utils import lazy_property
from torch.types import Number, _size

__all__ = ["ContinuousBernoulli"]

class ContinuousBernoulli(ExponentialFamily):
    arg_constraints = ...
    support = ...
    _mean_carrier_measure = ...
    has_rsample = ...
    def __init__(
        self,
        probs: Tensor | Number | None = ...,
        logits: Tensor | Number | None = ...,
        lims: tuple[float, float] = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def stddev(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    @lazy_property
    def logits(self) -> Tensor: ...
    @lazy_property
    def probs(self) -> Tensor: ...
    @property
    def param_shape(self) -> torch.Size: ...
    def sample(self, sample_shape=...) -> Tensor: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, value) -> Tensor: ...
    def entropy(self) -> Tensor: ...
