from torch import Tensor
from torch.autograd import Function
from torch.autograd.function import once_differentiable
from torch.distributions.exp_family import ExponentialFamily
from torch.types import _size

__all__ = ["Dirichlet"]

class _Dirichlet(Function):
    @staticmethod
    def forward(ctx, concentration) -> Tensor: ...
    @staticmethod
    @once_differentiable
    def backward(ctx, grad_output): ...

class Dirichlet(ExponentialFamily):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    def __init__(self, concentration: Tensor, validate_args: bool | None = ...) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def entropy(self) -> Tensor: ...
