from warnings import deprecated

import torch
from torch import Tensor
from torch.distributions import constraints
from torch.types import _size

__all__ = ["Distribution"]

class Distribution:
    has_rsample = ...
    has_enumerate_support = ...
    _validate_args = ...
    @staticmethod
    def set_default_validate_args(value: bool) -> None: ...
    def __init__(
        self,
        batch_shape: torch.Size = ...,
        event_shape: torch.Size = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape: _size, _instance=...): ...
    @property
    def batch_shape(self) -> torch.Size: ...
    @property
    def event_shape(self) -> torch.Size: ...
    @property
    def arg_constraints(self) -> dict[str, constraints.Constraint]: ...
    @property
    def support(self) -> constraints.Constraint | None: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    @property
    def stddev(self) -> Tensor: ...
    def sample(self, sample_shape: _size = ...) -> Tensor: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    @deprecated(
        "`sample_n(n)` will be deprecated. Use `sample((n,))` instead.",
        category=FutureWarning,
    )
    def sample_n(self, n: int) -> Tensor: ...
    def log_prob(self, value: Tensor) -> Tensor: ...
    def cdf(self, value: Tensor) -> Tensor: ...
    def icdf(self, value: Tensor) -> Tensor: ...
    def enumerate_support(self, expand: bool = ...) -> Tensor: ...
    def entropy(self) -> Tensor: ...
    def perplexity(self) -> Tensor: ...
