from torch import Tensor
from torch.distributions.exp_family import ExponentialFamily
from torch.types import _size

__all__ = ["Exponential"]

class Exponential(ExponentialFamily):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    _mean_carrier_measure = ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def stddev(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def __init__(self, rate: Tensor | float, validate_args: bool | None = ...) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, value) -> Tensor: ...
    def entropy(self) -> Tensor: ...
