from torch import Tensor
from torch.distributions.distribution import Distribution
from torch.types import _size

__all__ = ["FisherSnedecor"]

class FisherSnedecor(Distribution):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    def __init__(
        self,
        df1: Tensor | float,
        df2: Tensor | float,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
