from torch.distributions import Distribution, constraints

__all__ = ["GeneralizedPareto"]

class GeneralizedPareto(Distribution):
    arg_constraints = ...
    has_rsample = ...
    def __init__(self, loc, scale, concentration, validate_args=...) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    def rsample(self, sample_shape=...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def log_survival_function(self, value) -> Tensor: ...
    def log_cdf(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, value) -> Tensor: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def entropy(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @constraints.dependent_property(is_discrete=False, event_dim=0)
    def support(self) -> interval: ...
