from torch import Tensor
from torch.distributions.transformed_distribution import TransformedDistribution

__all__ = ["Gumbel"]

class Gumbel(TransformedDistribution):
    arg_constraints = ...
    support = ...
    def __init__(
        self,
        loc: Tensor | float,
        scale: Tensor | float,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    def log_prob(self, value): ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def stddev(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def entropy(self) -> Tensor: ...
