from torch import Tensor
from torch.distributions.normal import Normal
from torch.distributions.transformed_distribution import TransformedDistribution

__all__ = ["HalfNormal"]

class HalfNormal(TransformedDistribution):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    base_dist: Normal
    def __init__(self, scale: Tensor | float, validate_args: bool | None = ...) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def scale(self) -> Tensor: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, prob) -> Tensor: ...
    def entropy(self) -> Tensor: ...
