from typing import TypeVar

from torch import Tensor
from torch.distributions import constraints
from torch.distributions.distribution import Distribution
from torch.types import _size

__all__ = ["Independent"]
D = TypeVar("D", bound=Distribution)

class Independent[D: Distribution](Distribution):
    arg_constraints: dict[str, constraints.Constraint] = ...
    base_dist: D
    def __init__(
        self,
        base_distribution: D,
        reinterpreted_batch_ndims: int,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def has_rsample(self) -> bool: ...
    @property
    def has_enumerate_support(self) -> bool: ...
    @constraints.dependent_property
    def support(self) -> independent | Constraint | None: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def sample(self, sample_shape=...) -> Tensor: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def entropy(self) -> Tensor: ...
    def enumerate_support(self, expand=...) -> Tensor: ...
