from torch import Tensor
from torch.distributions import Categorical, constraints
from torch.distributions.distribution import Distribution

__all__ = ["MixtureSameFamily"]

class MixtureSameFamily(Distribution):
    arg_constraints: dict[str, constraints.Constraint] = ...
    has_rsample = ...
    def __init__(
        self, mixture_distribution: Categorical, component_distribution: Distribution, validate_args: bool | None = ...
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @constraints.dependent_property
    def support(self) -> MixtureSameFamilyConstraint: ...
    @property
    def mixture_distribution(self) -> Categorical: ...
    @property
    def component_distribution(self) -> Distribution: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def cdf(self, x) -> Tensor: ...
    def log_prob(self, x) -> Tensor: ...
    def sample(self, sample_shape=...) -> Tensor: ...
