import torch
from torch import Tensor
from torch.distributions.distribution import Distribution
from torch.distributions.utils import lazy_property

__all__ = ["NegativeBinomial"]

class NegativeBinomial(Distribution):
    arg_constraints = ...
    support = ...
    def __init__(
        self,
        total_count: Tensor | float,
        probs: Tensor | None = ...,
        logits: Tensor | None = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    @lazy_property
    def logits(self) -> Tensor: ...
    @lazy_property
    def probs(self) -> Tensor: ...
    @property
    def param_shape(self) -> torch.Size: ...
    def sample(self, sample_shape=...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
