import torch
from torch import Tensor
from torch.distributions.distribution import Distribution
from torch.types import _size

__all__ = ["OneHotCategorical", "OneHotCategoricalStraightThrough"]

class OneHotCategorical(Distribution):
    arg_constraints = ...
    support = ...
    has_enumerate_support = ...
    def __init__(
        self, probs: Tensor | None = ..., logits: Tensor | None = ..., validate_args: bool | None = ...
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def probs(self) -> Tensor: ...
    @property
    def logits(self) -> Tensor: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    @property
    def param_shape(self) -> torch.Size: ...
    def sample(self, sample_shape=...) -> Tensor: ...
    def log_prob(self, value) -> Any: ...
    def entropy(self) -> Tensor: ...
    def enumerate_support(self, expand=...) -> Tensor: ...

class OneHotCategoricalStraightThrough(OneHotCategorical):
    has_rsample = ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
