from torch import Tensor
from torch.distributions import constraints
from torch.distributions.transformed_distribution import TransformedDistribution
from torch.types import _size

__all__ = ["Pareto"]

class Pareto(TransformedDistribution):
    arg_constraints = ...
    def __init__(self, scale: Tensor | float, alpha: Tensor | float, validate_args: bool | None = ...) -> None: ...
    def expand(self, batch_shape: _size, _instance: Pareto | None = ...) -> Pareto: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    @constraints.dependent_property(is_discrete=False, event_dim=0)
    def support(self) -> constraints.Constraint: ...
    def entropy(self) -> Tensor: ...
