import torch
from torch import Tensor
from torch.distributions.distribution import Distribution
from torch.distributions.transformed_distribution import TransformedDistribution
from torch.distributions.utils import lazy_property
from torch.types import Number, _size

__all__ = ["LogitRelaxedBernoulli", "RelaxedBernoulli"]

class LogitRelaxedBernoulli(Distribution):
    arg_constraints = ...
    support = ...
    def __init__(
        self,
        temperature: Tensor,
        probs: Tensor | Number | None = ...,
        logits: Tensor | Number | None = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @lazy_property
    def logits(self) -> Tensor: ...
    @lazy_property
    def probs(self) -> Tensor: ...
    @property
    def param_shape(self) -> torch.Size: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...

class RelaxedBernoulli(TransformedDistribution):
    arg_constraints = ...
    support = ...
    has_rsample = ...
    base_dist: LogitRelaxedBernoulli
    def __init__(
        self,
        temperature: Tensor,
        probs: Tensor | Number | None = ...,
        logits: Tensor | Number | None = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @property
    def temperature(self) -> Tensor: ...
    @property
    def logits(self) -> Tensor: ...
    @property
    def probs(self) -> Tensor: ...
