from torch import Tensor
from torch.distributions import constraints
from torch.distributions.distribution import Distribution
from torch.distributions.transforms import Transform
from torch.types import _size

__all__ = ["TransformedDistribution"]

class TransformedDistribution(Distribution):
    arg_constraints: dict[str, constraints.Constraint] = ...
    def __init__(
        self, base_distribution: Distribution, transforms: Transform | list[Transform], validate_args: bool | None = ...
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @constraints.dependent_property(is_discrete=False)
    def support(self) -> independent | Constraint | None: ...
    @property
    def has_rsample(self) -> bool: ...
    def sample(self, sample_shape=...) -> Tensor | None: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, value) -> Tensor | None: ...
