from torch import Tensor
from torch.distributions import constraints
from torch.distributions.distribution import Distribution
from torch.types import _size

__all__ = ["Uniform"]

class Uniform(Distribution):
    """
    Generates uniformly distributed random samples from the half-open interval
    ``[low, high)``.

    Example::

        >>> m = Uniform(torch.tensor([0.0]), torch.tensor([5.0]))
        >>> m.sample()  # uniformly distributed in the range [0.0, 5.0)
        >>> # xdoctest: +SKIP
        tensor([ 2.3418])

    Args:
        low (float or Tensor): lower range (inclusive).
        high (float or Tensor): upper range (exclusive).
    """

    has_rsample = ...
    @property
    def arg_constraints(self) -> dict[str, less_than | greater_than]: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def stddev(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def __init__(self, low: Tensor | float, high: Tensor | float, validate_args: bool | None = ...) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @constraints.dependent_property(is_discrete=False, event_dim=0)
    def support(self) -> interval: ...
    def rsample(self, sample_shape: _size = ...) -> Tensor: ...
    def log_prob(self, value) -> Tensor: ...
    def cdf(self, value) -> Tensor: ...
    def icdf(self, value) -> Tensor: ...
    def entropy(self) -> Tensor: ...
