from torch import Tensor
from torch.distributions.exp_family import ExponentialFamily
from torch.distributions.utils import lazy_property
from torch.types import Number, _size

__all__ = ["Wishart"]
_log_2 = ...

class Wishart(ExponentialFamily):
    support = ...
    has_rsample = ...
    _mean_carrier_measure = ...
    @property
    def arg_constraints(
        self,
    ) -> dict[str, _PositiveDefinite | _LowerCholesky | greater_than]: ...
    def __init__(
        self,
        df: Tensor | Number,
        covariance_matrix: Tensor | None = ...,
        precision_matrix: Tensor | None = ...,
        scale_tril: Tensor | None = ...,
        validate_args: bool | None = ...,
    ) -> None: ...
    def expand(self, batch_shape, _instance=...) -> Self: ...
    @lazy_property
    def scale_tril(self) -> Tensor: ...
    @lazy_property
    def covariance_matrix(self) -> Tensor: ...
    @lazy_property
    def precision_matrix(self) -> Tensor: ...
    @property
    def mean(self) -> Tensor: ...
    @property
    def mode(self) -> Tensor: ...
    @property
    def variance(self) -> Tensor: ...
    def rsample(self, sample_shape: _size = ..., max_try_correction=...) -> Tensor: ...
    def log_prob(self, value): ...
    def entropy(self) -> Tensor: ...
