from typing import TYPE_CHECKING as _TYPE_CHECKING

from torch.serialization import LoadEndianness as _LoadEndianess

if _TYPE_CHECKING: ...

class load:
    """
    Shim to redirect to main config.
    `config.triton.cudagraphs` maps to _config["triton.cudagraphs"]
    """

    mmap: bool = ...
    endianness: _LoadEndianess | None = ...
    mmap_flags: int | None = ...
    calculate_storage_offsets: bool = ...

class save:
    """
    Shim to redirect to main config.
    `config.triton.cudagraphs` maps to _config["triton.cudagraphs"]
    """

    compute_crc32: bool = ...
    use_pinned_memory_for_d2h: bool = ...
    storage_alignment: int = ...
