from ...audio_utils import AudioInput
from ...processing_utils import ProcessingKwargs, ProcessorMixin, Unpack

class KyutaiSpeechToTextProcessorKwargs(ProcessingKwargs, total=False):
    _defaults = ...

class KyutaiSpeechToTextProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __call__(self, audio: AudioInput | None = ..., **kwargs: Unpack[KyutaiSpeechToTextProcessorKwargs]): ...
    def decode(self, *args, **kwargs): ...
    def batch_decode(self, *args, **kwargs): ...

__all__ = ["KyutaiSpeechToTextProcessor"]
