import torch

from ...image_processing_utils_fast import BaseImageProcessorFast, BatchFeature, DefaultFastImageProcessorKwargs
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import is_torch_available, is_torchvision_available, is_vision_available

"""Fast Image processor class for SigLIP."""
if is_vision_available(): ...
if is_torch_available(): ...
if is_torchvision_available(): ...
logger = ...

class Gemma3FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_pan_and_scan: bool | None
    pan_and_scan_min_crop_size: int | None
    pan_and_scan_max_num_crops: int | None
    pan_and_scan_min_ratio_to_activate: float | None

class Gemma3ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    do_convert_rgb = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_pan_and_scan = ...
    pan_and_scan_min_crop_size = ...
    pan_and_scan_max_num_crops = ...
    pan_and_scan_min_ratio_to_activate = ...
    valid_kwargs = Gemma3FastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[Gemma3FastImageProcessorKwargs]) -> None: ...
    def pan_and_scan_batched(
        self,
        images: torch.Tensor,
        pan_and_scan_min_crop_size: int,
        pan_and_scan_max_num_crops: int,
        pan_and_scan_min_ratio_to_activate: float,
    ):  # -> list[Any] | list[Tensor]:

        ...
    def preprocess(self, images: ImageInput, **kwargs: Unpack[Gemma3FastImageProcessorKwargs]) -> BatchFeature: ...

__all__ = ["Gemma3ImageProcessorFast"]
