_mangle_index = ...

class PackageMangler:
    def __init__(self) -> None: ...
    def mangle(self, name) -> str: ...
    def demangle(self, mangled: str) -> str: ...
    def parent_name(self):  # -> str:
        ...

def is_mangled(name: str) -> bool: ...
def demangle(name: str) -> str: ...
def get_mangle_prefix(name: str) -> str: ...
