import ast

class _ExtractModuleReferences(ast.NodeVisitor):
    @classmethod
    def run(cls, src: str, package: str) -> list[tuple[str, str | None]]: ...
    def __init__(self, package) -> None: ...
    def visit_Import(self, node) -> None: ...
    def visit_ImportFrom(self, node) -> None: ...
    def visit_Call(self, node): ...

find_files_source_depends_on = ...
