__all__ = ["detect_anomaly", "set_detect_anomaly"]

class detect_anomaly:
    def __init__(self, check_nan=...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: object) -> None: ...

class set_detect_anomaly:
    def __init__(self, mode: bool, check_nan: bool = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: object) -> None: ...
