from sympy.core.decorators import _sympifyit
from sympy.core.numbers import Number
from sympy.core.singleton import Singleton

class IntInfinity(Number, metaclass=Singleton):
    is_integer = ...
    is_commutative = ...
    is_number = ...
    is_extended_real = ...
    is_comparable = ...
    is_extended_positive = ...
    is_prime = ...
    _op_priority = ...
    __slots__ = ...
    def __new__(cls): ...
    @_sympifyit("other", NotImplemented)
    def __add__(self, other):  # -> Self:
        ...

    __radd__ = ...
    @_sympifyit("other", NotImplemented)
    def __sub__(self, other):  # -> Self:
        ...
    @_sympifyit("other", NotImplemented)
    def __rsub__(self, other): ...
    @_sympifyit("other", NotImplemented)
    def __mul__(self, other):  # -> Self:
        ...

    __rmul__ = ...
    @_sympifyit("other", NotImplemented)
    def __truediv__(self, other): ...
    def __abs__(self): ...
    def __neg__(self): ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    @_sympifyit("other", NotImplemented)
    def __mod__(self, other):  # -> _NotImplementedType:
        ...

    __rmod__ = ...
    def floor(self):  # -> Self:
        ...
    def ceiling(self):  # -> Self:
        ...

int_oo = ...

class NegativeIntInfinity(Number, metaclass=Singleton):
    _op_priority = ...
    is_integer = ...
    is_extended_real = ...
    is_commutative = ...
    is_comparable = ...
    is_extended_negative = ...
    is_number = ...
    is_prime = ...
    __slots__ = ...
    def __new__(cls): ...
    @_sympifyit("other", NotImplemented)
    def __add__(self, other):  # -> Self:
        ...

    __radd__ = ...
    @_sympifyit("other", NotImplemented)
    def __sub__(self, other):  # -> Self:
        ...
    @_sympifyit("other", NotImplemented)
    def __rsub__(self, other): ...
    @_sympifyit("other", NotImplemented)
    def __mul__(self, other):  # -> Self:
        ...

    __rmul__ = ...
    @_sympifyit("other", NotImplemented)
    def __truediv__(self, other):  # -> Self:
        ...
    def __abs__(self): ...
    def __neg__(self): ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    @_sympifyit("other", NotImplemented)
    def __mod__(self, other):  # -> _NotImplementedType:
        ...

    __rmod__ = ...
    def floor(self):  # -> Self:
        ...
    def ceiling(self):  # -> Self:
        ...
    def as_powers_dict(self):  # -> dict[Any, int]:
        ...
