class ReferenceAnalysis:
    @staticmethod
    def constant(c, dtype): ...
    @staticmethod
    def or_(a, b): ...
    @staticmethod
    def and_(a, b): ...
    @staticmethod
    def eq(a, b): ...
    @classmethod
    def ne(cls, a, b): ...
    @staticmethod
    def lt(a, b): ...
    @staticmethod
    def gt(a, b): ...
    @staticmethod
    def le(a, b): ...
    @staticmethod
    def ge(a, b): ...
    @staticmethod
    def not_(a): ...
    @staticmethod
    def reciprocal(x):  # -> FloatTrueDiv:
        ...
    @staticmethod
    def square(x):  # -> PowByNatural:
        ...
    @staticmethod
    def trunc_to_int(x, dtype):  # -> TruncToInt:
        ...
    @staticmethod
    def ceil_to_int(x, dtype): ...
    @staticmethod
    def floor_to_int(x, dtype): ...
    @staticmethod
    def floor(x): ...
    @staticmethod
    def ceil(x): ...
    @staticmethod
    def to_dtype(x, dtype):  # -> ToFloat:
        ...
    @staticmethod
    def mod(x, y):  # -> Mod:
        ...
    @staticmethod
    def abs(x): ...
    @staticmethod
    def neg(x): ...
    @staticmethod
    def truediv(a, b):  # -> FloatTrueDiv:
        ...
    @staticmethod
    def int_truediv(a, b):  # -> IntTrueDiv:
        ...
    @staticmethod
    def floordiv(a, b):  # -> FloorDiv:
        ...
    @staticmethod
    def truncdiv(a, b): ...
    @staticmethod
    def add(a, b):  # -> Any:
        ...
    @classmethod
    def sym_sum(cls, args): ...
    @staticmethod
    def mul(a, b):  # -> Any:
        ...
    @staticmethod
    def sub(a, b):  # -> Any:
        ...
    @staticmethod
    def exp(x):  # -> OpaqueUnaryFn:
        ...
    @staticmethod
    def log(x):  # -> OpaqueUnaryFn:
        ...
    @staticmethod
    def log2(x):  # -> OpaqueUnaryFn:
        ...
    @staticmethod
    def sqrt(x):  # -> OpaqueUnaryFn:
        ...
    @staticmethod
    def pow(a, b): ...
    @staticmethod
    def pow_by_natural(a, b):  # -> PowByNatural:
        ...
    @staticmethod
    def minimum(a, b):  # -> int:
        ...
    @staticmethod
    def maximum(a, b):  # -> int:
        ...
    @staticmethod
    def round_to_int(a, dtype):  # -> RoundToInt:
        ...
    @staticmethod
    def round_decimal(a, b):  # -> RoundDecimal:
        ...
    @staticmethod
    def bitwise_and(a, b):  # -> BitwiseFn:
        ...
    @staticmethod
    def bitwise_or(a, b):  # -> BitwiseFn:
        ...

class PythonReferenceAnalysis(ReferenceAnalysis):
    @staticmethod
    def constant(c, dtype):  # -> int | float | bool:
        ...
    @staticmethod
    def not_(a): ...
    @classmethod
    def sym_sum(cls, args):  # -> Any | Literal[0]:
        ...
    @staticmethod
    def floordiv(a, b): ...
    @staticmethod
    def mod(x, y): ...
    @staticmethod
    def truncdiv(a, b): ...
    @staticmethod
    def to_dtype(x, dtype):  # -> SymFloat:
        ...
    @staticmethod
    def exp(x): ...
    @staticmethod
    def log(x): ...
    @staticmethod
    def log2(x): ...
    @staticmethod
    def sqrt(x): ...
    @staticmethod
    def minimum(a, b): ...
    @staticmethod
    def maximum(a, b): ...
    @staticmethod
    def floor_to_int(x, dtype): ...
    @staticmethod
    def ceil_to_int(x, dtype): ...
    @staticmethod
    def floor(x):  # -> float:
        ...
    @staticmethod
    def ceil(x):  # -> float:
        ...
    @staticmethod
    def truediv(a, b): ...
    @staticmethod
    def pow(a, b): ...
    @staticmethod
    def pow_by_natural(a, b): ...
    @staticmethod
    def round_to_int(a, dtype): ...
    @staticmethod
    def round_decimal(a, b): ...
    @staticmethod
    def bitwise_and(a, b): ...
    @staticmethod
    def bitwise_or(a, b): ...

class OptimizedPythonReferenceAnalysis(PythonReferenceAnalysis):
    @staticmethod
    def sym_sum(args):  # -> SymInt | SymFloat | SymBool:
        ...

class TensorReferenceAnalysis:
    @staticmethod
    def constant(c, dtype):  # -> Any:
        ...
    @staticmethod
    def or_(a, b):  # -> Any:
        ...
    @staticmethod
    def and_(a, b):  # -> Any:
        ...
    @staticmethod
    def bitwise_and(a, b):  # -> Any:
        ...
    @staticmethod
    def bitwise_or(a, b):  # -> Any:
        ...
    @staticmethod
    def eq(a, b):  # -> Any:
        ...
    @classmethod
    def ne(cls, a, b):  # -> Any:
        ...
    @staticmethod
    def lt(a, b):  # -> Any:
        ...
    @staticmethod
    def gt(a, b):  # -> Any:
        ...
    @staticmethod
    def le(a, b):  # -> Any:
        ...
    @staticmethod
    def ge(a, b):  # -> Any:
        ...
    @staticmethod
    def not_(a):  # -> Any:
        ...
    @staticmethod
    def reciprocal(x):  # -> Any:
        ...
    @staticmethod
    def square(x):  # -> Any:
        ...
    @staticmethod
    def trunc_to_int(x, dtype):  # -> Tensor:
        ...
    @staticmethod
    def ceil_to_int(x, dtype):  # -> Tensor:
        ...
    @staticmethod
    def floor_to_int(x, dtype):  # -> Tensor:
        ...
    @staticmethod
    def floor(x):  # -> Any:
        ...
    @staticmethod
    def ceil(x):  # -> Any:
        ...
    @staticmethod
    def to_dtype(x, dtype):  # -> Tensor:
        ...
    @staticmethod
    def mod(x, y): ...
    @staticmethod
    def abs(x):  # -> Any:
        ...
    @staticmethod
    def neg(x):  # -> Any:
        ...
    @staticmethod
    def truediv(a, b):  # -> Any:
        ...
    @staticmethod
    def int_truediv(a, b): ...
    @staticmethod
    def floordiv(a, b):  # -> Any:
        ...
    @staticmethod
    def truncdiv(a, b): ...
    @staticmethod
    def add(a, b):  # -> Any:
        ...
    @staticmethod
    def mul(a, b):  # -> Any:
        ...
    @staticmethod
    def sub(a, b):  # -> Any:
        ...
    @staticmethod
    def exp(x):  # -> Any:
        ...
    @staticmethod
    def log(x):  # -> Any:
        ...
    @staticmethod
    def log2(x):  # -> Any:
        ...
    @staticmethod
    def sqrt(x):  # -> Any:
        ...
    @staticmethod
    def sin(x):  # -> Any:
        ...
    @staticmethod
    def cos(x):  # -> Any:
        ...
    @staticmethod
    def tanh(x):  # -> Any:
        ...
    @staticmethod
    def sinh(x):  # -> Any:
        ...
    @staticmethod
    def cosh(x):  # -> Any:
        ...
    @staticmethod
    def tan(x):  # -> Any:
        ...
    @staticmethod
    def acos(x):  # -> Any:
        ...
    @staticmethod
    def atan(x):  # -> Any:
        ...
    @staticmethod
    def asin(x):  # -> Any:
        ...
    @staticmethod
    def pow(a, b):  # -> Any:
        ...
    @staticmethod
    def pow_by_natural(a, b):  # -> Any:
        ...
    @staticmethod
    def minimum(a, b):  # -> Any:
        ...
    @staticmethod
    def maximum(a, b):  # -> Any:
        ...
    @staticmethod
    def round_to_int(a, dtype):  # -> Any:
        ...
    @staticmethod
    def round_decimal(a, b): ...
