import sympy
from typing import Optional

log = ...
_MIRROR_REL_OP: dict[type[sympy.Basic], type[sympy.Rel]] = ...
INEQUALITY_TYPES = ...

def mirror_rel_op(type: type) -> type[sympy.Rel] | None: ...
def try_solve(
    expr: sympy.Basic, thing: sympy.Basic, trials: int = ..., floordiv_inequality: bool = ...
) -> tuple[sympy.Rel, sympy.Expr] | None: ...
