import functools
from dataclasses import dataclass
from typing import Any

from torch._inductor.codegen.rocm.ck_tile_template import CKTileTemplate
from torch._inductor.codegen.rocm.rocm_kernel import ROCmTemplateKernel
from torch._inductor.codegen.rocm.rocm_template import ArgInfo
from torch._inductor.ir import Buffer, Layout

from ...utils import IndentedBuffer

log = ...

def is_static_int(number): ...
def torch_layout_to_ck_layout(torch_layout): ...

@dataclass
class CKTileGemmOperation:
    layout_a: str
    layout_b: str
    layout_c: str
    datatype_a: str
    datatype_b: str
    datatype_c: str
    tile_m: int
    tile_n: int
    tile_k: int
    warp_m: int
    warp_n: int
    warp_k: int
    warp_tile_m: int
    warp_tile_n: int
    warp_tile_k: int
    m_is_padded: str
    n_is_padded: str
    k_is_padded: str
    pipeline: str
    scheduler: str
    epilogue: str
    def layout_repr(self): ...
    def dtype_repr(self): ...
    def tile_sizes(self): ...
    def name(self): ...
    def dict_items(self): ...

@functools.cache
def ops(): ...

class CKTileGemmTemplate(CKTileTemplate):
    gemm_template = ...
    def __init__(self, input_nodes: list[Buffer], layout: Layout) -> None: ...
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def check_dtypes(self, op: CKTileGemmOperation): ...
    def check_layouts(self, op: CKTileGemmOperation): ...
    def get_gemm_problem_size(self): ...
    def check_block_tiles(self, op: CKTileGemmOperation): ...
    def check_alignments(self, op: CKTileGemmOperation): ...
    def check_warp_tiles(self, op: CKTileGemmOperation): ...
    def check_block_tile_size(self, op: CKTileGemmOperation): ...
    def filter_op(self, op: CKTileGemmOperation): ...
    def emit_ck_instance(self, op: CKTileGemmOperation): ...
    def render(self, kernel: ROCmTemplateKernel, op: CKTileGemmOperation, **kwargs) -> str: ...
    def gen_ops(self): ...
    @staticmethod
    def add_choices(choices, layout, input_nodes): ...
    def k_batch_choices(self, op: CKTileGemmOperation) -> tuple[int, ...]: ...
    def size_args(self): ...
    def get_runtime_arg_info(self) -> list[ArgInfo]: ...
    def get_runtime_arg_values(self, **kwargs: Any) -> list[Any]: ...
