from torch._inductor.codegen.rocm.rocm_template import ROCmTemplate
from torch._inductor.ir import IRNode
from torch._inductor.utils import IndentedBuffer

class CKTileTemplate(ROCmTemplate):
    _TORCH_DTYPE_TO_CK = ...
    ck_dtype_to_size = ...
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def torch_type_to_ck(self, node: IRNode, ptr: str) -> str: ...
