from typing import Optional

from torch._inductor.codegen.rocm.ck_template import CKTemplate
from torch._inductor.codegen.rocm.rocm_kernel import ROCmTemplateKernel
from torch._inductor.ir import Buffer, Layout

from ...utils import IndentedBuffer

log = ...
InductorROCmOp = ...
padding_lookup = ...

def is_static_int(number):  # -> bool:
    ...
def torch_layout_to_ck_layout(torch_layout):  # -> Literal['Row', 'Col'] | None:
    ...

class CKGemmTemplate(CKTemplate):
    gemm_template = ...
    standalone_runner_template = ...
    def __init__(
        self,
        input_nodes: list[Buffer],
        layout: Layout,
        alpha: float,
        beta: float,
        input_reorder: list[int] | None = ...,
    ) -> None: ...
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def inline_utils(self):  # -> IndentedBuffer:
        ...
    def filter_op(self, op_info: InductorROCmOp):  # -> None:

        ...
    def emit_ck_instance(self, op: CKGemmOperation):  # -> tuple[Any, Any]:
        ...
    def render(self, kernel: ROCmTemplateKernel, op: CKGemmOperation, **kwargs) -> str: ...
    def gen_ops(self) -> list[InductorROCmOp]: ...
    @staticmethod
    def add_ck_gemm_choices(choices, layout, input_nodes, alpha=..., beta=..., input_reorder=...):  # -> None:

        ...
    def size_args(
        self,
    ):  # -> tuple[Any, Any, Any, Any, Any, Any, Any, Any | Literal[0]] | tuple[Any, Any, Any, Any, Any, Any, Any | Literal[0]]:
        ...
