from typing import Literal

from ...tokenization_utils_fast import PreTrainedTokenizerFast

logger = ...
VOCAB_FILES_NAMES = ...
PRETRAINED_VOCAB_FILES_MAP = ...
DEFAULT_SYSTEM_PROMPT = ...
DEFAULT_RAG_PREAMBLE = ...

class CohereTokenizerFast(PreTrainedTokenizerFast):
    vocab_files_names = ...
    pretrained_vocab_files_map = ...
    padding_side = ...
    model_input_names = ...
    slow_tokenizer_class = ...
    def __init__(
        self,
        vocab_file=...,
        merges_file=...,
        tokenizer_file=...,
        clean_up_tokenization_spaces=...,
        unk_token=...,
        bos_token=...,
        eos_token=...,
        add_bos_token=...,
        add_eos_token=...,
        use_default_system_prompt=...,
        add_prefix_space=...,
        **kwargs,
    ) -> None: ...
    def update_post_processor(self):  # -> None:

        ...
    @property
    def add_eos_token(self):  # -> bool:
        ...
    @property
    def add_bos_token(self):  # -> bool:
        ...
    @add_eos_token.setter
    def add_eos_token(self, value):  # -> None:
        ...
    @add_bos_token.setter
    def add_bos_token(self, value):  # -> None:
        ...
    def apply_tool_use_template(
        self, conversation: list[dict[str, str]], tools: list[dict], **kwargs
    ) -> str | list[int]: ...
    def apply_grounded_generation_template(
        self,
        conversation: list[dict[str, str]],
        documents: list[dict],
        citation_mode: Literal["fast", "accurate"] = ...,
        **kwargs,
    ) -> str | list[int]: ...
    def build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=...):  # -> list[str | list[str] | Any | None]:
        ...

__all__ = ["CohereTokenizerFast"]
