import torch
from typing import Union, TypeAlias
from torch._inductor.codegen.common import CSEVariable, OpOverrides

"""
CuteDSL-specific operation overrides for pointwise operations.

This module provides CuteDSL implementations of common operations used in
template kernels, particularly for flex attention modifications.
"""
CuteDSLArg: TypeAlias = Union[CSEVariable, str]

def upcast_compute_type(dtype: torch.dtype) -> torch.dtype: ...

class CuteDSLOpOverrides(OpOverrides):
    TORCH_TO_CUTE_DTYPE = ...
    LOG2_E = ...
    @staticmethod
    def constant(value: Union[bool, float], dtype: torch.dtype) -> str: ...
    @staticmethod
    def add(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def mul(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def sub(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def truediv(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def mod(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def remainder(a, b):  # -> CuteDSLArg:
        ...
    @staticmethod
    def exp(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def sqrt(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def log(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def cos(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def sin(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def erf(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def maximum(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def minimum(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def where(condition: CuteDSLArg, a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def pow(a: CuteDSLArg, b: CuteDSLArg):  # -> CuteDSLArg:
        ...
    @staticmethod
    def abs(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def neg(x: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def to_dtype(x: CuteDSLArg, dtype: torch.dtype, src_dtype=..., use_compute_types=...) -> CuteDSLArg: ...
    @staticmethod
    def tanh(x0: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def logical_and(x0: CuteDSLArg, x1: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def logical_or(x0: CuteDSLArg, x1: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def logical_not(a):  # -> CuteDSLArg:

        ...
    @staticmethod
    def eq(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def ne(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def lt(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def le(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def gt(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
    @staticmethod
    def ge(a: CuteDSLArg, b: CuteDSLArg) -> CuteDSLArg: ...
