import contextlib
import dataclasses
import sympy
from typing import Any, Callable, Optional
from torch._inductor.codegen.common import CSEVariable, IndentedBuffer, Kernel
from torch._inductor.ir import Buffer
from torch._inductor.ops_handler import StoreMode
from torch._inductor.virtualized import V

MAIN_SUFFIX = ...
log = ...
kernel_code_log = ...

class CuteDSLKernelWrapper:
    def __init__(self, kernel_fn: Callable[..., Any], kernel_path: Optional[str] = ...) -> None: ...
    def run(self, *args, stream=..., **kwargs):  # -> Any:

        ...

@dataclasses.dataclass
class CuteDSLSubgraphInfo:
    body: IndentedBuffer
    template_mask: Optional[str] = ...
    template_out: Optional[str] = ...
    def to_dict(self):  # -> dict[str, Any]:
        ...

class CuteDSLTemplateKernel(Kernel):
    def __init__(
        self, kernel_name: str, input_nodes: list[Buffer], output_node: Buffer, subgraphs: Optional[list[Buffer]] = ...
    ) -> None: ...
    def gen_imports(self) -> str: ...
    def gen_defines(self, **kwargs) -> str: ...
    def render(self, template, **kwargs):  # -> PartialRender:
        ...
    @contextlib.contextmanager
    def set_subgraph_body(self, body_name: str):  # -> Generator[None, Any, None]:

        ...
    @contextlib.contextmanager
    def create_subgraph_body(self, body_name: str):  # -> Generator[None, Any, None]:

        ...
    def def_kernel(self, *argnames):  # -> Literal['<DEF_KERNEL>']:

        ...
    def get_output(self):  # -> str | RemovedArg:

        ...
    def call_kernel(self, name: str, node=...):  # -> None:

        ...
    def modification(
        self, subgraph_number: int, output_name: Optional[str], mask: Optional[str] = ..., **fixed_inputs
    ) -> str: ...

class ModificationWrapperCuteDSL(V.WrapperHandler):
    def __init__(self, kernel, subgraph_number: int, fixed_inputs: dict[str, Any], mask: Optional[str]) -> None: ...
    def load(self, name: str, index: sympy.Expr): ...
    def indirect_indexing(self, index_var: str, size, check, wrap_neg=...): ...
    def store(self, name: str, index: sympy.Expr, value: CSEVariable, mode: StoreMode = ...) -> str: ...
