from typing import Any

from torch._inductor.autoheuristic.autoheuristic_utils import AHContext, AHMetadata, Choice
from torch._inductor.autoheuristic.learnedheuristic_interface import LearnedHeuristic

def find_and_instantiate_subclasses(package_name: str, base_class: Any) -> list[LearnedHeuristic]: ...

class LearnedHeuristicController:
    existing_heuristics: dict[str, list[LearnedHeuristic]] = ...
    heuristics_initialized: bool = ...
    def __init__(self, metadata: AHMetadata, context: AHContext) -> None: ...
    def get_heuristics(self, name: str) -> list[LearnedHeuristic]: ...
    def get_decision(self) -> Choice | None: ...
    def get_decisions_ranked(self, top_k: int) -> list[Choice] | None: ...
