from ...tokenization_utils_fast import PreTrainedTokenizer

"""Tokenization classes for GPTNeoXJapanese."""
logger = ...
VOCAB_FILES_NAMES = ...

def load_vocab_and_emoji(
    vocab_file, emoji_file
):  # -> tuple[OrderedDict[Any, Any], OrderedDict[Any, Any], OrderedDict[Any, Any], Any]:

    ...

class GPTNeoXJapaneseTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(
        self,
        vocab_file,
        emoji_file,
        unk_token=...,
        pad_token=...,
        bos_token=...,
        eos_token=...,
        do_clean_text=...,
        **kwargs,
    ) -> None: ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, int]:
        ...
    def convert_tokens_to_string(self, tokens):  # -> str:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

class SubWordJapaneseTokenizer:
    def __init__(self, vocab, ids_to_tokens, emoji) -> None: ...
    def __len__(self) -> int:  # -> int:
        ...
    def clean_text(self, content):  # -> str:
        ...
    def tokenize(self, text, clean=...):  # -> list[Any]:
        ...
    def convert_id_to_token(self, index, breakline=...):  # -> LiteralString:
        ...

__all__ = ["GPTNeoXJapaneseTokenizer"]
