import functools

def autograd_kernel_indirection(custom_op):  # -> Callable[..., Any]:
    ...
def autograd_not_implemented(custom_op):  # -> Callable[..., Any]:
    ...
def mark_non_differentiable(ctx, output, output_differentiability):  # -> None:
    ...
def construct_autograd_kernel(
    schema, output_differentiability, custom_op, op_overload, save_for_backward_fn, backward_fn
):  # -> Callable[..., PyTree]:
    ...
def gen_autograd_function(name, forward, backward):  # -> Any:
    ...
@functools.lru_cache
def namedtuple_args_cls(schema):  # -> type[namedtuple]:
    ...
def namedtuple_args(schema, args):  # -> namedtuple:
    ...
def validate_grad_inputs_dict(grad_inputs_dict, forward_op, args_info):  # -> None:
    ...
def grad_inputs_dict_to_flat_tuple(grad_inputs_dict, args_info):  # -> tuple[Any, ...]:
    ...
def save_pytree_for_backward(ctx, stuff):  # -> None:
    ...
def unpack_saved(ctx):  # -> PyTree:
    ...
