from ...tokenization_utils import PreTrainedTokenizer

"""Tokenization classes for OpenAI GPT."""
logger = ...
VOCAB_FILES_NAMES = ...

def whitespace_tokenize(text):  # -> list[Any]:

    ...

class BasicTokenizer:
    def __init__(
        self, do_lower_case=..., never_split=..., tokenize_chinese_chars=..., strip_accents=..., do_split_on_punc=...
    ) -> None: ...
    def tokenize(self, text, never_split=...):  # -> list[Any] | list[LiteralString]:

        ...

def get_pairs(word):  # -> set[Any]:

    ...
def text_standardize(text):  # -> str:

    ...

class OpenAIGPTTokenizer(PreTrainedTokenizer):
    vocab_files_names = ...
    model_input_names = ...
    def __init__(self, vocab_file, merges_file, unk_token=..., **kwargs) -> None: ...
    @property
    def do_lower_case(self):  # -> Literal[True]:
        ...
    @property
    def vocab_size(self):  # -> int:
        ...
    def get_vocab(self):  # -> dict[str, Any]:
        ...
    def bpe(self, token):  # -> LiteralString | Literal['\n</w>']:
        ...
    def convert_tokens_to_string(self, tokens):  # -> str:

        ...
    def save_vocabulary(self, save_directory: str, filename_prefix: str | None = ...) -> tuple[str]: ...

__all__ = ["OpenAIGPTTokenizer"]
