from collections.abc import Callable

import jinja2

from .import_utils import is_jinja_available, is_torch_available, is_vision_available

logger = ...
if is_jinja_available(): ...
else:
    jinja2 = ...
if is_vision_available(): ...
if is_torch_available(): ...
BASIC_TYPES = ...
description_re = ...
args_re = ...
args_split_re = ...
returns_re = ...

class TypeHintParsingException(Exception): ...
class DocstringParsingException(Exception): ...

def parse_google_format_docstring(docstring: str) -> tuple[str | None, dict | None, str | None]: ...
def get_json_schema(func: Callable) -> dict: ...
def render_jinja_template(
    conversations: list[list[dict[str, str]]],
    tools: list[dict | Callable] | None = ...,
    documents: list[dict[str, str]] | None = ...,
    chat_template: str | None = ...,
    return_assistant_tokens_mask: bool | None = ...,
    continue_final_message: bool | None = ...,
    add_generation_prompt: bool | None = ...,
    **kwargs,
) -> str: ...
