from ..utils import DummyObject

class FlaxForcedBOSTokenLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxForcedEOSTokenLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxForceTokensLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGenerationMixin(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsProcessorList(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsWarper(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMinLengthLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxSuppressTokensAtBeginLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxSuppressTokensLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTemperatureLogitsWarper(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTopKLogitsWarper(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTopPLogitsWarper(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxWhisperTimeStampLogitsProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxPreTrainedModel(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...
