from ..utils import DummyObject

class BaseImageProcessorFast(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class BaseVideoProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...
