from ..utils import DummyObject

class ImageProcessingMixin(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class BaseImageProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...

class ImageFeatureExtractionMixin(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None: ...
