import functools
import logging

"""Logging utilities."""
_lock = ...
_default_handler: logging.Handler | None = ...
log_levels = ...
_default_log_level = ...
_tqdm_active = ...

def get_log_levels_dict():  # -> dict[str, int]:
    ...
def captureWarnings(capture):  # -> None:

    ...
def get_logger(name: str | None = ...) -> logging.Logger: ...
def get_verbosity() -> int: ...
def set_verbosity(verbosity: int) -> None: ...
def set_verbosity_info():  # -> None:

    ...
def set_verbosity_warning():  # -> None:

    ...
def set_verbosity_debug():  # -> None:

    ...
def set_verbosity_error():  # -> None:

    ...
def disable_default_handler() -> None: ...
def enable_default_handler() -> None: ...
def add_handler(handler: logging.Handler) -> None: ...
def remove_handler(handler: logging.Handler) -> None: ...
def disable_propagation() -> None: ...
def enable_propagation() -> None: ...
def enable_explicit_format() -> None: ...
def reset_format() -> None: ...
def warning_advice(self, *args, **kwargs):  # -> None:

    ...
@functools.lru_cache(None)
def warning_once(self, *args, **kwargs):  # -> None:

    ...
@functools.lru_cache(None)
def info_once(self, *args, **kwargs):  # -> None:

    ...

class EmptyTqdm:
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def __getattr__(self, _):  # -> Callable[..., None]:

        ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, type_, value, traceback):  # -> None:
        ...

class _tqdm_cls:
    def __call__(self, *args, **kwargs):  # -> tqdm | EmptyTqdm:
        ...
    def set_lock(self, *args, **kwargs):  # -> None:
        ...
    def get_lock(self):  # -> None:
        ...

tqdm = ...

def is_progress_bar_enabled() -> bool: ...
def enable_progress_bar():  # -> None:

    ...
def disable_progress_bar():  # -> None:

    ...
