from typing import Optional
from ..trainer_callback import TrainerCallback

def format_time(t):  # -> str:

    ...
def html_progress_bar(value, total, prefix, label, width=...):  # -> str:
    ...
def text_to_html_table(items):  # -> str:

    ...

class NotebookProgressBar:
    warmup = ...
    update_every = ...
    def __init__(
        self,
        total: int,
        prefix: Optional[str] = ...,
        leave: bool = ...,
        parent: Optional[NotebookTrainingTracker] = ...,
        width: int = ...,
    ) -> None: ...
    def update(self, value: int, force_update: bool = ..., comment: Optional[str] = ...):  # -> None:

        ...
    def update_bar(self, value, comment=...):  # -> None:
        ...
    def display(self):  # -> None:
        ...
    def close(self):  # -> None:

        ...

class NotebookTrainingTracker(NotebookProgressBar):
    def __init__(self, num_steps, column_names=...) -> None: ...
    def display(self):  # -> None:
        ...
    def write_line(self, values):  # -> None:

        ...
    def add_child(self, total, prefix=..., width=...):  # -> NotebookProgressBar:

        ...
    def remove_child(self):  # -> None:

        ...

class NotebookProgressCallback(TrainerCallback):
    def __init__(self) -> None: ...
    def on_train_begin(self, args, state, control, **kwargs):  # -> None:
        ...
    def on_step_end(self, args, state, control, **kwargs):  # -> None:
        ...
    def on_prediction_step(self, args, state, control, eval_dataloader=..., **kwargs):  # -> None:
        ...
    def on_predict(self, args, state, control, **kwargs):  # -> None:
        ...
    def on_log(self, args, state, control, logs=..., **kwargs):  # -> None:
        ...
    def on_evaluate(self, args, state, control, metrics=..., **kwargs):  # -> None:
        ...
    def on_train_end(self, args, state, control, **kwargs):  # -> None:
        ...
