from collections import OrderedDict
from collections import abc as container_abcs
from collections.abc import Iterable, Iterator, Mapping
from typing import Any, Self, overload

from torch._jit_internal import _copy_to_script_wrapper

from indextts.util import patch_call

from .module import Module

__all__ = ["Container", "ModuleDict", "ModuleList", "ParameterDict", "ParameterList", "Sequential"]

class Container(Module):
    def __init__(self, **kwargs: Any) -> None: ...

class Sequential[T: Module](Module):
    @overload
    def __init__(self, *args: T) -> None: ...
    @overload
    def __init__(self, arg: OrderedDict[str, T]) -> None: ...
    @_copy_to_script_wrapper
    def __getitem__(self, idx: slice | int) -> Self | T: ...
    def __setitem__(self, idx: int, module: T) -> None: ...
    def __delitem__(self, idx: slice | int) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    def __add__(self, other) -> Self: ...
    def pop(self, key: int | slice) -> T: ...
    def __iadd__(self, other) -> Self: ...
    def __mul__(self, other: int) -> Self: ...
    def __rmul__(self, other: int) -> Self: ...
    def __imul__(self, other: int) -> Self: ...
    @_copy_to_script_wrapper
    def __dir__(self) -> list[str]: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[T]: ...
    def forward(self, input): ...
    @patch_call(forward)
    def __call__(self) -> None: ...
    def append(self, module: T) -> Self: ...
    def insert(self, index: int, module: T) -> Self: ...
    def extend(self, sequential: Iterable[T]) -> Self: ...

class ModuleList[T: Module](Module):
    def __init__(self, modules: Iterable[T] | None = None) -> None: ...
    @overload
    def __getitem__(self, idx: slice) -> Self: ...
    @overload
    def __getitem__(self, idx: int) -> T: ...
    def __setitem__(self, idx: int, module: T) -> None: ...
    def __delitem__(self, idx: int | slice) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[T]: ...
    def __iadd__(self, modules: Iterable[T]) -> Self: ...
    def __add__(self, other: Iterable[T]) -> Self: ...
    @_copy_to_script_wrapper
    def __dir__(self) -> list[str]: ...
    def insert(self, index: int, module: T) -> None: ...
    def append(self, module: T) -> Self: ...
    def pop(self, key: int | slice) -> T: ...
    def extend(self, modules: Iterable[T]) -> Self: ...

class ModuleDict(Module):
    def __init__(self, modules: Mapping[str, Module] | None = None) -> None: ...
    @_copy_to_script_wrapper
    def __getitem__(self, key: str) -> Module: ...
    def __setitem__(self, key: str, module: Module) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[str]: ...
    @_copy_to_script_wrapper
    def __contains__(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Module: ...
    @_copy_to_script_wrapper
    def keys(self) -> container_abcs.KeysView[str]: ...
    @_copy_to_script_wrapper
    def items(self) -> container_abcs.ItemsView[str, Module]: ...
    @_copy_to_script_wrapper
    def values(self) -> container_abcs.ValuesView[Module]: ...
    def update(self, modules: Mapping[str, Module]) -> None: ...

class ParameterList[T](Module):
    def __init__(self, values: Iterable[Any] | None = None) -> None: ...
    @overload
    def __getitem__(self, idx: int) -> Any: ...
    @overload
    def __getitem__(self, idx: slice) -> T: ...
    def __setitem__(self, idx: int, param: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __iadd__(self, parameters: Iterable[Any]) -> Self: ...
    def __dir__(self) -> list[str]: ...
    def append(self, value: Any) -> Self: ...
    def extend(self, values: Iterable[Any]) -> Self: ...
    def extra_repr(self) -> str: ...
    def __call__(self, *args, **kwargs) -> None: ...

class ParameterDict(Module):
    def __init__(self, parameters: Any = None) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __reversed__(self) -> Iterator[str]: ...
    def copy(self) -> ParameterDict: ...
    def __contains__(self, key: str) -> bool: ...
    def setdefault(self, key: str, default: Any | None = None) -> Any: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Any: ...
    def popitem(self) -> tuple[str, Any]: ...
    def get(self, key: str, default: Any | None = None) -> Any: ...
    def fromkeys(self, keys: Iterable[str], default: Any | None = None) -> ParameterDict: ...
    def keys(self) -> container_abcs.KeysView[str]: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def values(self) -> Iterable[Any]: ...
    def update(self, parameters: Mapping[str, Any] | ParameterDict) -> None: ...
    def extra_repr(self) -> str: ...
    def __call__(self, input) -> None: ...
    def __or__(self, other: ParameterDict) -> ParameterDict: ...
    def __ror__(self, other: ParameterDict) -> ParameterDict: ...
    def __ior__(self, other: ParameterDict) -> Self: ...
