import collections
from typing import Any

import torch
from torch.export.exported_program import ExportGraphSignature
from torch.fx._symbolic_trace import _ConstantAttributeType

log = ...

class ConstantAttrMap(collections.abc.MutableMapping):
    def __init__(self) -> None: ...
    def __getitem__(self, key: _ConstantAttributeType) -> Any: ...
    def __setitem__(self, key: _ConstantAttributeType, value) -> None: ...
    def add(self, key: _ConstantAttributeType, value: Any) -> None: ...
    def __delitem__(self, key: _ConstantAttributeType) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...

def get_constant_fqn(node: torch.fx.Node, constant_name: str) -> str: ...
def lift_constants_pass(
    gm: torch.fx.GraphModule, graph_signature: ExportGraphSignature, constant_attrs: ConstantAttrMap
) -> dict[str, _ConstantAttributeType]: ...
def rewrite_script_object_meta(gm: torch.fx.GraphModule) -> dict[str, _ConstantAttributeType]: ...
