import torch
import torch.ao.nn.intrinsic as nni
import torch.ao.nn.quantized as nnq

__all__ = ["LinearLeakyReLU", "LinearReLU", "LinearTanh"]

class LinearReLU(nnq.Linear):
    _FLOAT_MODULE = nni.LinearReLU
    def __init__(self, in_features, out_features, bias=..., dtype=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> Self: ...
    @classmethod
    def from_reference(cls, ref_linear_relu, output_scale, output_zero_point) -> Self: ...

class LinearLeakyReLU(nnq.Linear):
    _FLOAT_MODULE = nni.LinearLeakyReLU
    def __init__(self, in_features, out_features, negative_slope, bias=..., dtype=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> Self: ...
    @classmethod
    def from_reference(cls, ref_mod, output_scale, output_zero_point) -> Self: ...

class LinearTanh(nnq.Linear):
    _FLOAT_MODULE = nni.LinearTanh
    def __init__(self, in_features, out_features, bias=..., dtype=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> Self: ...
    @classmethod
    def from_reference(cls, ref_mod, output_scale, output_zero_point) -> Self: ...
